### ISSUE TITLE
Update build scripts according to issues with QSQL

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6326] opened 2022-09-02 15:25 UTC
- For Jenkins make sure that we build everything from contrib EXCEPT sqlite
- Update dockerfiles
- Update docs
- Update CMake to make sure that we never have two different sqlite libraries
- Test pyopenms thoroughly
- Make sure that sqlite is placed in a directory where Qt finds it for EVERY OS, the KNIME package and pyopenms

**Comment by jpfeuffer** [comment] 2022-09-02 15:26
#5781

**Comment by jpfeuffer** [comment] 2022-09-08 19:07
https://stackoverflow.com/questions/72344579/cmake-avoid-copying-qt5-dlls-on-windows
will be helpful

**Comment by poshul** [comment] 2022-10-13 14:52
This is now working. I've tested the resulting installers in Windows and Ubuntu, and they work well

**Comment by poshul** [comment] 2022-10-17 15:17
> This is now working. I've tested the resulting installers in Windows and Ubuntu, and they work well

Packages build and install, but at least for windows tools which require qsql error out. I've opened a PR to make sure that the required libs are installed in linux. For windows after some brief exploration it looks like we could use https://doc.qt.io/qt-5/windows-deployment.html on the build system to make sure the correct libs were added.

**Comment by jpfeuffer** [comment] 2022-10-17 21:24
Yes that is probably your best bet. Note that you should remove the manual copy commands that we introduced for the basic library DLLs. (There it was easy since you could just copy them to the bin folder. Now you need to create a directory structure and probably a config file, that's why I would indeed suggest windeployqt.)

You can try :
https://stackoverflow.com/questions/41193584/deploy-all-qt-dependencies-when-building
or even more future-proof (if we ever rely only on CPack and not custom NSIS scripts):
https://blog.nathanosman.com/2017/11/24/using-windeployqt-with-cpack.html

**Comment by poshul** [comment] 2022-11-04 14:27
adding qt.conf in Mac lets us put plugins where we want. This works for command line tools.

**Comment by poshul** [comment] 2022-11-08 14:17
Okay, should be done now. Will confirm tomorrow with the nightlies.

**Comment by poshul** [comment] 2022-11-09 09:26
Confirmed fixed on both Mac and Windows

**Closed by poshul** 2022-11-09 09:26 UTC
Labels: blocker

**Comment by jpfeuffer** [comment] 2022-11-09 09:53
We still need disclaimers for pyopenms and TOPPView. Or Known issues.

**Comment by poshul** [comment] 2022-11-09 09:55
Where do we traditionally store "Known Issues"? What's the disclaimer on pyopenms? The issues with the tests under Mac?

**Comment by jpfeuffer** [comment] 2022-11-09 10:31
No, SQL will not work there, too. Traditionally the Known Issues are in the oxygen under installers. But I am not sure if this is very prominent.

**Comment by hendrikweisser** [comment] 2022-11-09 10:52
> Traditionally the Known Issues are in the oxygen under installers.

Known Issues should go in the release notes, too.

**Comment by tjeerdijk** [comment] 2022-11-09 16:36
We have also added known issues to the new openms manual, for example here: https://openms.readthedocs.io/en/latest/installations/installation-on-macos.html#known-issues

On 9. Nov 2022, at 11:52, hendrikweisser ***@***.******@***.***>> wrote:

Traditionally the Known Issues are in the oxygen under installers.

Known Issues should go in the release notes, too.

**Comment by jpfeuffer** [comment] 2022-11-09 16:37
Ah yes. Known issues and installers moved.
So Changelog and OpenMS-docs it is.

**Comment by tjeerdijk** [comment] 2022-11-09 16:40
To add to this: the new openms readthedocs manual is versioned so known issues can be different for different releases

On 9. Nov 2022, at 17:37, Julianus Pfeuffer ***@***.******@***.***>> wrote:



Ah yes. Known issues and installers moved.
So Changelog and OpenMS-docs it is.
