### ISSUE TITLE
zlib.dll missing?

### ISSUE THREAD

**Issue by TimKarr** [OpenMS/OpenMS#6865] opened 2023-05-15 16:20 UTC
Error message indicates the zlib.dll file is "not found". However, there is a zlib file in "Program Files/OpenMS-2.8.0/bin/platforms" but is apparently not either "seen" by the computer system or otherwise corrupted? Have tried reinstalling numerous times without success.

![image](https://github.com/OpenMS/OpenMS/assets/64794204/2c4c5876-6daf-4bad-9820-68d0a4a0f149)
![TOPPView error](https://github.com/OpenMS/OpenMS/assets/64794204/950b8845-d719-48da-8a0c-87bf7e5a9b97)

**Comment by cbielow** [comment] 2023-05-15 20:26
Did you download the installer for OpenMS 2.8 here from here:
https://github.com/OpenMS/OpenMS/releases/tag/Release2.8.0
?

If yes, I can reproduce the problem.
The zlib is indeed missing from the installer.

Quickfix: copy the zlib.dll (contained within the attached zip file) to this post to the bin/ subdirectory of the OpenMS installation, usually at `C:\Program Files\OpenMS-2.8.0\bin`, so you get `C:\Program Files\OpenMS-2.8.0\bin\zlib.dll`.

[zlib.zip](https://github.com/OpenMS/OpenMS/files/11481695/zlib.zip)

We will probably release a new installer soonish to fix the general problem.

**Comment by TimKarr** [comment] 2023-05-15 21:21
Hi Chris,

OK, thanks, looking forward to buying you a large stein of lager at our next encounter! Everything opens as expected, looking forward to mastering this beast!

Are you planning on attending ASMS this year in Houston?

Again, many thanks 🙂.

Tim

--

Timothy L. Karr, PhD

Neurodegenerative Disease Research Center

Assistant Director, KE Operations

Manager, Biosciences Mass Spec/Proteomics Core

Associate Research Professor, Biodesign Institute

Associate Editor, Molecular and Cellular Proteomics

https://cores.research.asu.edu/mass-spec/about

[cid:41140d38-9102-492a-b9ca-6bab28670f48]

________________________________

**Comment by jpfeuffer** [comment] 2023-05-15 22:25
I'm glad the workaround works.
Regarding the underlying problem: Our cmake script only copies transitive dependencies when they are found by a DependencyWalker-like program.
The dynamic zlib dependency is introduced by Qt. OpenMS and Boost link to it statically.

**Comment by TimKarr** [comment] 2023-05-16 05:17
Thanks to everyone on the team for this quick response, much appreciated.

**Comment by jpfeuffer** [comment] 2023-05-16 12:15
Aaah sorry, I made some mistake, this issue is about the 2.8.0 release?
Yes, 2.8 was a conda-first release with untested installers.
In the upcoming 3.0 this problem is fixed!

We will evaluate if we can reupload a fixed installer for 2.8 but since 3.0 is close we will have to see.

**Closed** 2024-02-12 10:09 UTC
