### ISSUE TITLE
TOPPView crashes on MRM data

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2452] opened 2017-03-10 15:53 UTC
When I browse spectra TV crashes with a segmentation fault.
mzML:
https://gist.github.com/timosachsenberg/01485463d9ba66d524505a8190cc9ccd

**Comment by timosachsenberg** [comment] 2017-03-10 16:01
also the spectra list is behaving strangely. Selection of single transition often leads to the selection of a whole  span of rows.
![image](https://cloud.githubusercontent.com/assets/5803621/23802319/3929d12a-05b3-11e7-8f64-2e7572460244.png)

**Comment by oliveralka** [comment] 2017-03-10 18:47
Could not reproduce the crashing part, but the selection issue (OpenMs 2.1.0, OSX 10.12.3). Was able to select single transitions only by using the arrow keys.

**Comment by hroest** [comment] 2017-03-10 23:06
also works for me with newest `develop`

![screenshot from 2017-03-10 15-05-25](https://cloud.githubusercontent.com/assets/464014/23816718/2be10156-05a3-11e7-99d7-7483203680dc.png)
![screenshot from 2017-03-10 15-06-00](https://cloud.githubusercontent.com/assets/464014/23816720/2d80f9c6-05a3-11e7-863f-6a845e4c5d0e.png)

**Comment by hroest** [comment] 2017-03-10 23:15
PS: the support for chromatograms is somewhat hacky

**Comment by hroest** [comment] 2017-04-28 18:24
@timosachsenberg can you reproduce this? can we close this?

**Closed** 2017-04-30 07:13 UTC
Labels: defect, invalid
