### ISSUE TITLE
Percolator reports all peptides with 1 score in OpenMS 2.3 with labeled samples

### ISSUE THREAD

**Issue by algom** [OpenMS/OpenMS#3188] opened 2018-01-22 13:46 UTC
I have been trying to integrate Percolator to my workflow in OpenMS 2.3 (TOPPAS on Windows) but so far have not succeed. This issue might be related to https://github.com/OpenMS/OpenMS/issues/3071.

My workflow is simple and is just an adaptation from a post of Mathew The on the Gitter OpenMS/Knime chat, but has not been succesful.

MSGFPlusAdapter —> PeptideIndexer —> PercolatorAdapter

I can reproduce Mathew The results, with the yeast test file, however I have no luck with my test file which is a Formaldehyde labeled sample (K and n-term labeled) measured in a Qexactive. The changes to the workflow thus are only adding the fixed modification (CAM, K and n-term dimethylation).

I have also tried to do the search with a database without decoys and let the MSGFPlusAdapter add the decoys (and of course removing the peptide indexer node). I also have done it with the XtandemAdapter, with similar results. 

Percolator runs through, but using MSGF in the training portion reports 0 PSMs at q < 0.01, even though before training recognizes both targets and decoys, and finally reports "0 suitable peptides found". If I use the mzid output of msgfplus as input instead, it does recognize PSMs below q 0.01 at the training but it also ends with 0 suitable peptides. Looking at the produced idxml file, the first part of the file, protein section all seem to have a score of 0, whereas at the peptide level all get a score of 1. Running it with xTandem, does reports PSMs below q 0.01 at training but ends with the same result (All peptides with score 1). 

If I take the MSGFplusAdapter mzid output and do msgf2pin and percolator on the command line in the same PC, percolator runs fine, reports both peptides at training (at all iterations) and finds suitable peptides, with probabilities from 0-1 in the end.

Setting debugging at 5 in PercolatorAdapter to keep the intermediate files I get the pin input file (which I guess comes from the idxml) and what I guess the target and decoy output. Running percolator on the command line with that pin file (Of both xTandem and MSGFplus) also runs through, although it does not find peptides in all iterations at training with msgf input thus resets the vector, however in the end finds peptides below q 0.01.

Comparing both files (msgf2pin/percolator and pin form debugging) shows that msgf2pin or tandem2pin annotates the labeling as e.g. K.[UNIMOD:36] whereas the openms adaptor annotates them as K..(Dimethyl) (2 dots after K), and the one form msgf2pin does not annotate the CAM. The other differences is a lack of the second line in the one produced by the PercolatorAdapter (which includes the DefaultDirection). 
After parsing the file to the same notation (UNIMOD) there is a 81% overlap on the peptides at q<0.01 when comapring both files. 

Any thoughts?

I have attached a folder with the workflow and some outputs.

[msgfperc_git.zip](https://github.com/OpenMS/OpenMS/files/1652136/msgfperc_git.zip)

**Comment by MatthewThe** [comment] 2018-01-22 14:39
On first sight, the problem might lie in the double periods `K..(Dimethyl)etc`, since we match ids between the input idXML and percolator results based on `scan_id+peptide`. I could not find the input idXML in your folder, that would be useful for debugging this.

The protein scores of 0 might be a result of providing a concatenated target+decoy fasta file to percolator, which I will try to fix in the percolator code.

**Comment by algom** [comment] 2018-01-22 14:47
Thanks for looking at this.

I attach the input file after PeptideIndexer so that target and decoys are annotated.
[BM2000_input_idxml.zip](https://github.com/OpenMS/OpenMS/files/1652335/BM2000_input_idxml.zip)

**Comment by MatthewThe** [comment] 2018-01-22 15:04
Thanks, the problem is that the spaces got lost while parsing the spectrum identifier, i.e. `controllerType=0 controllerNumber=1 scan=2130` became `controllerType=0controllerNumber=1scan=2130`. I think we can simply remove the `removeWhitespaces()` here: https://github.com/OpenMS/OpenMS/blob/develop/src/topp/PercolatorAdapter.cpp#L288

**Comment by timosachsenberg** [comment] 2018-01-22 16:11
Keeping the spaces results in:
http://cdash.openms.de/viewTest.php?onlyfailed&buildid=254799
Hyperparameters: selectionFdr=0.5, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile /tmp/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_1/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_2_pin.tab
Features:
mass peplen charge2 charge3 enzN enzC enzInt dm absdm COMET:deltCn COMET:deltLCn COMET:lnExpect MS:1002252 MS:1002255 COMET:lnNumSP COMET:lnRankSP COMET:IonFrac 
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read PSMid or label.

Percolator problem. Aborting! Calling command was: '/home/travis/build/OpenMS/OpenMS/_thirdparty/Percolator/percolator "-U--m-/tmp/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_1/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_2_target_pout_psms.tab--M-/tmp/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_1/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_2_decoy_pout_psms.tab--F-0.5--t-0.5-/tmp/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_1/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_2_pin.tab".
Set debug level to >=2 to keep the temporary files at '/tmp/20180122_155615_travis-job-openms-openms-331871466.travisci.net_27926_1/'

**Comment by MatthewThe** [comment] 2018-01-23 12:30
Turns out my first hunch was the right one: the extra dot in the peptide sequence breaks the matching of identifiers (this was actually listed as a TODO...): https://github.com/OpenMS/OpenMS/blob/develop/src/topp/PercolatorAdapter.cpp#L145

I guess we should split on the first and last period, instead of on every period. Not sure if there are also cases where the `aa_before` and `aa_after` fields could contain periods as well though.

**Comment by jpfeuffer** [comment] 2018-01-23 12:32
It could be due to our changes in handling of peptide termini.
https://github.com/OpenMS/OpenMS/blob/develop/src/topp/PercolatorAdapter.cpp#L457
Not sure if the line above is still correct.

**Comment by jpfeuffer** [comment] 2018-01-23 12:37
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/CHEMISTRY/AASequence.cpp#L798

This shows how a sequence is converted to a String. By now I think it includes the dots if there is a terminal modification.

**Comment by timosachsenberg** [comment] 2018-01-23 12:56
@jpfeuffer is right. Dots are added if a terminal modification is present. Note that a modification at the last amino acid can be both specific to a terminus (.) or a modification with site specificity ANYWHERE (no .). 
To distinguish those, e.g.: PEPTIDEK.(Acetyl) and PEPTIDEK(Acetyl) are used.

**Comment by timosachsenberg** [comment] 2018-01-23 12:58
aa before and aa after should not be a dot.
They are either a AA, '[' or ']':
```
const char PeptideEvidence::N_TERMINAL_AA = '[';
const char PeptideEvidence::C_TERMINAL_AA = ']';
```

**Comment by algom** [comment] 2018-02-06 14:58
Any news on this issue?
I also tried to circumvent the dots issue by changing the idxml file produced by PeptideIndexer and removing the dot in the terminal modification eg ".(Dimethyl)AVVESIQR" to "(Dimethyl)AVVESIQR" without dot but I guess the adapter later again adds the dot as the interim files (generated pin file still contains the dot), and still fails as the original idxml file.

It also caught my attention that the generated idxml file from the PetideIndexer includes two tags annotate if it is a decoy or target:

<ProteinHit id="PH_1" accession="sp|Q9Z3A0|YJGW_ECOLI" score="0" sequence="" >
 <UserParam type="string" name="isDecoy" value="false"/>
 <UserParam type="string" name="target_decoy" value="target"/>

Whereas the search done without a database containing reverse/shuffled entries and letting MSGFPlusAdapter add the reverse only writes:

<ProteinHit id="PH_1" accession="sp|Q9Z3A0|YJGW_ECOLI" score="0" sequence="" >
 <UserParam type="string" name="isDecoy" value="false"/>

I have also parse the idxml file like that but also does not have any effect, and running MSGFPlus -> PercolatorAdapter or MSGFPlus -> PeptideIndexer -> PercolatorAdapter (with a database including shuffled entries) with the yeast example (Not labeled at N-termini) runs ok in both.

**Comment by lars20070** [comment] 2018-04-04 13:24
Do you have a (small) `mzML` and `fasta` for your example?

<img width="1002" alt="screen shot 2018-04-04 at 14 23 51" src="https://user-images.githubusercontent.com/6149805/38310204-e48fde68-3813-11e8-9d71-16ed9b532ea7.png">

**Comment by lars20070** [comment] 2018-04-04 14:16
Better please send me a (small) indexed dimenthyl `idXML` that can be used as input for the `PercolatorAdapeter`. Thanks.

**Comment by lars20070** [comment] 2018-04-04 15:30
I uploaded a test input dataset [here](https://gist.github.com/lars20070/b15eab802154981edff62b3e0b68c3f0).

**Comment by lars20070** [comment] 2018-04-04 15:39
@mwalzer What is the recommended application of the `PercolatorAdapter`?
```
MSGFPlusAdapter --> PeptideIndexer --> PercolatorAdapter
```
or 
```
MSGFPlusAdapter --> PeptideIndexer --> PSMFeatureExtractor --> PercolatorAdapter
```
Can the `PSMFeatureExtractor` go into the adapter?

**Comment by lars20070** [comment] 2018-04-04 15:54
@MatthewThe Even after resolving the '..' sequence issue, I get an `Exception caught: ERROR: Reading tab file, too few features present.` error.
```
Percolator version 3.01, Build Date Jul 31 2017 10:51:02
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
/Users/lars/Code/THIRDPARTY/MacOS/64bit/Percolator/percolator -U -m /var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_target_pout_psms.tab -M /var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_decoy_pout_psms.tab /var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_pin.tab
Started Wed Apr  4 16:52:25 2018
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile /var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_pin.tab
Features:

Exception caught: ERROR: Reading tab file, too few features present.

Percolator problem. Aborting! Calling command was: 'percolator "-U--m-/var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_target_pout_psms.tab--M-/var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_decoy_pout_psms.tab-/var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/20180404_165225_remote239-113.home.uni-freiburg.de_69737_2_pin.tab".
Set debug level to >=2 to keep the temporary files at '/var/folders/bf/8phydss51y155wc4d3nmsr3h0000gn/T/20180404_165225_remote239-113.home.uni-freiburg.de_69737_1/'
PercolatorAdapter took 0.47 s (wall), 0.43 s (CPU), 0.02 s (system), 0.41 s (user).
```

**Comment by lars20070** [comment] 2018-04-04 18:37
@mwalzer @MatthewThe If I switch on `add_features` in `MSGFPlusAdapter`, do I still need to run `PSMFeatureExtractor`?

**Closed** 2018-04-13 05:24 UTC
Labels: TOPP, defect, major
