### ISSUE TITLE
EICExtractor in KNIME

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2612] opened 2017-05-18 11:23 UTC
EICExtractor KNIME node has probably the wrong input type to work as expected.
`ERROR EICExtractor         2:3        Execute failed: com.genericworkflownodes.knime.parameter.FileListParameter cannot be cast to com.genericworkflownodes.knime.parameter.FileParameter
`
For convenience, I attached a [_knwf_ ](https://github.com/OpenMS/OpenMS/files/1010677/EICExtractor_test.knwf.zip). 

EICExtractor works fine with the chosen files from the cmdl. 

Also, seems we don't sport a TOPP test for EICExtractor.

knwf screenshot for timo's convenience:
![knwf screenshot for timo's convenience](https://cloud.githubusercontent.com/assets/5859205/26200427/ff51e32c-3bc5-11e7-99b9-71021251150e.png)

**Comment by timosachsenberg** [comment] 2017-05-18 11:26
on mobile right now so can't open the workflow. Did you provide a file list instead of single file?

**Comment by mwalzer** [comment] 2017-05-18 11:27
BTW, FileConverter usage featureXML -> edta does not work like this in knime either. See the _knwf_. 
@jpfeuffer is the FileConverter mime type issue known already? (couldn't find any issue ticket)

**Comment by jpfeuffer** [comment] 2017-05-18 11:30
Can you upload an edta?

**Comment by jpfeuffer** [comment] 2017-05-18 11:32
FileConverter works, did not check the output.

**Comment by mwalzer** [comment] 2017-05-18 11:33
Use `FileConverter -in ../oms-src/src/tests/topp/FeatureFinder_1_output.featureXML -out /tmp/whop.edta`

**Comment by jpfeuffer** [comment] 2017-05-18 11:36
Ok it seems the problem is an empty optional File List Input.

**Comment by mwalzer** [comment] 2017-05-18 11:44
@timosachsenberg no.

**Comment by mwalzer** [comment] 2017-05-18 11:56
@jpfeuffer so this is similar to https://github.com/genericworkflownodes/GenericKnimeNodes/issues/129 ?

**Comment by jpfeuffer** [comment] 2017-07-03 14:47
Please check again, once there are new nightlies. Probably already solved.

**Comment by hroest** [comment] 2017-10-22 12:21
can we close this?

**Closed** 2019-10-22 13:42 UTC
Labels: (Unit) Tests, KNIME, defect, unconfirmed
