### ISSUE TITLE
MzTab crashes on idXML converted from mzIdentML

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#2445] opened 2017-03-07 10:13 UTC
```
Error: Unexpected internal error (the element 'Gln->pyro-Glu (Q)' could not be found)
```
is raised by this, kind of, minimal idXML.

If I change 'Gln->pyro-Glu (Q)' to 'Gln->pyro-Glu (N-term Q)' it works.
Note that the later is the correct notation, so there is probably something going wrong when converted from mzIdentML.

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://open-ms.sourceforge.net/XSL/IdXML.xsl" ?>
<IdXML version="1.4" xsi:noNamespaceSchemaLocation="http://open-ms.sourceforge.net/SCHEMAS/IdXML_1_4.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <SearchParameters id="SP_0" db="/stornext/Sysbio/data/Projects/ProtemicsLab/Databases/Ecoli_Human_proteome_cont.fasta" db_version="" taxonomy="" mass_type="monoisotopic" charges="" enzyme="trypsin" missed_cleavages="1000" precursor_peak_tolerance="10" precursor_peak_tolerance_ppm="false" peak_mass_tolerance="0" peak_mass_tolerance_ppm="false" >
                <FixedModification name="Carbamidomethyl (C)" />
                <VariableModification name="Gln-&gt;pyro-Glu (Q)" />
        </SearchParameters>
        <IdentificationRun date="2017-03-03T20:58:42" search_engine="MS-GF+" search_engine_version="Release (v2017.01.27)" search_parameters_ref="SP_0" >
                <ProteinIdentification score_type="" higher_score_better="true" significance_threshold="0" >
                        <ProteinHit id="PH_0" accession="tr|J3QRQ7|DDX5" score="0" sequence="" >
                                <UserParam type="string" name="isDecoy" value="false"/>
                        </ProteinHit>
                        <UserParam type="stringList" name="spectra_data" value="[/file.mzML]"/>
                </ProteinIdentification>
                <PeptideIdentification score_type="MS-GF:RawScore" higher_score_better="true" significance_threshold="0" MZ="1115.22485351562" RT="4928.527" spectrum_reference="scan=74855" >
                        <PeptideHit score="209" sequence=".(Gln->pyro-Glu)QNFTEPTAIQAQGWPVALSGLDMVGVAQTGSGK" charge="3" aa_before="R" aa_after="T" protein_refs="PH_0" >
                                <UserParam type="float" name="MS:1002049" value="209"/>
                                <UserParam type="float" name="MS:1002050" value="219"/>
                                <UserParam type="float" name="MS:1002052" value="5.830208e-34"/>
                                <UserParam type="float" name="MS:1002053" value="1.8772127e-26"/>
                                <UserParam type="float" name="MS:1002054" value="0"/>
                                <UserParam type="float" name="MS:1002055" value="0"/>
                                <UserParam type="string" name="AssumedDissociationMethod" value="CID"/>
                                <UserParam type="string" name="CTermIonCurrentRatio" value="0.18738566"/>
                                <UserParam type="string" name="ExplainedIonCurrentRatio" value="0.31501722"/>
                                <UserParam type="string" name="IsotopeError" value="2"/>
                                <UserParam type="string" name="MS2IonCurrent" value="374970.0"/>
                                <UserParam type="string" name="MeanErrorAll" value="5.058933"/>
                                <UserParam type="string" name="MeanErrorTop7" value="3.5459135"/>
                                <UserParam type="string" name="MeanRelErrorAll" value="1.037312"/>
                                <UserParam type="string" name="MeanRelErrorTop7" value="-0.20190702"/>
                                <UserParam type="string" name="NTermIonCurrentRatio" value="0.12763155"/>
                                <UserParam type="string" name="NumMatchedMainIons" value="38"/>
                                <UserParam type="string" name="StdevErrorAll" value="3.984174"/>
                                <UserParam type="string" name="StdevErrorTop7" value="2.0206013"/>
                                <UserParam type="string" name="StdevRelErrorAll" value="6.355346"/>
                                <UserParam type="string" name="StdevRelErrorTop7" value="4.0762196"/>
                                <UserParam type="float" name="calcMZ" value="1114.55383300781"/>
                                <UserParam type="int" name="pass_threshold" value="1"/>
                                <UserParam type="int" name="start" value="7"/>
                                <UserParam type="int" name="end" value="39"/>
                                <UserParam type="string" name="target_decoy" value="target"/>
                        </PeptideHit>
                        <UserParam type="string" name="MS:1001115" value="74855"/>
                </PeptideIdentification>
        </IdentificationRun>
</IdXML>
```

**Comment by timosachsenberg** [comment] 2017-03-07 10:17
Digging deeper it seems to be a Problem in the mzIdentML part - see a corresponding mzIdentML entry:
```
  <Peptide id="Pep_[-17QNFTEPTAIQAQGWPVALSGLDMVGVAQTGSGK">
    <PeptideSequence>QNFTEPTAIQAQGWPVALSGLDMVGVAQTGSGK</PeptideSequence>
    <Modification location="0" monoisotopicMassDelta="-17.026549105">
      <cvParam cvRef="UNIMOD" accession="UNIMOD:28" name="Gln-&gt;pyro-Glu"/>
    </Modification>
  </Peptide>
```
@mwalzer or @enetz can you confirm and fix?

see the unimod entry below. I am pretty sure that the mzIdentML reader writes the wrong modification string.
```
Unimod, View record [ Accession #: 28 ]
Accession # 	28	PSI-MS Name 	Gln->pyro-Glu	Interim Name 	Pyro-glu
Description 	Pyro-glu from Q
Composition 	H(-3) N(-1)	Monoisotopic 	-17.026549	Average 	-17.0305
Specificity Definition 1
Site 	Q	Position 	Any N-term	Classification 	Artefact
```

**Comment by hendrikweisser** [comment] 2017-03-07 10:29
I think this could be a duplicate of #2404, which is already fixed (thanks @mwalzer!).

@timosachsenberg: Do you have the mzid file? Did you try to convert it with a build of OpenMS that already contains #2422?

**Comment by timosachsenberg** [comment] 2017-03-07 10:42
Thanks I will check and report back

**Comment by timosachsenberg** [comment] 2017-03-07 11:02
I still get the same error so I guess it is not fixed. I can provide the mzIdentML.

**Comment by hendrikweisser** [comment] 2017-03-07 11:52
> I still get the same error so I guess it is not fixed.

How annoying. Can you provide the "SearchModification" element from the mzid where the "Gln->pyro-Glu" is defined?

**Comment by timosachsenberg** [comment] 2017-03-07 16:49
```
    <ModificationParams>
      <SearchModification fixedMod="true" massDelta="57.021465" residues="C">
        <cvParam cvRef="UNIMOD" accession="UNIMOD:4" name="Carbamidomethyl"/>
      </SearchModification>
      <SearchModification fixedMod="false" massDelta="15.994915" residues="M">
        <cvParam cvRef="UNIMOD" accession="UNIMOD:35" name="Oxidation"/>
      </SearchModification>
      <SearchModification fixedMod="false" massDelta="-17.026548" residues="Q">
        <SpecificityRules>
          <cvParam cvRef="PSI-MS" accession="MS:1001189" name="modification specificity N-term"/>
        </SpecificityRules>
        <cvParam cvRef="UNIMOD" accession="UNIMOD:28" name="Gln-&gt;pyro-Glu"/>
      </SearchModification>
      <SearchModification fixedMod="false" massDelta="42.010563" residues=".">
        <SpecificityRules>
          <cvParam cvRef="PSI-MS" accession="MS:1002057" name="modification specificity protein N-term"/>
        </SpecificityRules>
        <cvParam cvRef="UNIMOD" accession="UNIMOD:1" name="Acetyl"/>
      </SearchModification>
    </ModificationParams>
```

**Comment by timosachsenberg** [comment] 2017-03-07 17:26
wait a second before you try to confirm it - maybe I made a mistake. Need to quickly check it again...

**Comment by timosachsenberg** [comment] 2017-03-07 17:39
Good news - pyro-Glu seems to work now. But I get now an:
```
Error: Unexpected internal error (The value 'Acetyl' was used but is not valid! Retrieving the modification failed. It is not available for the residue '' and term specificity 4.)
```

**Comment by enetz** [comment] 2017-03-07 18:21
From what I can tell after tinkering with ModificationsDB, I do not think the term specificities 3 (PROTEIN_C_TERM) and 4 (PROTEIN_N_TERM) are actually used in ModsDB, although they are defined in ResidueModification.h.
All the terminal modifications from unimod are read in as just 1 (C_TERM) or 2 (N_TERM).
So if this Acetyl mod is read from mzIdentML as spec 4 but only contained in ModsDB with spec 2,
it is no wonder it can not match these two.
Or has that changed in the last few months?

**Comment by enetz** [comment] 2017-03-07 18:27
Yep, right here:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/UnimodXMLHandler.cpp#L109

**Comment by timosachsenberg** [comment] 2017-03-08 14:42
makes sense... @hendrikweisser @enetz what would you think is a good way to solve this? Instead of only adding it as N_TERM also add it as 4 (PROTEIN_N_TERM)? Or probably cleaner only add it as PROTEIN_N_TERM?

**Comment by hendrikweisser** [comment] 2017-03-08 14:50
Good find, @enetz!

@timosachsenberg: I think for now the mzIdentML parser would have to treat "protein N/C-term" as just "N/C-term". OpenMS currently can't handle protein term specificity and support would have to be added at quite a fundamental level. That might be a good topic for the developer meeting.

**Comment by enetz** [comment] 2017-03-08 15:30
I agree with adding it to the dev meeting agenda.
There are also other issues with modifications in OpenMS, that we can include.

**Comment by hendrikweisser** [comment] 2017-03-08 15:37
> I agree with adding it to the dev meeting agenda.

I've added it here: https://github.com/OpenMS/OpenMS/wiki/Retreat-Spring-2017#handling-of-modifications

**Comment by lars20070** [comment] 2017-03-08 16:12
Do you think #2343 is related? The crashes occur only when the `featureXML` is annotated with IDs.
https://github.com/OpenMS/OpenMS/issues/2343#issuecomment-280350978

**Comment by timosachsenberg** [comment] 2017-03-17 12:56
I prepared a PR that changes the mzIdentML parser to treat "protein N/C-term" as just "N/C-term".
conversion now works on my pc

**Comment by mwalzer** [comment] 2017-03-17 14:12
Uhm, btw, why not export directly from mzid? Internal datastructure is the same, idXML format opportunities to mess up the information via one further format conversion removed.

**Comment by timosachsenberg** [comment] 2017-03-17 14:15
the problem is not the idXML - OpenMS currently can't handle protein term specificity and support would have to be added at quite a fundamental level.

**Comment by mwalzer** [comment] 2017-03-17 14:17
Exactly, but the issue says so. Contributes to confusion. Maybe open another issue?

**Comment by timosachsenberg** [comment] 2017-03-17 14:26
There is already an open issue: https://github.com/OpenMS/OpenMS/issues/1913
I will close this one after the PR is clean and merged

**Comment by mwalzer** [comment] 2017-03-17 14:26
:+1:

**Closed** 2017-03-21 15:08 UTC
