### ISSUE TITLE
The question of the SiriusAdapter node 

### ISSUE THREAD

**Issue by hello-lei** [OpenMS/OpenMS#5508] opened 2021-08-31 07:06 UTC
Hi,
I use the workflow to further identify the compound, then the mzTable is empty, but the data of the SIRIUS.ms is not empty![image](https://user-images.githubusercontent.com/83147334/131458472-fa5c09c6-f566-467a-a10f-c17ffc32febb.png)
![Uploading image.png…]()

Thank you very much!
@Oliver Alka

**Comment by oliveralka** [comment] 2021-08-31 09:23
Hi @hello-lei,
what is the purpose of having the PeakPickerHiRes and the HighResPrecursorMAssCorrector twice in your workflow? 

Which KNIME and OpenMS Version are you using? 

Could you please check the `View: SiriusAdapter Std Output` and `View: SiriusAdaper Error Output`
by right-clicking on the SiriusAdapter node?

MzTab-Reader has multiple output e.g. Metadata_Section, Protein_Section, ...
Did you check the correct section by using right-click and choosing `4: Small Molecule Section` on the MzTabReader Node?

**Comment by hello-lei** [comment] 2021-08-31 11:13
The PeakPickerHiRes convert the  profile file to centroid file and the HighResPrecursorMAssCorrector node corrects the mass and charge according the previous discussion.Because I try to change the empty data,but it doesn't work.
My KNIME is 4.4.0,OpenMS is 2.6.0.
![image](https://user-images.githubusercontent.com/83147334/131492738-3cca9d9c-5985-41ec-af11-73bfa1fd5e44.png)
 Since I update the Knime It became the ...and more.
![image](https://user-images.githubusercontent.com/83147334/131492902-1a308a1f-6432-403d-9a93-a82c7ea191cb.png)
Thank you very much.

**Comment by oliveralka** [comment] 2021-08-31 13:02
Could you please upgrade our KNIME Version to 4.4.1. The Std Output and Std Error work there as intended again. 
Please let me know the output of these.

**Comment by hello-lei** [comment] 2021-08-31 13:43
Ok,I will try it.Thank you!

**Comment by hello-lei** [comment] 2021-08-31 13:58
![image](https://user-images.githubusercontent.com/83147334/131515506-dfcdafda-5ece-45cd-af32-602183da0387.png)
![image](https://user-images.githubusercontent.com/83147334/131515615-501948b0-45d0-4b64-b8aa-18e5a1d69dd6.png)

**Comment by oliveralka** [comment] 2021-08-31 14:10
Thanks, could you upload the ones from the SiriusAdapter as well?

**Comment by hello-lei** [comment] 2021-08-31 14:16
I don't understand your meaning clearly? Is it?
![image](https://user-images.githubusercontent.com/83147334/131518770-0fc209cc-cd5d-48ab-95be-f40daaa9d1e4.png)

**Comment by hello-lei** [comment] 2021-08-31 14:18
![image](https://user-images.githubusercontent.com/83147334/131519275-75c03a63-82b1-472a-b228-567134dd612e.png)

**Comment by oliveralka** [comment] 2021-08-31 17:41
You accidentally uploaded the Std and Error Output of the MetaboliteAdductDecharger instead of the SiriusAdapter - I was regarding to those in my post above.

**Comment by hello-lei** [comment] 2021-09-01 00:43
Oh,I'm sorry I upload the wrong information.
![image](https://user-images.githubusercontent.com/83147334/131593749-175e7d77-1352-43f1-90b3-a00fa636b811.png)

**Comment by hello-lei** [comment] 2021-09-01 00:44
![image](https://user-images.githubusercontent.com/83147334/131593849-eeac6cc7-b30e-4ee3-9e67-811411495ae0.png)

**Comment by oliveralka** [comment] 2021-09-01 06:59
hm, from this it seems to work without any issues. 

What operating system are you using? Could you send me your workflow and example data to test?

**Comment by hello-lei** [comment] 2021-09-01 07:55
I try it as you said.It appears the wrong.
![image](https://user-images.githubusercontent.com/83147334/131633201-8d32e753-3f9e-46a1-b3a3-c7f6168a1800.png)
![image](https://user-images.githubusercontent.com/83147334/131634162-de0c1d9f-d787-4b81-83a9-ea5e12ad6e73.png)

**Comment by oliveralka** [comment] 2021-09-01 08:26
Indeed there seems to be something wrong on windows - thanks for letting us know. I will check it out.

**Comment by hello-lei** [comment] 2021-09-01 08:28
Ok,Thank you,I will appreciate your reply.

**Comment by hello-lei** [comment] 2021-09-02 14:21
Ok, thank you very much .Now,Does I  download the OpenMS one more? I don't quite understand the discussion.

**Comment by oliveralka** [comment] 2021-09-02 14:35
Yes, please install it one more time from the update site.
KNIME Update Site:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/knime-plugin/updateSite/RC/2.7.0/

It should now be the OpenMS Version 2.7.0 from 01.09.2021.

In addition you can download the updated SiriusAdapter workflow here:
https://github.com/OpenMS/Tutorials/blob/master/Workflows/Metabolite_DeNovoID.knwf
Maybe just to take a look and compare it with yours. Depending on your data the parameters have to be changed of course. 

You can find additional information to the workflow in our tutorial handout (Section: 6.3.6 De novo identification):
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/master/handout.pdf

**Comment by hello-lei** [comment] 2021-09-02 15:26
I will try it again,Thank your reply timely.May I have your personal email,I study the Openms in KNIME and I am a freshman.I often meets  some problems. The discussion is good for solving the questions.But this is not enough for me. 
Thank you very much!

**Comment by hello-lei** [comment] 2021-09-04 03:20
I download the latest OpenMS,But the workflow excute so long. it continues about 24 hours.
![image](https://user-images.githubusercontent.com/83147334/132080777-8818a773-63e9-4680-81dd-ce606526e812.png)

**Comment by oliveralka** [comment] 2021-09-04 09:17
In general that is a good sign. Which means that SIRIUS seems to process the data correctly. SIRIUS is very compute intensive and it might take a while to compute the results. What would you like to achieve and what are your current parameters in the SiriusAdapter?

**Comment by oliveralka** [comment] 2021-09-04 09:18
You could also test the workflow with the Tutorials Example Data just to be sure that everything is working correctly on your end. https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Data/latest/Example_Data/Metabolomics/

**Comment by hello-lei** [comment] 2021-09-05 02:26
The Example Data excuted successfullly.About my data, the parameters of SIRIUS is default.

**Comment by hello-lei** [comment] 2021-09-05 02:31
![image](https://user-images.githubusercontent.com/83147334/132112902-a90e13f5-290b-4afa-9610-1e595c742129.png)

**Comment by oliveralka** [comment] 2021-09-06 07:19
For runtime reduction, you can try to reduce the complexity of the data for SIRIUS, for example set the parameter `filter_by_num_masstraces` higher. For example `filter_by_num_masstraces = 3` will only export features to SIRIUS processing, which have the monoisotopic trace and 2 additional isotope traces. Of course with this step you also get less output depending on what you are interested in. 

The other option is to run the SIRIUSAdapter on a cluster or cloud infrastructure using a shell script. Do you have these kind of resources available to you?

**Comment by hello-lei** [comment] 2021-09-06 07:44
Yes,I am also satisfying with the workflow.
I try to change the key parameters to improve the speed.
I want to ask that the SIRIUSAdapter excutes also in KNIME.I don't have the resourses.I am interesting for the method.

**Comment by hello-lei** [comment] 2021-09-06 08:09
![image](https://user-images.githubusercontent.com/83147334/132181810-0128e3a0-ed47-4593-9aff-96b124a9e57a.png)
I choose the feature_only to true. The final output quickly.But the data is only 137rows.

**Comment by oliveralka** [comment] 2021-09-06 08:35
I guess that is due to the `filter_by_num_masstraces` parameter. You can set it to 2 or 1, but keep in mind that this will increase the runtime. 

You can also check your data and the features visually by using TOPPView. 
To be able to visualise the mass traces the parameter `report_convex_hulls` has to be switched on in the FeatureFinderMetabo.

Then you have to load a specific mzML with the corresponding featureXML in ToppView (same window, different layers). You are also able to filter based on number_of_masstraces to see how many features you can retain by your filtering and if the feature detection works as you intend. Maybe you have to tweak your parameters there as well to fit your dataset. 

TOPPView is an OpenMS Tool which is not available in KNIME and can be used to visualise Data. Please install OpenMS on your system if you would like to use it. You can find the currently latest version of OpenMS here:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/latest/

**Comment by hello-lei** [comment] 2021-09-06 10:47
Ok,you have a good idea.
Thank for your advice very much.I will use the OpenMS to inspect it.

**Comment by hello-lei** [comment] 2021-09-07 02:13
Hi，
I have some question to ask you.
a) The features find  51, is it ok?
b) The SiriusAdapter node refer to the database(BIO),and previous version have the various databases.
May be the feature have  51 due to the one database.
Thank you very much.
![image](https://user-images.githubusercontent.com/83147334/132273354-2a3e8e73-a279-473a-9636-22a1c4ac5759.png)
![image](https://user-images.githubusercontent.com/83147334/132273446-81c8ea21-b5b6-4264-a4d4-406a393c8171.png)

**Comment by oliveralka** [comment] 2021-09-07 06:10
a) I am sorry, but I am not able to state if 51 features are a "good" number, since it highly depends on your data and the research question. What do you want to achieve? Did you have a look at the feature detection and are happy with it? 

b) In terms of the databases, we should have the same standard parameters as the actual SIRIUS 4.9.3 implementation. The database `BIO` is used in terms of CSI:FingerID, since it entails all plausible biological explainable structures. Other databases such as `ALL` can contain predicted non biological structures, which do not make sense in the biological context. You can always change the parameter (`db`) to your liking. In the beginning, I would go with the standards.

The number of features to be processed by SIRIUS does not have anything to do with the database chosen used for fingerprinting by SIRIUS. The number of features come from the feature detection (`FeatureFinderMetabo`) and the filtering (`SiriusAdapterAlgorithim::preprocessing`) which entails complexity reduction via `filter_by_num_masstraces`. If you are not happy with the number - the first step is to check the feature detection and perform parameter optimisation (e.g. via `TOPPView`). In addition, you can set the filter parameter (`filter_by_num_masstraces`) to 1 to gain access to features with only the monoisotopic trace - but as indicated in a post above, this will increase the runtime of SIRIUS.

**Comment by hello-lei** [comment] 2021-09-07 07:57
Thank for your reply timely very much.
It is import for me to inspect the data through the TOPPView.I will check it using the TOPPView.

**Comment by oliveralka** [comment] 2021-09-10 06:23
I will close this issue since I think you have all relevant information, please either reopen the issue or write me on Gitter if anything pops up.

**Closed by oliveralka** 2021-09-10 06:23 UTC
