### ISSUE TITLE
build on ARMHF fails

### ISSUE THREAD

**Issue by lopippo** [OpenMS/OpenMS#4785] opened 2020-06-10 20:00 UTC
Greetings, 

building of OpenMS 2.5.0 fails on the ARMHF (and ARMEL) platform with the error listed at the bottom of the following page:

https://buildd.debian.org/status/fetch.php?pkg=openms&arch=armhf&ver=2.5.0%2Bcleaned1-1&stamp=1591794524&file=log

If you understand what is going on, that would be nice if you could provide me with a fix so that I could patch the code for Debian.

Thank you for your kind attention,

Sincerely,
Filippo

**Comment by jpfeuffer** [comment] 2020-06-11 10:08
When moving to Qt5 I remember having problems when using only QOpenGLFunctions (i.e. the OpenGL ES subset of OpenGL). To be honest I did not thoroughly evaluate alternatives since requiring full OpenGL 2.0 compatibility solved it.
So I think for this release the best would be to require software accelerated drivers that support full OpenGL 2.0 on ARM (not sure how or if possible though) or build OpenMS with the -DWITH_GUI=Off option there.

**Comment by lopippo** [comment] 2020-06-13 13:17
Thank you for your answer, Julianus. Need to think about it.

**Comment by poshul** [comment] 2021-06-22 10:02
As of March 2021 it looks like 2.6 is still failing on ARMHF (see https://buildd.debian.org/status/fetch.php?pkg=openms&arch=armhf&ver=2.6.0%2Bcleaned1-3&stamp=1614684297&raw=0)
@lopippo how would you like to proceed?

**Comment by jpfeuffer** [comment] 2021-06-22 10:18
Did you try the fix proposed in the linked bug report? I think it suggested to use
`libqt5opengl5-desktop-dev` instead of `libqt5opengl5-dev`.

I am not sure if we have the capabilities to investigate updates in our OpenGL painting code at the moment.
Last resort would be to disable OpenMS GUI on ARM then.

**Comment by poshul** [comment] 2021-06-22 10:25
It looks like it works on ARM64, it's just ARMHF and ARMEL.

**Comment by poshul** [comment] 2021-06-22 10:47
Also, it looks like 2.6 works Bullseye for ARMHF, so I think the issue is limited to Sid.

**Comment by poshul** [comment] 2021-06-29 12:11
I'm going to go ahead and close this. Please feel free to reach out if there are any updates.

**Closed by poshul** 2021-06-29 12:11 UTC

**Comment by lopippo** [comment] 2021-06-29 13:37
Greetings, Samuel,

On Tue, Jun 29, 2021 at 05:12:03AM -0700, Samuel Wein wrote:
>I'm going to go ahead and close this. Please feel free to reach out if there are any updates.

sorry for the late response. I'll check how it performs in latest testing.
Thanks !

Filippo

-- 

⢀⣴⠾⠻⢶⣦⠀  Filippo Rusconi, PhD
⣾⠁⢠⠒⠀⣿⡁   Research scientist at CNRS
⢿⡄⠘⠷⠚⠋⠀   Debian Developer
⠈⠳⣄⠀⠀⠀⠀  http://msxpertsuite.org
           http://www.debian.org
