### ISSUE TITLE
MzTab exporter does not write peptide_abundance_assay[1-n] rows from consensusXML input

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2483] opened 2017-03-27 18:35 UTC
It does however write peptide_abundance_study_variable[1-n].

**Comment by mwalzer** [comment] 2017-03-27 18:49
I think it should rather be writing assay abundances by default. Assays resemble closer in most cases, what information is stored in the feature handles of consensus features. (And study variables rather the consensus of consensus features.) 
I know the export is 'just' summary, but for most cases I see, the assay is needed first. And from the way we construct our workflows, the consensus features are firstly comprised of 'assay' level intensities (e.g. our tutorial LFQ workflow).
@timosachsenberg : what do you think?

**Comment by timosachsenberg** [comment] 2017-03-27 19:40
I agree but the problem is the standard requires us to report study variables. It would be redundant to report both assay and study variables. Not sure how we could handle this properly? Maybe I could suggest a change to the standard at the PSI meeting to allow only reporting assays but I am not sure if they will agree on this.

**Comment by timosachsenberg** [comment] 2017-05-02 13:34
I suggested the change in https://github.com/HUPO-PSI/mzTab/issues/29
closing the issue

**Closed by timosachsenberg** 2017-05-02 13:34 UTC
Labels: question
