### ISSUE TITLE
TOPPView crashs when loading mzML and featureXML [213]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#213] opened 2014-01-09 10:48 UTC
Submitted by aiche on 2010-11-11 14:20:19

TOPPView chrashs when loading mzML and corresponding featureXML (order is irrelevant).

Following message is reported on command line:

```
Error: Unexpected error (position<=pre_min_+pre_size_ MultiGradient::precalculatedColorAt(DoubleReal): position 98352103424 out of specified range (1.82871807384072e-05-98352103424)!)
Code location: /home/takifugu/aiche/RAID/open-ms-dev/openms-src/include/OpenMS/VISUAL/MultiGradient.h:124
```

**Comment by enetz** [comment] 2019-01-17 15:25
Release build just crashes with a segfault for me when I try to open these files.
Trying to debug with a debug build and running it with gdb, I suddenly get pop-ups in TOPPView.

`Caught exception: 'Precondition failed' with message 'position >= pre_min_ MultiGradient::precalculatedColorIndex(double): position -7172395 out of specified range (-5e-06-8028148.600005)!'`

and then

`This dataset contains negative intensities. Use it at your own risk!`

Btw. although this is not shown with the release build for some reason, a similar error also pops up without loading the mzML file with a debug build. It just doesn't seem to be fatal in this case:
`Caught exception: 'Precondition failed' with message 'position >= pre_min_ MultiGradient::precalculatedColorIndex(double): position -6910700 out of specified range (-5e-06-8028148.600005)!'`

Also this error message appears on the command line but not as a pop-up before the errors mentioned above:
`Caught exception: 'Precondition failed' with message 'pre_.size() != 0 MultiGradient::precalculatedColorIndex(double): Precalculation mode not activated!'`

So as @lars20070 wrote, the Problem seems to be that TOPPView expects numbers above `-5e-06`, while this featureXML contains an intensity of `-6910700`.
Unfortunately, on a release build this makes TOPPView crash with a segmentation fault even before one can see the warning for negative intensities.

This problem is caused by the calls to the function
`MultiGradient::activatePrecalculationMode(double min, double max, UInt steps)`
here: https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/MultiGradient.cpp#L258

because it is usually called with `0.0` as `min`, like in this case:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms_gui/source/VISUAL/Spectrum2DCanvas.cpp#L1088

Should we call it with something like `overall_data_range_.minPosition()[2]` instead?
Or transform negative numbers to their absolute value?
@lars20070 What is the meaning of these negative numbers and how do you expect them to be represented?

Disclaimer: i am not very familiar with this code and do not know what exactly `MultiGradient::activatePrecalculationMode` even does. I guess this is related to the automatic colour generation for the dots representing the features?

**Comment by lars20070** [comment] 2019-01-18 08:52
@enetz Thanks for looking into this!
IMO, `TOPPView` should represent negative intensities as zero and give a warning after loading.
The negative feature intensities are fixed in #3927.

**Comment by lars20070** [comment] 2019-01-24 15:40
@enetz IMO, intensity < 0  ==>  intensity = 0.

**Comment by hroest** [comment] 2019-01-26 15:43
>  IMO, `TOPPView` should represent negative intensities as zero and give a warning after loading.

:+1:

**Closed** 2019-01-26 21:54 UTC
Labels: TOPPView, critical, defect
