### ISSUE TITLE
IDFileConverter fails when converting psms to idXML

### ISSUE THREAD

**Issue by PayamEmami** [OpenMS/OpenMS#2243] opened 2016-10-18 19:37 UTC
Hello,
I was converting the result of Percolator to idXML and got this error:
> (The value 'UniMod:2' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'M' and term specificity 0.

The workflow is MSGFPlusAdapter -> MSGFtoPercolator -> Percolator -> IDFileConverter.
The modification is C-term amidation (UNIMOD 2). 

Starting from the beginning, i realized that MSGFPlus reports the location of C-term amidation one character beyond the sequence length. So if we have XXXX amino acid sequence, the location of modification should be 4 (starting from zero, placing the modification at the end of the sequence) but it’s reported to be 5 which makes MSGFtoPercolator complaining about wrong string position (and it fails). I corrected it by a small script and came to IDFileConverter which fails on C-term amidation. 

I fixed it by adding the following specificity to the unimod.xml but not quite sure if it's a proper thing to do?

`<umod:specificity hidden="0" site="M" position="Any C-term" classification="Artefact"
                           spec_group="8"/>`

Still i cannot open the resulted idXML by TOPPView (the same error as above) but it can be processed in the rest of the workflow. Interesting thing is that if get idXML directly from MSGFPlus (in TOPPAS) it works perfectly. 

Any idea ?

**Comment by PayamEmami** [comment] 2016-10-18 19:47
One more thing i can add to it is that if i open the converted idXML from TOPPAS using "Open files in TOPPView" it can open the file but if i open it from the folder i still get 

> The value 'Amidated' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'M' and term specificity 0.

This is after adding the specificity to unimod.xml

**Comment by cbielow** [comment] 2016-10-19 06:36
not sure I fully understand the problem, but is is possible that you have multiple versions of OpenMS installed? TOPPAS will use the TOPP tools and TOPPView which are in the same(!) directory as the TOPPAS binary itself, i.e. when you invole TOPPView within TOPPAS via "Open in TOPPView".
If you use Explorer, your %PATH% comes into play.. maybe thats the difference (assuming that you open TOPPAS via a shortcut or somehow work around %PATH%)?

**Comment by PayamEmami** [comment] 2016-10-19 07:22
Yes. that's true. In this case, the error occurs in TOPPView 2.1 and not in 2.0.1
But still the same error in IDFileConverter regardless of the version.

**Comment by hendrikweisser** [comment] 2016-10-19 08:46
> Starting from the beginning, i realized that MSGFPlus reports the location of C-term amidation one character beyond the sequence length. So if we have XXXX amino acid sequence, the location of modification should be 4 (starting from zero, placing the modification at the end of the sequence) but it’s reported to be 5 which makes MSGFtoPercolator complaining about wrong string position (and it fails).

For a C-terminal modification, the location "one character beyond the sequence length" (i.e. 5 in your example) should be correct. The mzIdentML standard (https://github.com/HUPO-PSI/mzIdentML/blob/master/schema/mzIdentML1.1.1.xsd) says:
> Modification to the C-terminus should be given as peptide length + 1.

So if MSGFtoPercolator complains about that, it's a problem with the "msgf2pin" tool provided by Percolator (which MSGFtoPercolator wraps). What exactly is the error message there?
If this turns out to be the cause of the problem, we should raise an issue with Percolator (https://github.com/percolator/percolator).

> The value 'UniMod:2' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'M' and term specificity 0.

This indicates that during the conversion we are looking for a non-terminal modification. If you change your Unimod entry to say `position="Anywhere"`, does that make it work?

Can you look into the Percolator output file (.psms) and post a line that has the "UniMod:2" modification in it, please?

**Comment by PayamEmami** [comment] 2016-10-23 20:00
I reported the issue [here ](https://github.com/percolator/percolator/issues/161).
The problem was actually my script but it's worth reporting anyhow.
This peptide will cause an error in ID converter (this is output of my script).
`L.RRKT[UNIMOD:21]LLPKRTACPTKS[UNIMOD:21]SM[UNIMOD:2][UNIMOD:35].E`
but the following peptide works in ID converter (output of Percolator with the change posted [here ](https://github.com/percolator/percolator/issues/161))
`L.RRKT[UNIMOD:21]LLPKRTACPTKS[UNIMOD:21]SM[UNIMOD:35][UNIMOD:2].E`

It's the order of the modification causing the error and it makes sense.

> This indicates that during the conversion we are looking for a non-terminal modification. If you change your Unimod entry to say position="Anywhere", does that make it work?

This also worked.
Anyhow, the modification in Percolator converter will solve the problem.

Thank you,
Payam

**Comment by hendrikweisser** [comment] 2016-10-24 08:24
Thanks for raising the Percolator issue and for reporting back to us, @PayamEmami!

It looks like there's nothing more to do on our side (correct me if I'm wrong), so I'll close this.

**Closed by hendrikweisser** 2016-10-24 08:24 UTC
