### ISSUE TITLE
Empty string in restrictions

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#5875] opened 2022-03-01 14:36 UTC
The parameter `select_activation` in `IsobaricAnalyzer` contains an additional empty value in the restrictions. Probably to render it kind of an optional parameter. Wouldn't it be better to really make it optional? Or is this a general scheme in OpenMS to implement optional parameters (then I could consider this for generating the Galaxy wrappers) 

Empty string is added here:

https://github.com/OpenMS/OpenMS/blob/df159dbe45b4143500715974bc60aa4ab1fd1226/src/openms/source/ANALYSIS/QUANTITATION/IsobaricChannelExtractor.cpp#L169

ctd looks as follows:

```
        <ITEM name="select_activation" value="auto" type="string" description="Operate only on MSn scans where any of its precursors features a certain activation method. Setting to &quot;auto&quot; uses HCD and HCID spectra. Set to empty string if you want to disable filtering." required="false" advanced="false" restrictions="auto,Collision-induced dissociation,Post-source decay,Plasma desorption,Surface-induced dissociation,Blackbody infrared radiative dissociation,Electron capture dissociation,Infrared multiphoton dissociation,Sustained off-resonance irradiation,High-energy collision-induced dissociation,Low-energy collision-induced dissociation,Photodissociation,Electron transfer dissociation,Pulsed q dissociation,trap-type collision-induced dissociation,beam-type collision-induced dissociation,in-source collision-induced dissociation," />
```

**Comment by bernt-matthias** [comment] 2022-03-01 14:47
`x_weight` (e.g. in `MapAlignerTreeGuided`) seems to be another example:

https://github.com/OpenMS/OpenMS/blob/df159dbe45b4143500715974bc60aa4ab1fd1226/src/openms/source/ANALYSIS/MAPMATCHING/TransformationModel.cpp#L191

**Comment by jpfeuffer** [comment] 2022-03-02 13:52
The problem is, that it creates ambiguities between a missing parameter and passing the parameter with the empty string

**Comment by timosachsenberg** [comment] 2022-03-02 16:03
@bernt-matthias can you identify all tools with those restrictions? I can take a look and maybe replace the empty strings in restrictions with something meaningful.

**Comment by timosachsenberg** [comment] 2022-03-02 16:26
I started with a PR here: https://github.com/OpenMS/OpenMS/pull/5886

**Comment by bernt-matthias** [comment] 2022-03-02 16:29
If I `egrep restrictions ctd/ -r | grep ',"'` then I get:

```
ctd/MapAlignerTreeGuided.ctd:            <ITEM name="x_weight" value="" type="string" description="Weight x values" required="false" advanced="false" restrictions="1/x,1/x2,ln(x)," />
ctd/MapAlignerTreeGuided.ctd:            <ITEM name="y_weight" value="" type="string" description="Weight y values" required="false" advanced="false" restrictions="1/y,1/y2,ln(y)," />
ctd/ProteomicsLFQ.ctd:            <ITEM name="x_weight" value="" type="string" description="Weight x values" required="false" advanced="false" restrictions="1/x,1/x2,ln(x)," />
ctd/ProteomicsLFQ.ctd:            <ITEM name="y_weight" value="" type="string" description="Weight y values" required="false" advanced="false" restrictions="1/y,1/y2,ln(y)," />
ctd/MapRTTransformer.ctd:          <ITEM name="x_weight" value="" type="string" description="Weight x values" required="false" advanced="false" restrictions="1/x,1/x2,ln(x)," />
ctd/MapRTTransformer.ctd:          <ITEM name="y_weight" value="" type="string" description="Weight y values" required="false" advanced="false" restrictions="1/y,1/y2,ln(y)," />
ctd/MapAlignerSpectrum.ctd:          <ITEM name="x_weight" value="" type="string" description="Weight x values" required="false" advanced="false" restrictions="1/x,1/x2,ln(x)," />
ctd/MapAlignerSpectrum.ctd:          <ITEM name="y_weight" value="" type="string" description="Weight y values" required="false" advanced="false" restrictions="1/y,1/y2,ln(y)," />
ctd/MapAlignerIdentification.ctd:          <ITEM name="x_weight" value="" type="string" description="Weight x values" required="false" advanced="false" restrictions="1/x,1/x2,ln(x)," />
ctd/MapAlignerIdentification.ctd:          <ITEM name="y_weight" value="" type="string" description="Weight y values" required="false" advanced="false" restrictions="1/y,1/y2,ln(y)," />
ctd/IsobaricAnalyzer.ctd:        <ITEM name="select_activation" value="auto" type="string" description="Operate only on MSn scans where any of its precursors features a certain activation method. Setting to &quot;auto&quot; uses HCD and HCID spectra. Set to empty string if you want to disable filtering." required="false" advanced="false" restrictions="auto,Collision-induced dissociation,Post-source decay,Plasma desorption,Surface-induced dissociation,Blackbody infrared radiative dissociation,Electron capture dissociation,Infrared multiphoton dissociation,Sustained off-resonance irradiation,High-energy collision-induced dissociation,Low-energy collision-induced dissociation,Photodissociation,Electron transfer dissociation,Pulsed q dissociation,trap-type collision-induced dissociation,beam-type collision-induced dissociation,in-source collision-induced dissociation," />
```

**Comment by bernt-matthias** [comment] 2022-03-02 16:30
And `egrep restrictions ctd/ -r | grep '",'` gives one more:

```
ctd/FidoAdapter.ctd:      <ITEM name="accuracy" value="" type="string" description="Accuracy level of start parameters. There is a trade-off between accuracy and runtime. Empty uses the default (&apos;best&apos;)." required="false" advanced="true" restrictions=",best,relaxed,sloppy" />
```

There seems to be no case where an empty string is in the middle of the restriction list.

**Comment by timosachsenberg** [comment] 2022-03-03 12:53
ok should be fixed with https://github.com/OpenMS/OpenMS/pull/5886

**Closed by timosachsenberg** 2022-03-03 12:53 UTC
