### ISSUE TITLE
OpenMS-2.8 not working in WIndows PC

### ISSUE THREAD

**Issue by devenderarora** [OpenMS/OpenMS#5908] opened 2022-03-09 22:02 UTC
Hello Team,

I tried to install the per-release version of openMS and encountered issue with executing GUI tools. I installed 2.7 version and it works fine but gave an attempt to see the update but couldn't get hands-on due to some bug.

Regards
Devender Arora

**Comment by timosachsenberg** [comment] 2022-03-10 09:51
Hi. Thanks for reporting. Do you get an error message that indicates what could be the cause of the error?
Which GUI tool did you execute? Note that OpenMS 2.8 is kind of an unofficial version so there might be some bugs that are eigher already fixed in the nightly builds or we would be happy to fix :)

**Comment by jpfeuffer** [comment] 2022-03-10 09:53
Probably the DLLs are missing like in the KNIME issue

**Comment by timosachsenberg** [comment] 2022-03-10 13:42
I got another report ![image001](https://user-images.githubusercontent.com/5803621/157673879-71540a2a-f698-480b-bb03-110655bbb5c0.png)

**Comment by devenderarora** [comment] 2022-03-10 19:37
I tried TOPPAS, TOPView and got the same zlib.dll issue. I hope you fix the issue and release a updated version soon.

**Comment by timosachsenberg** [comment] 2022-03-16 08:41
I think this might be fixed in our nightly build: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/
can you install https://abibuilder.informatik.uni-tuebingen.de/archive/openms/OpenMSInstaller/nightly/OpenMS-3.0.0-pre-nightly-2022-03-14-Win64.exe and see if this fixes the problem on your computer?

**Comment by enetz** [comment] 2022-05-03 14:42
Tried installing the 2.8 pre-release on an almost fresh Windows 10 instance.
Wwhen starting any tool, I get the same message about missing zlib.dll

Then I uninstalled and tried the latest nightly build (OpenMS-3.0.0-pre-nightly-2022-05-03-Win64)
This works fine, GUI applications included

**Closed** 2022-05-03 14:51 UTC
Labels: BinaryPackages, blocker, Windows
