### ISSUE TITLE
IsotopeDistribution is broken in multiple ways

### ISSUE THREAD

**Issue by hroest** [OpenMS/OpenMS#3781] opened 2018-10-07 02:27 UTC
There seem to be some assumptions that dont make much sense:

https://github.com/OpenMS/OpenMS/blob/118d1a7f0757330bdb632ebf0c6d518268606d0d/src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.cpp#L258-L264

this does not make any sense as the most intense peak may not be the first (and assumes sorting by intensity)

https://github.com/OpenMS/OpenMS/blob/118d1a7f0757330bdb632ebf0c6d518268606d0d/src/openms/source/CHEMISTRY/ISOTOPEDISTRIBUTION/IsotopeDistribution.cpp#L98-L114

this assumes that its sorted by mass if we believe the docu ` /// returns the maximal weight isotope which is stored in the distribution`

The main question is whether we can/should guarantee any sorting since the distribution may be sorted by intensity, by mass or not at all (see also the FineIsotope distribution which comes unsorted by default sorting causes some performance drop).

**Comment by timosachsenberg** [comment] 2018-10-08 11:05
I think it would make sense to guarantee sorting in the IsotopeDistribution. If speed is an issue we can still provide the raw data arrays / vectors in an implementation

**Comment by michalsta** [comment] 2018-10-09 22:07
I think that the issue is more that different parts of code assume different sorting: either by MZ or by intensity. So maybe fixing this discrepancy would be a good opportunity to provide an option to pick the sorting by MZ, by intensity, or none...

**Comment by poshul** [comment] 2023-01-17 14:51
addressed in https://github.com/OpenMS/OpenMS/pull/5956

**Closed as completed by poshul** 2023-01-17 14:51 UTC
Labels: defect
