### ISSUE TITLE
TOPPAS: download of workflows fails unexpectedly

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1572] opened 2015-08-25 14:22 UTC
16:20:47 NOTICE: Downloading file 'http://open-ms.sourceforge.net/wp-content/plugins/forced-download/download.php?path=/wp-content/uploads/2011/10/&file=iTRAQ_Quantation_and_ID.toppas'. You will be notified once the download finished.
# 

16:20:58 NOTICE: File successfully saved to '/Users/timosachsenberg/Downloads/iTRAQ_Quantation_and_ID.toppas'.

But the workflow windows stays empty

**Comment by cbielow** [comment] 2015-08-25 15:35
I can reproduce this on Win7, current develop.

The link seems valid and Chrome will fetch the file.
So the bug seems to be with Qt/OpenMS, not with Wordpress or alike.

**Comment by cbielow** [comment] 2015-09-08 13:17
Looking at the actual error code returned (using PR #1592), it seems that the server unexpectedly closes the connection (error 'Connection closed'; QNetworkReply::RemoteHostClosedError == 2, i.e.	the remote server closed the connection prematurely, before the entire reply was received and processed).

Googling this, one usually finds that the response is no proper HTTP response, but Wget says otherwise:

'''
 wget -S "http://open-ms.sourceforge.net/wp-content/plugins/forced-download/download.php?path=/wp-content/uploads/2011/10/&file=iTRAQ_Quantation_and_ID.t                                                                  oppas"
--2015-09-08 13:16:29--  http://open-ms.sourceforge.net/wp-content/plugins/forced-download/download.php?path=/wp-content/uploads/2011/10/&file=iTRAQ_Quantation_and_ID.topp                                                                  as
Resolving open-ms.sourceforge.net... 216.34.181.96
Connecting to open-ms.sourceforge.net|216.34.181.96|:80... connected.
HTTP request sent, awaiting response...
  HTTP/1.1 200 OK
  Server: Apache/2.2.15 (CentOS)
  Vary: Host
  X-Pingback: http://open-ms.sourceforge.net/xmlrpc.php
  Pragma: public
  Expires: 0
  Cache-Control: must-revalidate, post-check=0, pre-check=0, private
  Content-Disposition: attachment; filename="iTRAQ_Quantation_and_ID.toppas";
  Content-Transfer-Encoding: binary
  Content-Type: application/download
  Content-Length: 350065
  Date: Tue, 08 Sep 2015 11:16:32 GMT
  X-Varnish: 699186010
  Age: 0
  Via: 1.1 varnish
  Connection: keep-alive
Length: 350065 (342K) [application/download]
Saving to: `download.php?path=%2Fwp-content%2Fuploads%2F2011%2F10%2F&file=iTRAQ_Quantation_and_ID.toppas.1'
'''

So I'm a little bit lost right now...

It could be the server/php-script after all, since I know this used to work, and we have not changed the TOPPAS code, but sourceforge might have changed their server config.

**Comment by hendrikweisser** [comment] 2019-04-18 15:34
The title of this issue is giving me a brain aneurysm.

**Closed** 2021-06-16 22:38 UTC
Labels: defect, minor, wontfix
