### ISSUE TITLE
XTandemAdapter bug: reports incorrectly multiple hits

### ISSUE THREAD

**Issue by Stefan-N** [OpenMS/OpenMS#2057] opened 2016-07-18 14:53 UTC
Command line Tandem always reports only a single peptide hit for each MS2 spectrum [1] using for example this standard parameter file. [2]. But the OPENMS adapter tandem reports multiple, identical peptide hits for one spectra as seen in this example, e.g. GDDNTVPR [3]. Those hits are absolutely identical but just written multiple times in the output file as first, second hit. The used OPENMS workflow and the input mzml (converted from Bruker .d raw file) can be found at [4] [5].

[1] `pep.xml` from tandem cmdline (piledriver 2015.04.01): https://gist.github.com/Stefan-N/528c485c73c0b7b195bc0c9130af67eb
[2]`.tandem` parameterfile for cmdline (piledriver 2015.04.01): https://gist.github.com/Stefan-N/c08125295b5664740333705bfe4ac64d
[3] `idXML`  output from OPENMS tandem adapter https://gist.github.com/Stefan-N/6ea68dabf27777f822490be6edf46093
[4]  `.toppas` OPENMS workflow with tandemadapter leading to multiple peptide hit reports https://gist.github.com/Stefan-N/5277b0d841248e326f66da6f5b1d6d75
[5] `.mzML` input file https://fz-juelich.sciebo.de/index.php/s/ougH2RKacRsH5C4

**Comment by lars20070** [comment] 2016-08-05 08:59
So far tested with `Piledriver`. Best to to test/debug with VENGEANCE (2015.12.15) from now on.
See #2093.

**Comment by timosachsenberg** [comment] 2016-08-09 11:31
does this error also occur in VENGEANCE?

**Comment by julianu** [comment] 2016-08-10 08:59
Unfortunately, I have to confirm this bug and could provide more test files, if necessary. Though I only noticed it on relatively "large" searches using big databases for metaproteomics.

**Comment by timosachsenberg** [comment] 2016-08-10 09:18
hi can you some of you run X!Tandem with debug set to 2 or higher and provide the temporary files?
It will output a message like
```
    "Keeping the temporary files at ???? Set debug level to <2 to remove them."
```
to indicate were to find these files.

**Comment by julianu** [comment] 2016-08-11 13:11
Hej @timosachsenberg , are these the files you wanted?

One thing I just spotted (for the peptide CANMFSKNEESTTDTAGK): in the X!Tandem's XML file, this was identified for two spectra. But with two different sets of PTMs each (so together 4 identifications). In the idXML there is only one set of PTMs, C+57 on first position, but these doubled.

[DC_repl1.idXML.zip](https://github.com/OpenMS/OpenMS/files/413241/DC_repl1.idXML.zip)
[DC_repl1.mzML.zip](https://github.com/OpenMS/OpenMS/files/413239/DC_repl1.mzML.zip)
[tmp_tandem.zip](https://github.com/OpenMS/OpenMS/files/413240/tmp_tandem.zip)

**Comment by timosachsenberg** [comment] 2016-08-11 16:27
Ok I am able to reproduce the problem using 
```
IDFileConverter -in _tandem_output_file.2016_08_11_15_00_32.t.xml  -out out.idXML
```
So I guess the problem is located in the XTandemFile parser

**Comment by timosachsenberg** [comment] 2016-08-12 07:00
After parse_ we have both hits for spectrum 1016 and 1068. Let's see where things go wrong now.
````
idx: 836	1	(Glu->pyro-Glu)EADDGGAVAEEC(Carbamidomethyl)SMGADVREDAIEAK
idx: 1016	2	(Carbamidomethyl)CANMFSKNEESTTDTAGK
idx: 1016	2	(Ammonia-loss)CANM(Oxidation)FSKNEESTTDTAGK
idx: 1068	2	(Carbamidomethyl)CANMFSKNEESTTDTAGK
idx: 1068	2	(Ammonia-loss)CANM(Oxidation)FSKNEESTTDTAGK
idx: 1116	1	WNNFDDQGTNGSYTWGK
idx: 1136	1	KAFEM(Oxidation)WQQNDEKTEY
idx: 1139	1	KAFEM(Oxidation)WQQNDEKTEY
idx: 1144	1	TDDGWKSADFADYPNK
idx: 1158	1	SEVDMQIATAK
idx: 1187	1	KAFEM(Oxidation)WQQNDEKTEY
idx: 1676	1	DGREADDESTR
idx: 1801	1	GQSSNLYATM(Oxidation)PYARQD
idx: 1870	1	DPENDLKGAQNGSSNDR
idx: 1934	1	GQSSNLYATM(Oxidation)PYARQD
idx: 1973	1	SLNTGAADWYC(Carbamidomethyl)SFLGR
idx: 2003	1	DPENDLKGAQNGSSNDR
idx: 2014	1	(Acetyl)M(Oxidation)IKLIATDVDGTLVKDGTMQID
idx: 2047	1	DTLDAYAGPGQDGK
idx: 2066	1	GQRHGEMDDSLSDTLR
idx: 2106	1	NADSTNRMAANSR
idx: 2122	1	NKAFTLSYDDGVESDR
idx: 2301	1	(Ammonia-loss)CTSNAKQGDR
idx: 2344	1	(Gln->pyro-Glu)QVPDTSGK
idx: 2377	1	(Ammonia-loss)CTSNAKQGDR
idx: 2378	1	IATISSGGK
idx: 2422	1	(Gln->pyro-Glu)QVPDTSGK
idx: 2441	1	WSSRSYFIC(Carbamidomethyl)DGK
idx: 2450	1	DGREADDESTR
idx: 2457	1	IATISSGGK
idx: 2458	1	M(Oxidation)HSMVDDLR
idx: 2491	1	(Gln->pyro-Glu)QVPDTQGK
```

**Comment by timosachsenberg** [comment] 2016-08-12 07:07
ok think I found the problem... I am preparing a fix

**Comment by timosachsenberg** [comment] 2016-08-12 07:36
Seems the XTandemAdapter tried to be smart and combine peptide hits with the same sequence into single ones. This is imho bad as two different modification states are two distinct hits (and also have different scores). The fix will report multiple hits of a spectrum if they have the same sequence.

**Comment by lars20070** [comment] 2016-08-12 08:16
@Stefan-N Looking at spectrum `1016`, X!Tandem already reports multiple hits for each spectrum.
```
idx: 1016   2   (Carbamidomethyl)CANMFSKNEESTTDTAGK
idx: 1016   2   (Ammonia-loss)CANM(Oxidation)FSKNEESTTDTAGK
```
Not a single hit as reported in your post. So no need to talk to Ron Beavis?

**Comment by timosachsenberg** [comment] 2016-08-12 08:20
I would not jump to this conclusion. Could also mean that hits with the same score are reported.

**Comment by julianu** [comment] 2016-08-12 08:21
@lars20070 Actually that's from my example files, I think.
I guess it is correct to report multiple matches per spectrum. X!Tandem usually does so, if the matches have exactly the same score.

**Comment by lars20070** [comment] 2016-08-12 09:54
Ok. Interesting. Multiple hits only for identical scores. - So for an optimal `ConsensusID` performance we still need more hits from X!Tandem, see #1823. How did you do this in http://doi.org/10.1016/j.jprot.2016.08.002 ?

**Comment by timosachsenberg** [comment] 2016-08-12 12:14
@julianu thanks for the files. do you have information on how to report multiple hits in xtandem?

**Comment by julianu** [comment] 2016-08-12 12:26
Whether this is fully correct or not might be arguable, but I simply handle them as equals. Like the results in any other search engine, like e.g. Mascot, which also reports multiple hits per spectrum, and which also are equal sometimes.
I think in idXML these are represented by different peptideHits in the same peptideIdentification. So, in the ones in my example files, only the modifications of the peptideHits need to be corrected.

**Comment by timosachsenberg** [comment] 2016-08-15 08:56
ok thanks for reporting - I merged the pull request as this seems to be the correct behavior

**Closed** 2016-08-15 10:26 UTC
Labels: critical, defect
