### ISSUE TITLE
PepXML Reader can't read some Comet enzyme names

### ISSUE THREAD

**Issue by Matthias313** [OpenMS/OpenMS#3191] opened 2018-01-23 15:05 UTC
Hi,
I built a very simple workflow 
CometAdapter->PeptideIndexer->FalseDiscoveryRate->MzTabExporter/FileInfo

in the default_params_file which is given to the CometAdapter the enzyme is by default Trypsin (Code "1").
I specified another enzyme in the adapter (used glutamyl endopeptidase) and started the pipeline. Checking the Output the search run with the enzymatic specificity of trypsin, not glutamyl endopeptidase. 

To check if this could be fixed i changed the setting in the default_params_file to GluC = glutamyl endopeptidase (Code "8"). 
This change allowed the search for GluC specific Peptides. 

Is it possible to fix the Adapter so that the enzyme which the user defines in the tool is used rather than the enzyme specified in the default_params_file?

[Comet.txt](https://github.com/OpenMS/OpenMS/files/1656462/Comet.txt)

The toppas workflow saved as txt file

[comet.params.txt](https://github.com/OpenMS/OpenMS/files/1656457/comet.params.txt)

the default_params_file

**Comment by jpfeuffer** [comment] 2018-01-23 15:30
Why do you need the default params file? As specified in the docu, when a params file is given, it will use only that.

**Comment by Matthias313** [comment] 2018-01-23 16:38
load PepXMLFile
 95%Error: Unexpected internal error (the element 'Enzyme name cannot be found. '' could not be found)
Error occurred in line 67 of file C:\jenkins\ws\openms_release_packaging\c2e226b2\source\src\openms\source\CHEMISTRY\EnzymesDB.cpp (in function: const class OpenMS::Enzyme *__cdecl OpenMS::EnzymesDB::getEnzyme(const class OpenMS::String &) const) !

==============================================================================
17:24:12 ERROR: CometAdapter failed!

When using the CometAdapter without a default_params file i get this error. 
In the Adapter one only can select glutamyl endopeptidase whereas in the default in is written GluC with Code "8".

**Comment by jpfeuffer** [comment] 2018-01-23 17:59
Hmm I can't reproduce that error. Can you paste your command or ini file? I want to see how you specify the enzyme. For all adapters we use the same OpenMS nomenclature and translate to the specific nomenclature of the tool. Here "glutamyl endopeptidase" = "Glu_C" = "8".
This should be ok.

**Comment by jpfeuffer** [comment] 2018-01-23 18:38
I have found one bug though.

**Comment by Matthias313** [comment] 2018-01-24 20:04
I changed the file type to txt because .ini is not supported to be uploaded.
This is the ini-file and the TOPPAS.log of the run without a default_params_file.

I hope it helps to find the issue.

[TOPPAS.log](https://github.com/OpenMS/OpenMS/files/1661489/TOPPAS.log)
[CometAdapter.txt](https://github.com/OpenMS/OpenMS/files/1661484/CometAdapter.txt)

**Comment by jpfeuffer** [comment] 2018-02-07 10:29
This should be fixed by the referenced PRs. Please reopen if it persists or open a new issue if something else occurs. Make sure you have a nightly build, we currently do not have an installer.

**Closed by jpfeuffer** 2018-02-07 10:29 UTC
