### ISSUE TITLE
TOPPView: opening a file on windows 10 with space in the file name leads to an error

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#1974] opened 2016-04-26 13:38 UTC
to be confirmed

**Comment by hroest** [comment] 2016-04-27 21:04
FYI: works on Linux

**Comment by timosachsenberg** [comment] 2018-07-18 08:02
hi Leon can you confirm?

**Comment by jpfeuffer** [comment] 2018-07-18 10:47
See also #3598 if someone takes this task. I suspect it to be true tbh.

**Comment by Leon-Bichmann** [comment] 2018-07-18 10:49
Hey ok, I'll have a look tomorrow

**Comment by jpfeuffer** [comment] 2018-07-19 14:59
Could you test?

**Comment by Leon-Bichmann** [comment] 2018-07-19 15:11
Tested with spaces in file and path it works on windows 10.

Currently I dont have a shared drive to test it with, so #3598 is still not clear.

**Comment by jpfeuffer** [comment] 2018-07-19 15:12
Can you test non-ASCII characters, too?

**Comment by Leon-Bichmann** [comment] 2018-07-23 13:52
μ did not work

**Comment by hendrikweisser** [comment] 2019-06-14 13:19
> Tested with spaces in file and path it works on windows 10.

Closing this because the problem couldn't be confirmed.

**Closed by hendrikweisser** 2019-06-14 13:19 UTC
Labels: TOPPView, defect, major
