### ISSUE TITLE
CometAdapter takes too long with more than three modifications

### ISSUE THREAD

**Issue by rolivella** [OpenMS/OpenMS#6200] opened 2022-06-27 09:12 UTC
Hi, I'm working with the `CometAdapter` and I have some issues. When I search a light file with some variable modifications it works fine. But when I use a quite big file (for instance a 2.2GB mzML) and more that three variable modifications the search takes ages and does not finish. I tried the same search without using the CometAdapter, I mean, by running the comet.linux.exe and the search ends in 1h aprox. Do you have any idea on why the CometAdapter is taking so long? 

I've put in a Dropbox folder the files I'm using: https://www.dropbox.com/sh/6vcv951um294qcz/AABWzzg6Jm6KueaPDalTo2hVa?dl=0
* mzML file for testing
* comet.linux.exe
* comet.params.high-low
* shotgun_hela_decoy.fasta

With all this files I send to the cluster (booking 15GB and 1 CPU) and takes 53 minutes. Command: 

`./comet.linux.exe -Pcomet.params.high-low 202206MZ_QC02_001_01_100ng.raw.mzML`

If I send the same job with CometAdapter, it doesn't finish at least in 24 hours. 

Thanks!

**Comment by jpfeuffer** [comment] 2022-06-27 09:27
Hi! Thanks for the detailed report. Do you maybe also have the command line or ini-file for the CometAdapter?

**Comment by rolivella** [comment] 2022-06-27 10:16
Yes, well, I lost it but I think it was something like: 

`CometAdapter -force -in 202206MZ_QC02_001_01_100ng.raw.mzML -out 202206MZ_QC02_001_01_100ng.raw.idXML -database shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable comet.linux.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.5 -fragment_error_units Da -fixed_modifications "Carbamidomethyl (C)" -variable_modifications "'Oxidation (M)' 'Acetyl (N-term)' 'Formyl (N-term)' 'Carbamyl (N-term)' 'Gln->pyro-Glu (N-term Q)' 'Carbamyl (K)' 'Carbamyl (R)' 'Formyl (K)' 'Formyl (S)' 'Formyl (T)'"`

**Comment by jpfeuffer** [comment] 2022-06-27 10:23
Hm I think it would be very important to double-check that if you have time. If you could even provide us with the comet.params file written (and kept in debug mode) by the adapter (it will show you the location in the log), that would be even better.

**Comment by rolivella** [comment] 2022-06-27 10:24
Ok, I'll do it.

**Comment by rolivella** [comment] 2022-06-27 13:07
The closest `CometAdater` command line is: 

`CometAdapter -debug 1 -force -in /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML -database /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /users/pr/qsample/test/comet/comet.linux.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.5 -fragment_error_units Da -fixed_modifications 'Carbamidomethyl (C)' -variable_modifications 'Oxidation (M)' 'Acetyl (N-term)' 'Formyl (N-term)' 'Carbamyl (N-term)' 'Gln->pyro-Glu (N-term Q)' 'Carbamyl (K)' 'Carbamyl (R)' 'Formyl (K)' 'Formyl (S)'`

I say "closest" because if I put all the modifications that are at my `comet.params.high-low` file, in reality are 11 in compact format, but the CometAdapter only supports 9 so I removed the last two: 

`Error: Unexpected internal error (Error: Comet supports at most 9 variable modifications. 11 provided.)`

Where can I find the comet.params file written by the adapter? I put `debug 1` but i can't see it...This is the log: 

```log
Debug level: 1
 >> CometAdapter -debug 1 -force -in /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML -database /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /users/pr/qsample/test/comet/comet.linux.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.5 -fragment_error_units Da -fixed_modifications "Carbamidomethyl (C)" -variable_modifications "Oxidation (M)" "Acetyl (N-term)" "Formyl (N-term)" "Carbamyl (N-term)" "Gln->pyro-Glu (N-term Q)" "Carbamyl (K)" "Carbamyl (R)" "Formyl (K)" "Formyl (S)"
File '/users/pr/qsample/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/users/pr/qsample/.OpenMS/OpenMS.ini' with defaults!
Value of string option 'test': 0
Debug level (after ini file): 1
Value of string option 'no_progress': 0
Value of string option 'comet_executable': /users/pr/qsample/test/comet/comet.linux.exe
File.cpp(72): Creating temporary directory '/scratch/80121255.1.long-sl7/20220627_125910_node-hp0206.linux.crg.es_52327_1/'
Comet is writing the default parameter file...
Value of int option 'ms_level': 2
Value of string option 'in': /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML
XMLHandler.cpp(172): While loading '/users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML': Unhandled attribute 'instrumentConfigurationRef' in 'scan' tag.
Value of string option 'out': /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML
Value of string option 'database': /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta
Value of string option 'default_params_file': 
Value of int option 'threads': 1
<Value of string option 'database': /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta> occurred 2 times
Value of double option 'precursor_mass_tolerance': 7.0
Value of string option 'precursor_error_units': ppm
Value of string option 'isotope_error': off
Value of string option 'enzyme': Trypsin
Value of string option 'second_enzyme': 
Value of string option 'num_enzyme_termini': fully
Value of int option 'missed_cleavages': 1
Value of string option 'variable_modifications': Oxidation (M)
Value of string option 'variable_modifications': Acetyl (N-term)
Value of string option 'variable_modifications': Formyl (N-term)
Value of string option 'variable_modifications': Carbamyl (N-term)
Value of string option 'variable_modifications': Gln->pyro-Glu (N-term Q)
Value of string option 'variable_modifications': Carbamyl (K)
Value of string option 'variable_modifications': Carbamyl (R)
Value of string option 'variable_modifications': Formyl (K)
Value of string option 'variable_modifications': Formyl (S)
Value of int option 'max_variable_mods_in_peptide': 5
Value of string option 'require_variable_mod': false
<Value of int option 'max_variable_mods_in_peptide': 5> occurred 2 times
Value of string option 'instrument': high_res
Value of double option 'fragment_mass_tolerance': 0.5
Value of double option 'fragment_bin_offset': 0.0
Fragment bin size (== 2x 'fragment_mass_tolerance') or offset is quite high for high-res instruments (Comet recommends 0.02 Da bin size & 0.0 Da offset). Current value: fragment bin size = 1(=2x0.5) and offset = 0. Use the '-force' flag to continue anyway.
Value of string option 'force': 1
You used the '-force'!
Value of string option 'use_A_ions': false
Value of string option 'use_B_ions': true
Value of string option 'use_C_ions': false
Value of string option 'use_X_ions': false
Value of string option 'use_Y_ions': true
Value of string option 'use_Z_ions': false
Value of string option 'use_NL_ions': false
Value of string option 'pin_out': 
Value of int option 'num_hits': 1
Value of string option 'precursor_charge': 2:5
Value of string option 'override_charge': keep known search unknown
Value of int option 'ms_level': 2
Value of string option 'activation_method': ALL
Value of string option 'digest_mass_range': 600:5000
Value of int option 'max_fragment_charge': 3
Value of int option 'max_precursor_charge': 5
Value of string option 'clip_nterm_methionine': false
Value of int option 'min_peptide_length': 5
Value of int option 'max_peptide_length': 63
Value of int option 'spectrum_batch_size': 20000
Value of string option 'mass_offsets': 0.0
Value of string option 'clear_mz_range': 0:0
Value of int option 'minimum_peaks': 10
Value of double option 'minimum_intensity': 0.0
Value of string option 'remove_precursor_peak': no
Value of double option 'remove_precursor_tolerance': 1.5
Value of string option 'fixed_modifications': Carbamidomethyl (C)
```

**Comment by jpfeuffer** [comment] 2022-06-27 15:49
It should tell you when it starts the search. E.g. Calling command is: "comet.exe ...."

**Comment by jpfeuffer** [comment] 2022-06-27 15:50
Why is the adapter restricted? Was there a change in comet to support more than 9 mods? Or was it just lazily implemented

**Comment by jpfeuffer** [comment] 2022-06-27 15:54
Also note this warning:
`Fragment bin size (== 2x 'fragment_mass_tolerance') or offset is quite high for high-res instruments (Comet recommends 0.02 Da bin size & 0.0 Da offset). Current value: fragment bin size = 1(=2x0.5) and offset = 0. Use the '-force' flag to continue anyway`

This already makes me suspicious. Note 
that fragment tolerance is not the same as fragment bin tolerance. You need to double it to be compatible with our unified search engine interface.

**Comment by rolivella** [comment] 2022-06-28 08:21
I sent a job with a new command: 

`CometAdapter -debug 10 -force -in /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML -database /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /users/pr/qsample/test/comet/comet.linux.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.02 -fragment_error_units Da -fixed_modifications 'Carbamidomethyl (C)' -variable_modifications 'Oxidation (M)' 'Acetyl (N-term)' 'Formyl (N-term)' 'Carbamyl (N-term)' 'Gln->pyro-Glu (N-term Q)' 'Carbamyl (K)' 'Carbamyl (R)' 'Formyl (K)' 'Formyl (S)'`

Now I put `-debug 10` and `fragment_mass_tolerance 0.02`. It created a file `comet.params.new` at, I think, this folder at our cluster `'/scratch/80125175.1.long-sl7/20220628_075537_node-hp0303.linux.crg.es_41186_1/'` but it doesn't exist...

At the moment the job is running without the warning you mentioned. Here the log until now: 

```log
Debug level: 10
 >> CometAdapter -debug 10 -force -in /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML -database /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /users/pr/qsample/test/comet/comet.linux.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.02 -fragment_error_units Da -fixed_modifications "Carbamidomethyl (C)" -variable_modifications "Oxidation (M)" "Acetyl (N-term)" "Formyl (N-term)" "Carbamyl (N-term)" "Gln->pyro-Glu (N-term Q)" "Carbamyl (K)" "Carbamyl (R)" "Formyl (K)" "Formyl (S)"
File '/users/pr/qsample/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/users/pr/qsample/.OpenMS/OpenMS.ini' with defaults!
Value of string option 'test': 0
Debug level (after ini file): 10
Value of string option 'no_progress': 0
Value of string option 'comet_executable': /users/pr/qsample/test/comet/comet.linux.exe
Input file resolved to '/users/pr/qsample/test/comet/comet.linux.exe'
Checking input file '/users/pr/qsample/test/comet/comet.linux.exe'
File.cpp(72): Creating temporary directory '/scratch/80125175.1.long-sl7/20220628_075537_node-hp0303.linux.crg.es_41186_1/'
Comet is writing the default parameter file...
Running: /users/pr/qsample/test/comet/comet.linux.exe -p

 Created:  comet.params.new

Executed '/users/pr/qsample/test/comet/comet.linux.exe' successfully!
Comet Version extracted is: '# comet_version 2021.02 rev. 0 (3c62af2)

Value of int option 'ms_level': 2
Value of string option 'in': /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML
Checking input file '/users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML'
XMLHandler.cpp(172): While loading '/users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.mzML': Unhandled attribute 'instrumentConfigurationRef' in 'scan' tag.
Value of string option 'out': /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML
Checking output file '/users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML'
Value of string option 'database': /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta
Value of string option 'default_params_file': 
Value of int option 'threads': 1
<Value of string option 'database': /users/pr/qsample/test/comet/shotgun_hela_decoy.fasta> occurred 2 times
Value of double option 'precursor_mass_tolerance': 7.0
Value of string option 'precursor_error_units': ppm
Value of string option 'isotope_error': off
Value of string option 'enzyme': Trypsin
Value of string option 'second_enzyme': 
Value of string option 'num_enzyme_termini': fully
Value of int option 'missed_cleavages': 1
Value of string option 'variable_modifications': Oxidation (M)
Value of string option 'variable_modifications': Acetyl (N-term)
Value of string option 'variable_modifications': Formyl (N-term)
Value of string option 'variable_modifications': Carbamyl (N-term)
Value of string option 'variable_modifications': Gln->pyro-Glu (N-term Q)
Value of string option 'variable_modifications': Carbamyl (K)
Value of string option 'variable_modifications': Carbamyl (R)
Value of string option 'variable_modifications': Formyl (K)
Value of string option 'variable_modifications': Formyl (S)
Value of int option 'max_variable_mods_in_peptide': 5
Value of string option 'require_variable_mod': false
<Value of int option 'max_variable_mods_in_peptide': 5> occurred 2 times
Value of string option 'instrument': high_res
Value of double option 'fragment_mass_tolerance': 0.02
Value of double option 'fragment_bin_offset': 0.0
Value of string option 'use_A_ions': false
Value of string option 'use_B_ions': true
Value of string option 'use_C_ions': false
Value of string option 'use_X_ions': false
Value of string option 'use_Y_ions': true
Value of string option 'use_Z_ions': false
Value of string option 'use_NL_ions': false
Value of string option 'pin_out': 
Value of int option 'num_hits': 1
Value of string option 'precursor_charge': 2:5
Value of string option 'override_charge': keep known search unknown
Value of int option 'ms_level': 2
Value of string option 'activation_method': ALL
Value of string option 'digest_mass_range': 600:5000
Value of int option 'max_fragment_charge': 3
Value of int option 'max_precursor_charge': 5
Value of string option 'clip_nterm_methionine': false
Value of int option 'min_peptide_length': 5
Value of int option 'max_peptide_length': 63
Value of int option 'spectrum_batch_size': 20000
Value of string option 'mass_offsets': 0.0
Value of string option 'clear_mz_range': 0:0
Value of int option 'minimum_peaks': 10
Value of double option 'minimum_intensity': 0.0
Value of string option 'remove_precursor_peak': no
Value of double option 'remove_precursor_tolerance': 1.5
Value of string option 'fixed_modifications': Carbamidomethyl (C)
```
```

**Comment by jpfeuffer** [comment] 2022-06-28 08:45
Regarding the number of modifications:
```
#
# Up to 9 variable modifications are supported
# format:  <mass> <residues> <0=variable/else binary> <max_mods_per_peptide> <term_distance> <n/c-term> <required> <neutral_loss>
#     e.g. 79.966331 STY 0 3 -1 0 0 97.976896
#
```

This is in your param file. One would need to double-check if this is indeed still a limitation of comet. I guess it is. 9 modifications are a lot. Did you try an open search with e.g. MSFragger?

Regarding your output:
The log is not long enough to see where the param file will be written in the end. Can you upload the full log?

**Comment by jpfeuffer** [comment] 2022-06-28 09:44
I am just wondering if Comet actually takes all those modifications when it has this comment in the param file. Maybe it silently ignores the other mods?

**Comment by rolivella** [comment] 2022-06-28 09:57
I think is a matter of notation. For instance: 

`variable_mod06 = 28.0101 STK 1`

Are three modifications in one sentence `Formyl (S)`, `Formyl (T)`, `Formyl (K)`. So, in the Comet notation, there are 8 "variable_modX" entries but in the CometAdapter notation, 11.

**Comment by cbielow** [comment] 2022-06-28 10:03
I'm currently trying to reproduce the issue...

**Comment by jpfeuffer** [comment] 2022-06-28 10:17
Hmm if it does not even show the start of the real Comet search, it has problems with the preprocessing (probably the indexing or whatever else it is doing).

**Comment by cbielow** [comment] 2022-06-28 14:04
I ran you data using the above commandline
```
CometAdapter -debug 10 -force -in /buffer/ag_bsc/tmp/OpenMS_comet/202206MZ_QC02_001_01_100ng.raw.mzML -out 202206MZ_QC02_001_01_100ng.raw.idXML -database /buffer/ag_bsc/tmp/OpenMS_comet/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /buffer/ag_bsc/tmp/OpenMS_comet/comet.linux.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.02 -fragment_error_units Da -fixed_modifications "Carbamidomethyl (C)" -variable_modifications "Oxidation (M)" "Acetyl (N-term)" "Formyl (N-term)" "Carbamyl (N-term)" "Gln->pyro-Glu (N-term Q)" "Carbamyl (K)" "Carbamyl (R)" "Formyl (K)" "Formyl (S)"
```

on both Windows and Linux.
On both platforms, the comet executable starts up almost instantly (even though on Linux the CometAdapter does not immediately report that fact on the commandline due to not flushing a cout buffer -- but thats a minor thing).
Comet itself makes progress. I confirmed this by killing the comet process (not the CometAdapter!), which make the CometAdapter realize that the child process died, and it will print the console output of comet it received so far... this is looking good.
I did not finish any of the computations, since they burned about 9 CPU hours and reached 7% completion.
However, when searching with only 2 var-mods, the search finished on both platforms successfully.

So, I don't know what the problem may be to be honest.
Could you please check that `comet.linux.exe` is running on the node. If yes, you can try to kill it, which will print more information in the CometAdapter output.
For all I know so far, it just needs more time :)

Speculation: since we seem to write modifications one by one (if I read the above correctly), maybe Comet cannot apply some optimization in its search scheme, and thats why it simply takes longer?

**Comment by timosachsenberg** [comment] 2022-06-29 08:22
related to https://github.com/OpenMS/OpenMS/issues/6203

**Comment by rolivella** [comment] 2022-06-29 08:56
I have the results for [this test](https://github.com/OpenMS/OpenMS/issues/6200#issuecomment-1168547222): 

* Running `comet.linux.exe` this job took almost 4h.
* Running `CometAdapter` took almost 12h. 

Maybe @cbielow your speculation is true. If the mapping between the CometAdapter notation and the "native" Comet format is optimized, probably the running time is going to decrease. AFAIK is what @timosachsenberg is trying to elucidate in this new related issue.

**Comment by cbielow** [comment] 2022-06-29 13:52
good news/bad news:
I just confirmed by suspicion:
`slow` config:
```
variable_mod06 = 43.0058 K 0 5 -1 0 0 0.0
variable_mod07 = 43.0058 R 0 5 -1 0 0 0.0
variable_mod08 = 27.9949 K 0 5 -1 0 0 0.0
variable_mod09 = 27.9949 S 0 5 -1 0 0 0.0
```

vs. `fast` config:
```
variable_mod04 = 43.0058 n 0 5 0 2 0 0.0
variable_mod06 = 43.0058 KR 0 5 -1 0 0 0.0
variable_mod08 = 27.9949 KS 0 5 -1 0 0 0.0
```

One the same dataset etc, the speed difference is 83min vs. 25min, i.e. a more than 3x fold speedup.
Also worth noting: The resulting output is identical.

**Comment by cbielow** [comment] 2022-06-29 13:54
I will forward this to the comet devs. We can certainly fix that (for speedup of existing comet versions), but ideally, its fixed upstream, so that downstream tools don't have to reinvent the wheel.

**Comment by cbielow** [comment] 2022-07-01 19:25
Posted it on the Comet mailing list. Jimmy came along and fixed in within hours! Just WOW :)
The next Comet release will contain the fix.
https://groups.google.com/g/comet-ms/c/b6vwQnU-Qvk/m/dTZZ90TpAwAJ?utm_medium=email&utm_source=footer

We should still fix it on our end, just to make older Comets happy.

**Closed by cbielow** 2022-07-01 19:25 UTC

**Comment by rolivella** [comment] 2022-07-04 07:46
So @cbielow , I understand that if I put the new Comet and the same CometAdapter is going to work? I mean, process the files with the same speed?

**Comment by cbielow** [comment] 2022-07-04 07:56
Yes, once the new Comet release is out, Comet will internally merge the modifications and thus be faster, even with an older CometAdapter.

**Comment by rolivella** [comment] 2022-07-25 07:42
Just a follow-up because I've seen that there's not any new Comet realease yet since May. Where did you contact Comet developers? I would ask if there's any new version planned soon. Thanks!

**Comment by cbielow** [comment] 2022-07-25 08:16
I used their google group.
See https://groups.google.com/g/comet-ms/c/b6vwQnU-Qvk

**Comment by rolivella** [comment] 2022-09-15 08:38
Hi again, last Tuesday I met @timosachsenberg at Barcelona and we discussed about this issue. Timo told me to make a test with the new Comet release with the changes that @cbielow suggested to the Comet devs. I did the test with the CometAdapter I'm using (Version: 2.6.0-pre-develop-2021-04-29 Apr 30 2021, 06:30:26, Revision: 5fe7aec) with six variable modifications running at our cluster with 5 cpus and took 4h aprox. So I understand that I've still have to wait for the resolution of this issue -> https://github.com/OpenMS/OpenMS/issues/6203? Thanks!

**Comment by cbielow** [comment] 2022-09-16 04:44
The new Comet is sufficient to achieve better runtime. At least in theory.

**Comment by rolivella** [comment] 2022-09-16 07:19
And "New Comet" + "Old CometAdapter" should also work?

**Comment by cbielow** [comment] 2022-09-16 11:33
Yes!

**Comment by rolivella** [comment] 2022-09-27 09:34
Hi again, sorry for bother you again but I still have the same issue I posted at the beginning. What I did now: 

1) Compare the time that takes a new and old version of Comet to process a complex sample of HeLa. 
2) Compare the time that takes a new and old version of Comet to process a complex sample of HeLa using the CometAdapter. 

with quite a lot of variable modifications that we use to analyze Histones PTMs.  

Here a table with a summary of the results: 

| Comet engine version        | Is using CometAdapter?            | Time (min)  |
| ------------- |:-------------:| -----:|
|  2021.02.0     | No| 63 |
| 2022.01.2    | No     |   45 |
|  2021.02.0     | Yes| Killed job after 12h |
| 2022.01.2    | Yes      |   Killed job after 12h  |

So in conclusion, when not using the CometAdapter the Search is quite fast, but when using the CometAdapter it takes ages to finish (if it really finishes...). 

Here the files I used to do the test: https://www.dropbox.com/scl/fo/yaiuu72y0fg4dd2zr27bn/h?dl=0&rlkey=6v7j66csyc70t4f0karyc0ao1

And the command lines: 

### Without CometAdapter: 

old engine: 
` /users/pr/qsample/test/comet/bin/./comet.linux.2021.02.0.exe -P/users/pr/qsample/test/comet/sec_react/comet.params.2021.02.0 /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML` --> 63 min

new: 
`/users/pr/qsample/test/comet/bin/./comet.linux.2022.01.2.exe -P/users/pr/qsample/test/comet/sec_react/comet.params.2022.01.2 /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML` --> 45 min

### With CometAdapter: 

old: 
`CometAdapter -debug 10 -threads 5 -force -in /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.idXML -database /users/pr/qsample/test/comet/sec_react/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /users/pr/qsample/test/comet/bin/comet.linux.2021.02.0.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.02 -fragment_error_units Da -fixed_modifications 'Carbamidomethyl (C)' -variable_modifications 'Oxidation (M)' 'Acetyl (N-term)' 'Phenylisocyanate (N-term)' 'Propionyl (K)' 'Propionyl (Protein N-term)' 'Dimethyl (K)' 'Trimethyl (K)' 'Acetyl (K)' 'Crotonaldehyde (K)'` 

new:
`CometAdapter -debug 10 -threads 5 -force -in /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.idXML -database /users/pr/qsample/test/comet/sec_react/shotgun_hela_decoy.fasta -precursor_charge 2:5 -comet_executable /users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe -precursor_mass_tolerance 7 -precursor_error_units ppm -fragment_mass_tolerance 0.02 -fragment_error_units Da -fixed_modifications 'Carbamidomethyl (C)' -variable_modifications 'Oxidation (M)' 'Acetyl (N-term)' 'Phenylisocyanate (N-term)' 'Propionyl (K)' 'Propionyl (Protein N-term)' 'Dimethyl (K)' 'Trimethyl (K)' 'Acetyl (K)' 'Crotonaldehyde (K)'`

**Comment by jpfeuffer** [comment] 2022-09-27 09:41
Hi! Sorry that it still persists. Can you additionally upload the param files created by the adapter?

**Comment by rolivella** [comment] 2022-09-27 09:45
Do you mean the default param file? Because I don't know how to get the param file that is really using internally the CometAdapter...

**Comment by jpfeuffer** [comment] 2022-09-27 10:33
Where did you get the `[^` nomenclature from? I cannot find it in the documentation

**Comment by jpfeuffer** [comment] 2022-09-27 10:39
The params that the adapter produces, are here: https://gist.github.com/jpfeuffer/aff8d35c9321a1798c55ab704d71c981
Can you run it on your computer to see how long it takes?
Many things are different, including obvious things like precursor tolerance so it is clear that it will not be comparable.

**Comment by rolivella** [comment] 2022-09-27 10:42
I see...maybe I mixed different notations with a test I did with the MSFragger because the param file is quite similar. Let me check it and I let you know. 

How can you get this parameter file? So I will do this comparisions for myself without bothering you. 

And yes, the precursor tolerance is different but for the CometAdapter it should be faster that the config without CometAdapter.

**Comment by jpfeuffer** [comment] 2022-09-27 10:45
With the `-debug 10` option that you are passing already, the adapter prints the following lines:
```
File.cpp(74): Creating temporary directory '/tmp/20220927_102405_openms-openms-5msc66m4tau_15769_1/'
TOPPBase.cpp(1605): Comet is writing the default parameter file...
```

You can then navigate to the tmp directory and look at param.txt.

> And yes, the precursor tolerance is different but for the CometAdapter it should be faster that the config without CometAdapter.

True. This is probably not the issue.

**Comment by rolivella** [comment] 2022-09-28 09:12
Hello, so the search is still running in our cluster (20h till now), I don't know if it's really doing something...

Param file: 

[comet.params.cometadapter.2022.01.2.zip](https://github.com/OpenMS/OpenMS/files/9663356/comet.params.cometadapter.2022.01.2.zip)


The log: 

```
[qsample@nextflow2 f14ae3e03f89c798a14bb80dea246c]$ cat .command.log
Debug level: 10
 >> CometAdapter -debug 10 -threads 5 -force -database /users/pr/qsample/test/comet/sec_react/shotgun_hela_decoy.fasta -in /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML -out /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML -default_params_file /users/pr/qsample/test/comet/sec_react/comet.params.cometadapter.2022.01.2 -comet_executable /users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe
File '/users/pr/qsample/.OpenMS/OpenMS.ini' is deprecated.
Updating missing/wrong entries in '/users/pr/qsample/.OpenMS/OpenMS.ini' with defaults!
Value of string option 'test': 0
Debug level (after ini file): 10
Value of string option 'no_progress': 0
Value of string option 'comet_executable': /users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe
Input file resolved to '/users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe'
Checking input file '/users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe'
File.cpp(72): Creating temporary directory '/scratch/80715710.1.pr-fenn-el7/20220927_120957_fenn.linux.crg.es_1370_1/'
Comet is writing the default parameter file...
Running: /users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe -p

 Created:  comet.params.new

Executed '/users/pr/qsample/test/comet/bin/comet.linux.2022.01.2.exe' successfully!
Comet Version extracted is: '# comet_version 2022.01 rev. 2 (f447eed)

Value of int option 'ms_level': 2
Value of string option 'in': /users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML
Checking input file '/users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML'
XMLHandler.cpp(172): While loading '/users/pr/qsample/test/comet/sec_react/202206MZ_QC02_001_01_100ng.raw.mzML': Unhandled attribute 'instrumentConfigurationRef' in 'scan' tag.
Value of string option 'out': /users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML
Checking output file '/users/pr/qsample/test/comet/202206MZ_QC02_001_01_100ng.raw.idXML'
Value of string option 'database': /users/pr/qsample/test/comet/sec_react/shotgun_hela_decoy.fasta
Value of string option 'default_params_file': /users/pr/qsample/test/comet/sec_react/comet.params.cometadapter.2022.01.2
Warning: Could not determine format of input file '/users/pr/qsample/test/comet/sec_react/comet.params.cometadapter.2022.01.2'!
```

**Comment by jpfeuffer** [comment] 2022-09-28 09:28
Ok! And the pure command with comet.exe? Still finishes in 40 mins?

**Comment by jpfeuffer** [comment] 2022-09-28 09:32
Great. I just tested 10 mins and it was still at 0%, so it might be that it finally picks up all your modifications and just takes a long time. Your log indicates that Comet is still running (to be sure you would need to "top" on your cluster node if possible)

**Comment by rolivella** [comment] 2022-09-28 09:43
Ok, so I sent the Comet without adapter an new params and I can confirm that the process is running at our cluster after make a `top`

**Comment by rolivella** [comment] 2022-09-29 09:44
@jpfeuffer after monitoring the searches I sent yesterday I think that we can conclude that with this new parameters file there's no significant difference between Comet alone and with CometAdapter. Both take more ore less 10h to finish, which I think is still too much. But at less we can now assure that internally the var. modif. are being managed properly. 👍  

Do you think that this processing time could be decreased with a `spectrum_batch_size = 5000` as we are using with MascotAdapterOnline? (for the same search takes less than 2h....)
