### ISSUE TITLE
building pyOpenMS with python3 fails

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#4229] opened 2019-08-29 11:33 UTC
Builds fail if I want to switch to py3. Are there any additional configuration steps necessary or is this a new issue to 2.4.0?
Consider some dockerfile like:
```
FROM openms/library

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /openms-build

RUN apt-get update -y 
RUN apt-get install -y python3 python3-pip \
				python3-dev \
				python3-numpy
RUN pip3 install nose
RUN pip3 install -U setuptools
RUN pip3 install Cython
RUN pip3 install autowrap
RUN pip3 install wheel

RUN cmake  -DOPENMS_CONTRIB_LIBS="/contrib-build" -DCMAKE_PREFIX_PATH="/usr/;/usr/local" -DBOOST_USE_STATIC=OFF -DHAS_XSERVER=Off -DWITH_GUI=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DPYOPENMS=On -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 /OpenMS

RUN make pyopenms
```
Is there maybe some incompatibility with the cmake instructions? Maybe @hroest knows?
The error (actually, myriads like it) is 
```
created pyopenms.cpp

Error compiling Cython file:
------------------------------------------------------------
...
    
    def _hasElement_0(self,  name ):
        """Cython signature: bool hasElement(const String & name)"""
        assert (isinstance(name, str) or isinstance(name, unicode) or isinstance(name, bytes) or isinstance(name, String)), 'arg name wrong type'
    
        cdef bool _r = self.inst.get().hasElement(deref((convString(name)).get()))
                                                 ^
------------------------------------------------------------

pyopenms/pyopenms_8.pyx:9297:50: Invalid operand type for '*' (Python object)

Error compiling Cython file:
------------------------------------------------------------
...
    def hasElement(self, *args ):
        """
          - Cython signature: bool hasElement(const String & name)
          - Cython signature: bool hasElement(unsigned int atomic_number)
"""
        if (len(args)==1) and ((isinstance(args[0], str) or isinstance(args[0], unicode) or isinstance(args[0], bytes) or isinstance(args[0], String))):
                                                                                                                                             ^
------------------------------------------------------------

pyopenms/pyopenms_8.pyx:9314:142: 'String' is not a constant, variable or function identifier
```

**Comment by hroest** [comment] 2019-08-29 15:05
which Python and Cython version is this?

**Comment by mwalzer** [comment] 2019-08-29 16:28
It's using the xenial repos, so it is 
```
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
>>> import Cython
>>> Cython.__version__
'0.29.13'
```

**Comment by mwalzer** [comment] 2019-09-05 10:53
Just tried it with Ubuntu 18.04, no luck there either.

**Comment by jpfeuffer** [comment] 2019-09-22 16:29
Are there any updates?
@hroest On which setup does it work for you?
I will try to switch our builds gradually to python 3. What Ubuntu version should I use and which Visual Studio is suggested/needed on Windows?

**Comment by oliveralka** [comment] 2019-10-01 19:15
@hroest: 
The issue seems to be somewhat unrelated to python 3, since I have build it successfully a few months ago with python 3.7. 
I am currently testing with Ubuntu 19.04, python 3.7, cython 0.29.13. 

There seem to be errors during cython / compile:

I am not quite sure how to fix this ... (ideas would be welcome ;))

I added an example for an error, but seems like a lot of similar ones occur (see error log).

```
Error compiling Cython file:
------------------------------------------------------------
...

# this class has addons, see the ./addons folder

cdef extern from "<OpenMS/KERNEL/MSExperiment.h>" namespace "OpenMS":

    cdef cppclass MSExperiment(ExperimentalSettings, RangeManager2):
        ^
------------------------------------------------------------

/home/pancake/software/OpenMS/src/pyOpenMS/pxds/MSExperiment.pxd:16:9: Cannot inherit from incomplete type

Error compiling Cython file:
------------------------------------------------------------
...
        #     for spectrum in exp:
        #       print(spectrum.size()) # prints number of peaks
        #       mz, intensities = spectrum.get_peaks()
        #   -----

        MSExperiment() nogil except +
       ^
------------------------------------------------------------
```

I added an error log (which is basically the stderr of the build process without warnings)
[pyopenms_build_errorlog.txt](https://github.com/OpenMS/OpenMS/files/3678108/pyopenms_build_errorlog.txt)

**Comment by hroest** [comment] 2019-10-02 14:20
I am currently looking into this, can you try again now that this PR is merged: https://github.com/OpenMS/OpenMS/pull/4279

**Comment by oliveralka** [comment] 2019-10-02 14:25
I will try it later, with the newest develop.

**Comment by hroest** [comment] 2019-10-02 17:39
Hi Oliver, I am just trying this:

https://github.com/OpenMS/OpenMS/wiki/pyOpenMS#test

it seems to work when merging the Epifany fix for compiling with gcc 4.8 plus a patch that I had to add ... so not great yet but it compiles

**Comment by oliveralka** [comment] 2019-10-02 17:39
It seems there are other errors occuring during compiling the Cython file.

Example:

```
Error compiling Cython file:
------------------------------------------------------------
...
from XTandemXMLFile cimport XTandemXMLFile as _XTandemXMLFile
from InterfaceDataStructures cimport BinaryDataArray as _BinaryDataArray
from InterfaceDataStructures cimport Chromatogram as _Chromatogram
from InterfaceDataStructures cimport Spectrum as _Spectrum
from streampos cimport streampos as _streampos
from pyopenms_2 cimport FeatureFindingMetabo
^
------------------------------------------------------------

pyopenms/pyopenms_1.pxd:884:0: 'pyopenms_2.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from XTandemXMLFile cimport XTandemXMLFile as _XTandemXMLFile
from InterfaceDataStructures cimport BinaryDataArray as _BinaryDataArray
from InterfaceDataStructures cimport Chromatogram as _Chromatogram
from InterfaceDataStructures cimport Spectrum as _Spectrum
from streampos cimport streampos as _streampos
from pyopenms_2 cimport FeatureFindingMetabo
^
------------------------------------------------------------

pyopenms/pyopenms_1.pxd:884:0: 'pyopenms_2/FeatureFindingMetabo.pxd' not found
```

It seems to try to reference to a file, which is build at a later time point. 
This happens with 
pyopenms_1 to pyopenms_2
pyopenms_1 to pyopenms_3
pyopenms_1 to pyopenms_4

Afterwards it is having problems with the type identifiers:
`pyopenms/pyopenms_1.pyx:193:26: 'Feature' is not a type identifier`

**Comment by hroest** [comment] 2019-10-02 17:40
So basically what worked was:
```
hr@hr-Precision-5520:~/projects/docker/hroest_docker/openms/pyopenms$ sudo docker build --build-arg branch=fix/gcc48 --build-arg repo=hroest/OpenMS .
[...]
20/25 Test #23: pyopenms_unittest_test_MzXMLConsumer.py ....................   Passed    0.75 sec
21/25 Test #22: pyopenms_unittest_test_MzMLConsumer.py .....................   Passed    1.68 sec
22/25 Test #24: pyopenms_integrationtest_test_MRMRTNormalizer.py ...........   Passed    2.68 sec
23/25 Test #19: pyopenms_unittest_test_SpectraFilter.py ....................   Passed   13.43 sec
24/25 Test  #1: test_pyopenms_unittests ....................................   Passed   26.01 sec
25/25 Test #25: pyopenms_test_memoryleaktests ..............................   Passed   57.67 sec

100% tests passed, 0 tests failed out of 25

Total Test time (real) =  68.90 sec
Removing intermediate container 2b4c36119156
 ---> e432b5ae298c
Successfully built e432b5ae298c

```

so pyOpenMS builds and runs (on Python 2). On my machine it also rusn with Python 3

**Comment by hroest** [comment] 2019-10-02 17:41
> It seems there are other errors occuring during compiling the Cython file.

there is an issue in autowrap 19.0.1 that I found yesterday, can you try 

```
pip install autowrap==0.19.0
```

**Comment by hroest** [comment] 2019-10-02 17:43
@mwalzer @oliveralka is it possible the error is there since Mid-August? That is when 19.1 was relased which leads to the failure above: https://pypi.org/project/autowrap/#history

**Comment by oliveralka** [comment] 2019-10-02 17:43
Ok, thanks Hannes! 
I will try that as well!

**Comment by oliveralka** [comment] 2019-10-02 18:41
@hroest

> there is an issue in autowrap 19.0.1 that I found yesterday, can you try
> 
> ```
> pip install autowrap==0.19.0
> ```

It seems you have been right with the autowrap in terms of the Cython process! 
Everything build successfully! 

But I have encountered a problem with the whl after installing and import of pyopenms.

```
 (py37) pancake@pancake:~/software/pyopenms_build/pyOpenMS/dist$ python -c "import pyopenms"

======================================================================
Error when loading pyOpenMS libraries!
Libraries could not be found / could not be loaded.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pancake/miniconda3/envs/py37/lib/python3.7/site-packages/pyopenms/__init__.py", line 82, in <module>
    raise e
  File "/home/pancake/miniconda3/envs/py37/lib/python3.7/site-packages/pyopenms/__init__.py", line 45, in <module>
    from .all_modules import *
  File "/home/pancake/miniconda3/envs/py37/lib/python3.7/site-packages/pyopenms/all_modules.py", line 1, in <module>
    from .pyopenms_1 import *
ImportError: /home/pancake/miniconda3/envs/py37/lib/python3.7/site-packages/pyopenms/pyopenms_1.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost13match_resultsIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEESaINS_9sub_matchISB_EEEE12maybe_assignERKSF_
```
I will look further into it.

**Comment by poshul** [comment] 2019-10-04 11:28
> @mwalzer @oliveralka is it possible the error is there since Mid-August? That is when 19.1 was relased which leads to the failure above: https://pypi.org/project/autowrap/#history

Looking at the PyOpenMS work that I did over the dev retreat in April, it looks like this has been an issue at least that far back.

**Comment by timosachsenberg** [comment] 2019-10-23 11:12
@hroest I can confirm that autowrap==0.19.0 builds but 0.19.1 fails on my ubuntu

**Comment by hroest** [comment] 2019-10-23 16:13
> @hroest I can confirm that autowrap==0.19.0 builds but 0.19.1 fails on my ubuntu

yes, I can confirm that

**Comment by mwalzer** [comment] 2019-10-25 14:38
I can confirm the apparent cause is the autowrap version update from  0.19.0 to 0.19.1
```python
RUN pip3 install autowrap==0.19.0
```
somewhat fixes that. @hroest did you open an issue for autowrap 0.19.1 incompatibility yet somewhere?

**Comment by poshul** [comment] 2019-10-28 19:34
I've spent some time bisecting and the bug was introduced in https://github.com/uweschmitt/autowrap/commit/ecb647176a33bcee198dea91469a8f6e8360008e I'm working on figuring out what in that commit causes it.

**Comment by hroest** [comment] 2019-10-29 00:28
@poshul I am pretty convinced its this change

```
directive_defaults["language_level"] = sys.version_info.major
```

which is probably the difference between `from pyopenms_2 cimport FeatureFindingMetabo` and `from .pyopenms_2 cimport FeatureFindingMetabo`

**Comment by poshul** [comment] 2019-10-29 10:03
@hroest I can confirm that is the issue. I've submitted a pull request (https://github.com/uweschmitt/autowrap/pull/80) to address this.

**Comment by uweschmitt** [comment] 2019-10-29 11:19
I think this pull request has effects beyond `PyOpenMS` when people use Python 3 for building and write Python 3 code in their wrapper files.

As far as I understand you try to use Python 3 to build the wrapper but use old Python 2 in your pxd files.

I think the cleaner fix would be to rewrite the wrapper files in `pyOpenMS`, or we implement an extra option for `autowrap` to enforce Python 2 `.pxd` files and imports.

**Comment by poshul** [comment] 2019-10-29 15:28
@uweschmitt Any suggestions as to why bumping to version 3 causes an issue? The logs are basically full of: pyopenms/pyopenms_1.pxd:883:0: 'pyopenms_2.pxd' not found

**Comment by hroest** [comment] 2019-10-29 16:36
@poshul it works with https://github.com/uweschmitt/autowrap/pull/82 and https://github.com/OpenMS/OpenMS/pull/4334

**Comment by poshul** [comment] 2019-11-21 10:58
> @poshul it works with [uweschmitt/autowrap#82](https://github.com/uweschmitt/autowrap/pull/82) and #4334

I've been trying to get all of the autowrap tests working wtth https://github.com/uweschmitt/autowrap/pull/82 but cannot. It looks like the issue is that create_cpp_extension the combining of individual pxds into pyopenms_N.pxd doesn't reference the relative location of the other pyopenms_N.pxd files. I am going to work on seeing if I can change create_cpp_extension to correct this with language_level=3.

**Closed** 2019-11-28 01:09 UTC
Labels: Documentation, pyOpenMS
