### ISSUE TITLE
GH Actions: OpenPepXL failing on Linux.

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#6080] opened 2022-04-28 20:23 UTC
Probably some container not uptodate

**Comment by enetz** [comment] 2022-05-03 15:17
@jpfeuffer is this still an issue? What exactly is the failing GH Action? As far as I can see, it doesn't fail on any PR tests, and nightlies are being built successfully as well, right?

**Comment by jpfeuffer** [comment] 2022-05-03 15:31
https://cdash.seqan.de/viewTest.php?onlyfailed&buildid=34182

**Comment by jpfeuffer** [comment] 2022-05-03 15:31
https://cdash.seqan.de/viewTest.php?onlyfailed&buildid=34182

**Comment by jpfeuffer** [comment] 2022-05-03 15:32
The exit status of the action seems wrong. Only windows completes successfully but the actions says overall success

**Comment by enetz** [comment] 2022-05-04 15:24
I used clang on my Ubuntu Laptop before and now made sure there is no problem caused by differences in gcc and clang. With the current contrib libs, it doesn't fail on Ubuntu 10.04 with gcc and clang.
Are any of the test using some default system libs instead of the contrib libs maybe?

**Comment by jpfeuffer** [comment] 2022-05-04 18:29
The problem is probably the container that is used. On GH actions they are prebuilt containers that have contrib included.
E.g. openms/contrib or openms/manylinux_contrib

**Comment by jpfeuffer** [comment] 2022-05-09 15:12
What are you base64 encoding here? The floating point representations or string representations of the numbers?

**Comment by enetz** [comment] 2022-05-09 15:14
it's a string, these are the three most important lines in the code:
```
      s += String(Math::roundDecimal(spec[i].getMZ(), -6)) + "\t";
      s += String(Math::roundDecimal(spec[i].getIntensity(), -4)) + "\t";
...
Base64().encodeStrings(in_strings, out_encoded, false, false);
```

**Comment by jpfeuffer** [comment] 2022-05-09 15:49
We are using boost spirit for string conversions of numbers in OpenMS::String
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/include/OpenMS/DATASTRUCTURES/StringConversions.h

and I think they merged my PR to boost at some point. https://github.com/boostorg/spirit/pull/586
Maybe it is this.. I don't know. I am not very keen on reiterating conversion.. was very cumbersome

**Comment by jpfeuffer** [comment] 2022-05-09 17:15
But also thqle question is if and why the GH actions uses a different boost then

**Comment by jpfeuffer** [comment] 2022-05-09 17:18
https://cdash.openms.de/build/38397/configure
Uses boost 1.71
Does it find the system boost? Is the contrib not uptodate on the container. Those are the important things to check.

The stability of your tests can be addressed in a second step.

**Comment by enetz** [comment] 2022-05-09 20:58
OK, if I read that correctly, the GH Action is using `ghcr.io/openms/contrib_manylinux2014:latest`. I looked into that container and `contrib-build/include/boost/version.hpp` says `#define BOOST_LIB_VERSION "1_71"`. So the contrib_manylinux2014 container contains an older contrib version.

**Comment by jpfeuffer** [comment] 2022-05-09 21:08
OK hmm according to the "deploy manylinux" action in OpenMS/contrib it was built after the push that updated boost.
Did it not overwrite the container?

**Comment by jpfeuffer** [comment] 2022-05-09 21:17
The docker file is wrong:
 
 https://github.com/OpenMS/dockerfiles/blob/master/pyOpenMS/manylinux/Dockerfile#L16

Checking out contrib from the OpenMS submodule does of course not work before even merging it to contrib...

**Comment by enetz** [comment] 2022-05-09 22:12
This docker file defines the OpenMS branch and version as `develop, latest` and then uses the linked submodule for contrib. If it's always building latest develop anyway, wouldn't it be fine to just clone the latest `contrib master`?
Right now develop links to the latest contrib, so rebuilding the container with current setting would solve this for now, right?

**Comment by jpfeuffer** [comment] 2022-05-10 08:12
For now, yes. But will break everytime we change contrib. Check the other contrib Docker file. It should be parameterizable to work with latest/develop and any release branch. In case we have to update containers for older releases or fixes to a current release.

**Comment by enetz** [comment] 2022-05-12 11:18
I think the rebuild worked, boost 1.78 is now used in the GH Actions, but some other unrelated problems have cropped up.

About updating the Docker file:

the other contrib docker file https://github.com/OpenMS/dockerfiles/blob/master/contrib/Dockerfile
does this for some libs:
`RUN apt-get install -y --no-install-recommends --no-install-suggests libsvm-dev libglpk-dev libzip-dev ... libboost-date-time1.62-dev libboost-iostreams1.62-dev ...`

and this for some others:
```
RUN git clone https://github.com/OpenMS/contrib.git && rm -rf contrib/.git/
...
RUN cmake -DBUILD_TYPE=WILDMAGIC ../contrib && rm -rf archives src
...
```
so it isn't parameterized and just uses fixed / OS default versions for some libs and latest contrib for others

then the library docker file does this:
```
ARG OPENMS_TAG=latest
FROM ghcr.io/openms/contrib:${OPENMS_TAG}
```
so as long as we have pre-built contribs for all relevant OpenMS versions, can we use the same contrib builds for the GH Actions? Or is there a reason we use the manylinux contrib build there? The manylinux contrib build has the advantage of using all our contrib libs and much less OS default libs. Is that necessary for the GH Actions?

**Comment by jpfeuffer** [comment] 2022-05-12 11:22
Yes, you are right, they differ in which contrib they use. I personally do not care so much. Keep in mind that manylinux is RedHat Linux, so the contrib libs' availability may differ.
I think it is nice to test different strategies.

**Comment by enetz** [comment] 2022-07-08 07:49
fixed by updating the manylinux container
hasn't cropped up again since then, as far as I can see

**Closed by enetz** 2022-07-08 07:49 UTC
Labels: blocker, CI
