### ISSUE TITLE
TOPPAS & TOPPView Tutorial documentation unreachable from within the app

### ISSUE THREAD

**Issue by jgbradley1** [OpenMS/OpenMS#1028] opened 2014-09-30 07:27 UTC
I've been learning to use OpenMS for the past couple of months and it's great. These are 2 small bugs that I thought I'd report to help future OpenMS users. I'm using v1.11.1 under Mac (I'm on Mac OS 10.9.5). In TOPPAS, when I go to Help -> TOPPAS tutorial, I get the following error message.

Unable to open
html/TOPPAS_tutorial.html
Possible reason: security settings or misconfigured Operating System

I also get a similar issue in TOPPView when I go to Help -> Tutorials and documentation. The error message is

Unable to open
html/index.html
Possible reason: security settings or misconfigured Operating System

I reinstalled everything just to see if I had changed any settings by accident, but the problem still persist. I have not changed my security settings to block the app from making calls to the internet. Since the documentation is installed locally in the OpenMS folder, can I suggest just having the menu option open the local files? Either that or the url links will need to be fixed. I'm guessing the url has been hard-coded by accident.

**Comment by timosachsenberg** [comment] 2015-02-05 15:09
This seems to be a security / firewall issue as I can't reproduce it.

**Comment by hroest** [comment] 2017-04-28 18:56
closed as invalid / not reproducible

**Closed by hroest** 2017-04-28 18:56 UTC
Labels: Documentation, invalid, review, TOPPAS
