### ISSUE TITLE
PercolatorAdapter usability

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/OpenMS#3363] opened 2018-04-04 18:32 UTC
It is really hard to find the right settings. Especially since it depends on the right settings in not only the last tool (PSMFeatureExtractor) but also the tool before (e.g. MSGF+Adapter -add_features).
At least I would hope that the user gets a good error message on what to do in the previous tools when the settings were wrong. But it just gives you warnings and skips (MSGF) PSMs that e.g. do not have enough features.
To be honest, why can't we integrate PSMFeatureExtractor into the PercolatorAdapter?
And shouldn't we make add_features = true the default? How much does it add?

**Comment by jpfeuffer** [comment] 2018-04-04 18:38
Thinking about it more: Do you need the PSMFeatureExtractor if you do "add_features" in MSGF?
And actually sorry for opening a new issue. This came up twice already.

**Comment by jpfeuffer** [comment] 2018-04-04 18:38
#3071 #3188

**Comment by hroest** [comment] 2018-04-04 20:34
>  To be honest, why can't we integrate PSMFeatureExtractor into the PercolatorAdapter?

:+1: to that

**Comment by algom** [comment] 2018-04-05 08:39
I would also welcome having "add_features" as default. I also don't clearly understand the PSMFeatureExtractor. A "vanilla" percolator run would be:

Search engine (eg MSGF+) -> msgf2pin (tandem2pin, sqt2pin)-> Percolator
Or directly from the comet output (output_percolatorfile = 1) Comet -> Percolator

Is the PSMFeatureExtractor node using this converters or doing something similar? 

Moreover, setting the debug to a higher value I can see that the PercolatorAdapter is converting the idxml to a pin (default tab-separated txt file input for percolator), run percolator then converting back to idxml. Wouldn't be possible to be able to use the mzid output (MSGF) or pepxml (comet) and use these as input?

**Comment by Leon-Bichmann** [comment] 2018-04-05 08:40
Yes, I agree as well. Especially the add_features true as default is a good idea.

**Comment by lars20070** [comment] 2018-04-05 08:52
`add_feature = true` in https://github.com/OpenMS/OpenMS/pull/3362
Merge?

**Comment by jpfeuffer** [comment] 2018-04-05 20:15
@algom Yes, the feature extractor is doing similar stuff to the msgf2pin script. But since it is mandatory for Percolator and not really anything else, I think it makes sense to put it there internally. It can still be extended for different search engines.

**Comment by lars20070** [comment] 2018-05-08 11:08
`add_feature = true` is now merged.

**Comment by wenjiebi** [comment] 2018-05-08 12:04
@Leon-Bichmann @mwalzer Although I  set `add_features = true ` in the MSGFPlusAdapter, the `PercolaterAdatper` still wouldn't go through. The error message was `No search engine specific features found. Generate search engine specific features using PSMFeatureExtractor or set the -generic-features-set flag to override`. 

Then I took the later option to set `generic-features-set = true` and the `PercolaterAdapter` was finished successfully.

**Comment by lars20070** [comment] 2018-05-08 12:28
@MatthewThe What is the official recommendation?
Should `PercolatorAdapter` be run with or without `PSMFeatureExtractor` before?

**Comment by MatthewThe** [comment] 2018-05-08 13:15
As it is implemented now `PSMFeatureExtractor` should be run before. `generic-features-set = true` will produce sub-optimal results as it does not use the search engine specific features.

The main reason for using two nodes was to separate the `converters` functionality from the vanilla `percolator` functionality. However, I agree that it would be a nice feature to be able to interface `PercolatorAdapter` directly to a search engine node, while keeping the `PSMFeatureExtractor` node for more advanced use cases. It is probably relatively easy to do so by calling the `PercolatorFeatureSetHelper` functions, as is done here: https://github.com/OpenMS/OpenMS/blob/develop/src/utils/PSMFeatureExtractor.cpp#L245

**Comment by lars20070** [comment] 2018-05-09 08:47
<img width="931" alt="screen shot 2018-05-09 at 10 46 30" src="https://user-images.githubusercontent.com/6149805/39805134-47e17238-5376-11e8-968f-18156f2ea645.png">
Here the corresponding workflows.

**Comment by wenjiebi** [comment] 2018-05-09 08:56
Here is the workflow we use
![workflow](D:/1A_Daten_User/Wenjie/2018-05-06 Knime test/workflow.png)

**Comment by wenjiebi** [comment] 2018-05-09 09:04
Here are the parameters in the PercolatorAdapter

![percolater 1](https://user-images.githubusercontent.com/35566652/39805966-bcc330c6-5378-11e8-969d-dac7ee2115fe.PNG)
![percolater 2](https://user-images.githubusercontent.com/35566652/39805968-c096c4a6-5378-11e8-8c92-f18f7eef3827.PNG)

**Comment by MatthewThe** [comment] 2018-05-09 09:34
That is odd, can you somehow verify (e.g. from the logs) that percolator uses the MSGF+ features when using `PSMFeatureExtractor`?

I'm also not sure what happens if you run `FalseDiscoveryRate` after `PercolatorAdapter`, since `PercolatorAdapter` already calculates the FDR. Btw, I assume that when you say "protein hits" or "peptide hits" you filtered them at some FDR?

**Comment by lars20070** [comment] 2018-05-09 09:40
[Here](https://www.dropbox.com/s/i95n2paiydw0uc0/2018-05-08-peptide-IDs-with-Percolator.knwf?dl=1) the workflow which did run in the current nightly build.

**Comment by MatthewThe** [comment] 2018-05-14 15:14
`peptide-level-fdrs` and `protein-level-fdrs` should both be set to true.

**Comment by wenjiebi** [comment] 2018-05-14 15:46
@MatthewThe It didn't work. Could it be the problem with the FDR settings?

![Uploading FDR parameters.PNG…]()

Under the item `FalseDiscoveryRate`, both `PSM` and `protein` are set to `true`. I guess this is correct, isn't it?

**Comment by MatthewThe** [comment] 2018-05-14 15:58
That looks fine, unless you also want to report the number of proteins at say 1% FDR, then you have to change the 1.0 to 0.01. I don't see anything obviously wrong with your settings. Would it be possible to share the intermediate files that you feed into the 3 different FalseDiscoveryRate nodes?

**Comment by wenjiebi** [comment] 2018-05-14 20:25
[Here](https://www.dropbox.com/sh/yriybrd1j7rx2mm/AACuMWI0B9KTrPIrjk00JsvNa?dl=0) are the workflow, database and mzML files. To make the mzML smaller I already filtered it. And with this small file the peptides hits from the output after `PercolatorAdapter` are 50% of the output without PercolatorAdapter. The whole workflow can be finished within 10 minutes.

Thanks a lot.

**Comment by MatthewThe** [comment] 2018-05-15 09:37
I suspect the issue is that PercolatorAdapter labels PeptideHits with `target_decoy` value "target+decoy" (as set by `PeptideIndexer`) as decoys instead of targets: https://github.com/OpenMS/OpenMS/blob/d26047ce512c545136b59a4c4be77277c76f4a83/src/topp/PercolatorAdapter.cpp#L408

**Comment by timosachsenberg** [comment] 2018-05-15 10:29
k I can fix this.

**Comment by timosachsenberg** [comment] 2018-05-15 11:54
might be addressed in https://github.com/OpenMS/OpenMS/pull/3462

**Comment by lars20070** [comment] 2018-05-17 08:10
@algom has extensively tested inference in `Percolator` and compared to `ProteinProphet`. Would be useful to use this part of the algorithm as part of our workflows. https://github.com/OpenMS/OpenMS/issues/3466

**Comment by MFreidank** [comment] 2018-05-28 12:51
@MatthewThe
I experimented a little bit with the nice example workflow provided by @wenjiebi (thank you for that). 
I could reproduce his 50% decrease in found peptides after percolator even after changes by @timosachsenberg in #3462. One suspicion that I have is that since `peptide-level-fdrs` parameter in `PercolatorAdapter` is set to `true` there is already one fdr applied there and another one is then applied on top in the `FalseDiscoveryRate` note that follows it. If I turn off `peptide-level-fdrs` in PercolatorAdapter in the workflow of @wenjiebi I get the following numbers:

| MSGFPlus  | MSGFPlus + Percolator | MSGFPlus + PSMFeatureExtractor + Percolator |
| ------------- | ------------- | ------------- |
|   peptide hits:               1364 (avg. length: 15)  |   peptide hits:               1435 (avg. length: 15) |   peptide hits:               1379 (avg. length: 15) |
Weirdly enough, using `PSMFeatureExtractor` before `PercolatorAdapter` seems to slightly *decrease* the number of peptide hits. Does my suspicion regarding double-fdr make sense? Why would adding a `PSMFeatureExtractor` decrease the number of peptide hits?

**Comment by wenjiebi** [comment] 2018-05-28 13:12
I got exactly the same data as @MFreidank and also wondering why.

**Comment by MatthewThe** [comment] 2018-05-28 13:55
I think the issue is that setting `peptide-level-fdrs` only retains one (i.e. the best scoring) PSM per unique peptide sequence. In Percolator we make a distinction between PSM level and peptide level, since we believe that the latter is actually the more useful of the two.

**Comment by lars20070** [comment] 2018-05-28 14:49
@MatthewThe Ok. So in `Percolator` peptide-level FDR, and in subsequent OpenMS `FalseDiscoveryRate` tool PSM-level FDR. I guess we need the later, since we need PSMs which we then map to MS1-level quants.

But why fewer hits if we add the `PSMFeatureExtractor` to the workflow?

**Comment by MatthewThe** [comment] 2018-05-28 15:27
I'm not entirely sure if this is the reason, but I found several high scoring (MSGF+ EValues < 1e-10) decoy hits that have almost an identical sequence as a target peptide, differing only in one amino acid (among which, but not exclusively, isoleucine <-> leucine substitutions). It could be that these extremely high scoring decoy hits are messing up the percolator SVM training.

Perhaps you could try using a reversed decoy database instead of a shuffled one. I will take a closer look myself tomorrow as well.

**Comment by lars20070** [comment] 2018-05-29 07:58
@MatthewThe If *target* and *decoy* sequences are too similar, we can generate a new `fasta` and increase `shuffle_sequence_identity_threshold` and `shuffle_max_attempts` in the  [`DecoyDatabase`](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/RC/2.3.0/html/UTILS_DecoyDatabase.html) tool.

**Comment by wenjiebi** [comment] 2018-05-29 13:56
To test the `shuffle_sequence_identity_threshold`, I shuffled the database with gradient threshold: 0.5, 0.2, 0.1 and 0.05. At the same time I turned on the` -IL_equivalent parameter` in the `PeptideIndexer` and `-post-processing-tdc` in `PercolatorAdapter`. Here are the results I got

Threshold for   shuffle_sequence_identity | MSGF+ | MSGF++Percolator | MSGF++PSMEx+Percolator
-- | -- | -- | --
0.5 | 1487 | 1471 | 1509
0.2 | 1438 | 1466 | 1562
0.1 | 1579 | 1572 | 1725
0.05 | 1590 | 1544 | 1841

It seems that `MSGF++PSMEx+Percolator` can always improve the amount of PSMs after FDR. And lower the threshold would also help.

But I don't know what happened in `MSGF++Percolator` with threshold of 0.5. Maybe because the parameters has changed: ` -IL_equivalent parameter` in the `PeptideIndexer` and `-post-processing-tdc` in `PercolatorAdapter` .

**Comment by MatthewThe** [comment] 2018-05-29 14:57
I noticed this yesterday but forgot to mention it: `MSGF++Percolator` often doesn't do any useful training (you can check the `StdErr view` log of the PercolatorAdapter node). I think this is because it uses the `EValue` from MSGF+ directly, without log transformation. Since all these `Evalue`s are very close to each other (say 1e-10 to 1e-4), it might be hard to use this as a feature in Percolator.

**Comment by hroest** [comment] 2018-05-29 15:57
> To test the shuffle_sequence_identity_threshold, I shuffled the database with gradient threshold: 0.5, 0.2, 0.1 and 0.05. At the same time I turned on the-IL_equivalent parameter in the PeptideIndexer and -post-processing-tdc in PercolatorAdapter. Here are the results I got

I think at some point you are basically replacing your target-decoy database with a random AA database which does not have the same distribution in AA frequency etc and then the target decoy approach is potentially not fair any more.

**Comment by wenjiebi** [comment] 2018-05-30 08:57
@hroest Are you suggesting that we should use a decoy database similar to target database, to keep `shuffle_sequence_identity_threshold` around 0.5?

**Comment by lars20070** [comment] 2018-05-30 09:41
@wenjiebi Thanks a lot for these tests. Could you please run a final test with a simple *reverse database*? At least, this approach has no parameters which require optimisation.

@MatthewThe Since this thread is about usability, here three suggestions to make life easier for the end user.
- Hide `peptide/protein_level_fdrs` i.e. make these parameters *advanced*. They are already by default switched off. By default, FDR filtering should be done in OpenMS.
- Incorporate `PSMFeatureExtractor` in the adapter, and switch it by default on.
- Mention a recommendation for `DecoyDatabase` settings in the `PercolatorAdapter` docu. (Perhaps simply reverse).

In the end, inserting `PercolatorAdapter` with its default settings in between a search engine adapter and the OpenMS `FalseDiscoveryRate` tool, should always increase the number of PSMs and never decrease them.

**Comment by algom** [comment] 2018-05-30 09:50
@lars20070  Why would you need `FalseDiscoveryRate`? `PercolatorAdapter` already gives you a q-value, you would just need to do `IDFilter` on it. Otherwise what is the reason to run  `FalseDiscoveryRate`

**Comment by wenjiebi** [comment] 2018-05-30 11:00
With a reverse database I got the data as follows

  | MSGF+ | MSGF++Percolator | MSGF++PSMEx+Percolator
-- | -- | -- | --
Peptide hits | 1415 | 1461 | 1431

So the performance of Percolator or PSMEx+Percolator really depends on the decoydatabase we use.

**Comment by wenjiebi** [comment] 2018-05-30 13:49
[here ](https://www.dropbox.com/sh/co1sy2ynbf75n4g/AABhBfmxaTzd9KY8H_XJ5WI7a?dl=0) are the files, including a fitlered mzML file, a original database and the workflow I used.

**Comment by MatthewThe** [comment] 2018-05-30 15:26
I can indeed reproduce the results of @wenjiebi . Upon closer analysis, I found the following:
* The `dm` and `absdm` (delta mass and absolute delta mass) features are not correctly calculated for the cases where MS-GF+ matches the +1 isotope (set by the `-isotoper_error_range` flag): https://github.com/OpenMS/OpenMS/blob/17081894ccceae8c14a791ab63fd5eac2c9e9be0/src/topp/PercolatorAdapter.cpp#L446
Instead of values close to 0 we get values around 0.5 for charge2 peptides, around 0.33 for charge3 peptides and around 0.25 for charge4 peptides. As `delta mass` is typically a very informative feature, this could make quite a difference for Percolator training.
* From the logs I can see that for PSMEx+Percolator, Percolator resets the score vector, as the cross validated scores do not show an improvement over using only the `lnEvalue` feature from MS-GF+. This is a sign that Percolator is overfitting to the training bins, which might be a result of the `delta mass` issue above. We can override the resetting by setting the `-override` flag in `PercolatorAdapter`, which gives an increase to 1510 PSMs after target-decoy competition.
* Removing the +1 isotope matching from the MS-GF+ settings shows the expected improvement for PSMEx+Percolator:

|          | MSGF+ | MSGF++Percolator | MSGF++PSMEx+Percolator|
|--------|------------|--------------------------- |---------------------------------------|
|PSMs|1179      | 1210 (score vector reset) |  1310 (successful training)|

**Comment by timosachsenberg** [comment] 2018-05-30 17:57
Ok, I think we could check if there is a meta value "IsotopeError" and "isotope_error" with value != 0
and calculate dm and absdm correctly. This would fix the problem MSGFPlus (and also of SimpleSearchEngine)

**Comment by lars20070** [comment] 2018-05-31 05:54
@algom @Leon-Bichmann I think it would be good to always set the FDR in the [`FalseDiscoveryRate`](https://github.com/OpenMS/OpenMS/blob/develop/src/topp/FalseDiscoveryRate.cpp#L120) tool. No matter if the workflow includes `Percolator` or not. More consistent workflows for the end user, less support for us.

**Comment by algom** [comment] 2018-06-01 07:32
@lars20070 I don't think that is a good idea. It will not be consistent as the idea of post scoring models is to obtain a more confident FDR, and the `FalseDiscoveryRate` is yet another way of calculating an FDR. Moreover, even in the documentation of the `FalseDiscoveryRate` the note 
> Alternativly (sic), FDR filtering can be performed in the IDFilter tool by setting score:pep and score:prot to the maximum q-value

**Comment by hroest** [comment] 2018-06-01 18:47
> @hroest Are you suggesting that we should use a decoy database similar to target database, to keep shuffle_sequence_identity_threshold around 0.5?

Yes, I am saying that a reverse database is somewhat safer and that shuffling + randomly mutating AA may not be a such a good idea since it may overfit the data

**Comment by wenjiebi** [comment] 2018-06-04 13:01
@hroest Thank you for the suggestion.


  | MSGF+ | MSGF++Percolator | MSGF++PSMEx+Percolator
-- | -- | -- | --
Peptide hits | 40535 | 40810 | 45723

@MatthewThe By testing Percolator with a complete mzML file, I got these data. `MSGF+ + PSMFeatureExtractor + Percolator` contributed 12% increase of PSMs, which is quite good as expected. I have no idea why `MSGF+ + Percolator `only led to not even 1% increase, but we don't need it anyway.

**Comment by hroest** [comment] 2018-06-05 15:07
@timosachsenberg @lars20070 @wenjiebi do you think it would make sense to automatically document and test such workflows for a few different use cases? I would like to have some integration tests in OpenMS and this seems like a very basic one where we test that the whole workflow from mzML + fasta to ids and quantified features works. Would that be something that makes sense? We could host the data somewhere and have an automated scrip that downloads data, runs a workflow and does some checks, ,e.g. that number of features are within +/- 5% of what they should be? I think it would be much easier if we had those on some real-world dataset

**Comment by timosachsenberg** [comment] 2018-06-05 15:19
Absolutely. Workflow tests are on our todo list. 
@jpfeuffer is currently looking at different options

**Comment by lars20070** [comment] 2018-06-05 15:21
@hroest Yes, definitely. See https://github.com/OpenMS/OpenMS/issues/1827 We discussed this at the developer retreat.

I provided Julianus already a complete TMT10 example (`knwf`, `mzML`, `fasta`, results). Examples like the one above will follow.

**Closed** 2020-06-18 23:20 UTC
Labels: enhancement, wontfix
