### ISSUE TITLE
Tool doc links are dysfunctional 

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4557] opened 2020-03-02 17:46 UTC
The links given in the CLI help are dysfunctional 

For instance http://www.openms.de/documentation/TOPP_RTModel.html seems to redirect to https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/TOPP_RTModel.html which gives a 404.

**Comment by jpfeuffer** [comment] 2020-03-02 18:39
The names had to be shortened since they are too long for Windows systems.
Someone needs to implement a switch and change the CI to ignore windows.

**Comment by bernt-matthias** [comment] 2020-03-02 18:50
Seems that windows is still caught in medieval times. I never understood why and how scientific computing is done on windows systems :) ..

**Comment by cbielow** [comment] 2020-03-03 07:35
Not sure I follow this:
Windows traditionally has a path length restriction up to 257 chars (or something along those lines).
This can be lifted to 2^16 chars by setting a flag in the regex in Win10, but thats not the point:

Doxygen will not create hugely long filenames if `SHORT_NAMES = NO` is used in `Doxyfile.in`. 
So as long you do not hide the OpenMS build tree into a long and winded subdirectory structure, everything should be fine. Indeed I tried and it works just nicely on my machine.
 Is this a side-effect of JENKINS or some other CI going crazy with paths?

**Comment by jpfeuffer** [comment] 2020-03-03 09:31
For me it created an html for every namespace and nested struct. In the end, there were names like FeatureFinderAlgorithmSuperhirn_LongStruct_LongEnum_LongValue.

**Comment by cbielow** [comment] 2020-03-03 11:11
Yes, but if you keep the build tree sufficiently shallow this works fine.

**Comment by bernt-matthias** [comment] 2020-03-03 15:43
I think the problem is not about building (at least for me). The problem is that the URLs given in the command line help (for the binaries in the 2.5 conda package) are not existent.

**Comment by jpfeuffer** [comment] 2020-03-03 16:03
Yes but we switched to building with Short names because there were errors on windows

**Comment by jpfeuffer** [comment] 2020-03-04 11:30
@cbielow It happens during installer creation because CMake adds many subfolders:
`File: failed opening file "C:/jenkins/ws/openms_user_experimental/openms_test_packaging/9447518b/build/_CPack_Packages/win64/NSIS/OpenMS-2.5.0-HEAD-2020-03-03-Win64/share/doc\html\structOpenMS_1_1Internal_1_1Looper_3_01grid__size_00_01grid__size_00_01EvalResult_00_01Tuple_00_01TupleTypes_8_8_8_01_4-members.html"
`

**Comment by cbielow** [comment] 2020-03-04 12:01
So this happens when the installer unpacks its data into "C:/jenkins/ws/openms_user_experimental/openms_test_packaging/9447518b/build/_CPack_Packages/win64/NSIS" ?
If, so, just install to a shorter path?!

**Comment by jpfeuffer** [comment] 2020-03-04 15:31
I don't know if that is possible. This is not "installing". This is what happens when you do "make package".

**Comment by jpfeuffer** [comment] 2020-03-04 15:33
And if we move out of the build folder, we have to do manual cleanups and have to make sure that a unique build name is created, etc.

**Comment by cbielow** [comment] 2020-03-04 15:42
ok, I did not even know the NSIS which comes with CMake is actually working as intended...
Is this installer used?

**Comment by jpfeuffer** [comment] 2020-03-04 15:43
hehe, yes it is the most downloaded installer of all.

**Comment by jpfeuffer** [comment] 2020-03-04 20:33
I will try to shorten build paths as much as I can. I read that "just setting the registry key for long paths" might not work because a lot of programs (MSBuild, NSIS?) might not be able to handle it.
I think we should instead also think about
EXCLUDE_SYMBOLS in Doxygen. E.g. the full Internal namespace.

**Comment by oliveralka** [comment] 2020-03-05 10:36
I have found that the naming is different as well: 

Link to macOS build instructions (install_mac.html):  
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/install_mac.html (404)

Current active link (a16114.html): 
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/a16114.html

**Comment by jpfeuffer** [comment] 2020-03-07 12:38
Should be fixed. Please reload without cache.

**Closed by jpfeuffer** 2020-03-07 12:38 UTC

**Comment by bernt-matthias** [comment] 2020-03-07 19:29
Wonderful thanks. Is there a way to fix this related issue https://github.com/OpenMS/OpenMS/issues/4557

**Comment by jpfeuffer** [comment] 2020-03-07 19:47
I think you linked the wrong one. 4557 is this one here. ;)

**Comment by bernt-matthias** [comment] 2020-03-07 20:09
Ups: https://github.com/OpenMS/OpenMS/issues/4472
