### ISSUE TITLE
MSGF+ error 

### ISSUE THREAD

**Issue by ypriverol** [OpenMS/OpenMS#1771] opened 2016-01-19 12:25 UTC
Hi @all:
 I'm trying to run the MSGFPlusAdapter using the nightly installation (Mac). Here the output:

-----------
12:21:32 NOTICE: MSGFPlusAdapter of node #7 started. Processing ...
Debug level (after ini file): 1
Value of string option 'no_progress': 0
Value of string option 'in': /Users/yperez/work/ms_work/tabb-project/Acetylated-lysine/140702_0001_DC2ac_6600_noG12_DDA1-DC2ac_6600_noG12_DDA1.mzML
Value of string option 'out': 
Value of string option 'mzid_out': /var/folders/hm/w90zk0x90sv25st_pm8xdw940000gq/T/2016-01-19_120001_proteomicsdevmbpr1_33177_1/TOPPAS_tmp/label-free-workflow/007_MSGFPlusAdapter/mzid_out/140702_0001_DC2ac_6600_noG12_DDA1-DC2ac_6600_noG12_DDA1.mzML_tmp001
Value of string option 'database': /var/folders/hm/w90zk0x90sv25st_pm8xdw940000gq/T/2016-01-19_120001_proteomicsdevmbpr1_33177_1/TOPPAS_tmp/label-free-workflow/004_DecoyDatabase/out/20151215-RefSeq-ECOLI-Cntms.fasta
Value of string option 'fixed_modifications': Carbamidomethyl (C)
Value of string option 'variable_modifications': Acetyl (K)
Value of string option 'variable_modifications': Oxidation (M)
Value of string option 'variable_modifications': Acetyl (N-term)
Value of int option 'max_mods': 2
Value of string option 'force': 1
The installation of Java was not checked.
Creating temporary directory '/var/folders/hm/w90zk0x90sv25st_pm8xdw940000gq/T/2016-01-19_122132_proteomicsdevmbpr1_33841_1/'
Value of string option 'enzyme': trypsin
Value of double option 'precursor_mass_tolerance': 50
Value of string option 'precursor_error_units': ppm
Value of int option 'min_precursor_charge': 2
Value of int option 'max_precursor_charge': 3
Value of int option 'java_memory': 3500
Value of string option 'executable': /Applications/OpenMS-2.0.0/TOPP/SEARCHENGINES/MSGFPlus/MSGFPlus.jar
Value of string option 'fragment_method': from_spectrum
Value of string option 'instrument': TOF
Value of string option 'protocol': none
Value of string option 'tryptic': fully
Value of string option 'isotope_error_range': 0,1
Value of string option 'add_decoys': 0
Value of int option 'min_peptide_length': 6
Value of int option 'max_peptide_length': 40
Value of int option 'matches_per_spec': 1
Value of string option 'add_features': 0
Value of int option 'threads': 1
Value of string option 'legacy_conversion': 0
Fatal error: Running MS-GF+ returned an error code. Does the MS-GF+ executable (.jar file) exist?
MSGFPlusAdapter took 0.00 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user).

-----------

I check the issues and looks similar to this issue #1251 and I follow the @hendrikweisser suggestion of donwloading the latest version from http://omics.pnl.gov/software/ms-gf . But I have still the error.

**Comment by hendrikweisser** [comment] 2016-01-19 15:09
Looks like the same problem as https://github.com/OpenMS/OpenMS/issues/1764.

**Comment by ypriverol** [comment] 2016-01-19 15:52
@hendrikweisser I just try all the options in #1764 and still error, I'm using a Mac and the commandline option works.

**Comment by hendrikweisser** [comment] 2016-01-19 16:00
Have you used the MSGFPlusAdapter on a Mac before (successfully)?

It seems strange to me that we suddenly get multiple reports of the adapter not working on Mac. I can't think of any recent changes in OpenMS that should affect it (however, that doesn't mean there are none). I can't shake the feeling that it might be caused by a recent Java update on Mac OS X, but I haven't investigated it myself.

**Comment by ypriverol** [comment] 2016-01-19 16:03
@hendrikweisser  use this before in Mac ?

Why a Java update on Mac OS X can affect the Adapter if the commandline version works?

**Comment by hendrikweisser** [comment] 2016-01-19 17:12
> use this before in Mac ?

What I mean is, is this the first time you've installed OpenMS on your Mac and tried MSGFPlusAdapter? Or have you used it before, but now after an update it's broken?

> Why a Java update on Mac OS X can affect the Adapter if the commandline version works?

I don't know, but why would *anything* have that effect?

**Comment by ypriverol** [comment] 2016-01-19 17:14
No @hendrikweisser is the first time I use OpenMS in my Mac, I normally use the EBI cluster, but I want to try in my Mac.

**Comment by hendrikweisser** [comment] 2016-01-21 11:36
I just tried it on my Mac and it worked for me. See my comment [here](https://github.com/OpenMS/OpenMS/issues/1764#issuecomment-173544489).

Could you try the test workflow [here](https://gist.github.com/hendrikweisser/6837ef2db6619cd64054)? You'll probably have to change the paths to the inputs and to the executable.

**Comment by ypriverol** [comment] 2016-01-21 11:44
@hendrikweisser I try and it fail. The dafault workflow (only changing my path for ms-gf+) through this error:

-----
11:41:06 NOTICE: MSGFPlusAdapter of node #3 started. Processing ...
Fatal error: Java not found, or the Java process timed out. Java is needed to run MS-GF+. Make sure that it can be executed by calling 'java', e.g. add the directory containing the Java binary to your PATH variable. If you are certain java is installed, please set the 'force' flag in order to avoid this error message.
MSGFPlusAdapter took 0.00 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user).
-----  

Then, I force it to do not use the check and still the error is present:

11:42:50 NOTICE: MSGFPlusAdapter of node #3 started. Processing ...
The installation of Java was not checked.
Fatal error: Running MS-GF+ returned an error code. Does the MS-GF+ executable (.jar file) exist?
MSGFPlusAdapter took 0.00 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).

------

Then I move the jar to the bin of OpenMS and same error.

This is my java configuration:
 
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**Comment by hendrikweisser** [comment] 2016-01-21 13:11
Okay. My Java version is:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)
```

However, I think I updated it recently. Let me just try and restart my computer.

**Comment by hendrikweisser** [comment] 2016-01-21 13:44
I updated my Java to 1.8.0_71 and it still works, both from the command line and in TOPPAS. (Actually had to jump through hoops with the Java update, see [here](http://stackoverflow.com/questions/12757558/installed-java-7-on-mac-os-x-but-terminal-is-still-using-version-6). Stupid Macs!)

**Comment by cbielow** [comment] 2016-01-21 16:19
How do you guys know that you execute the exact same command as TOPPAS?

You should run TOPPAS from the cmdline with --debug and after the TOPPAS failed for the first time (i.e. the Ini file and output directory structure is present), copy the command which TOPPAS used to invoke the adapter and run it in a second cmdline window (keeping TOPPAS running in the meantime).
THEN you should be closer to what goes wrong.
(maybe I missed it, and you already did that) :)

**Comment by ypriverol** [comment] 2016-01-29 13:29
@all I just one to let you know that I abandon my Mac machine and everything looks really stable in my Linux machine. I will try to spend sometime in the future with this issue.

**Comment by hendrikweisser** [comment] 2016-01-29 14:00
Glad it's working on Linux for you. It still annoys me that we didn't figure out what caused the problem for Macs, but I couldn't reproduce it one mine, so couldn't do much.

**Comment by ypriverol** [comment] 2016-01-29 14:00
If you want I can close this issue.

**Comment by timosachsenberg** [comment] 2016-01-30 16:00
we should keep an eye on it but lets close it for now

**Closed by timosachsenberg** 2016-01-30 16:00 UTC
