### ISSUE TITLE
FidoAdapter tests failed

### ISSUE THREAD

**Issue by sagitter** [OpenMS/OpenMS#1432] opened 2015-05-18 19:56 UTC
Hi all.

OpenMS-2.0.0
Fido is compiled from upstream source code at https://noble.gs.washington.edu/proj/fido/
The following tests failed:
	1641 - TOPP_FidoAdapter_1_out (Failed)
	1643 - TOPP_FidoAdapter_2_out (Failed)
	1645 - TOPP_FidoAdapter_3_out (Failed)
	1647 - TOPP_FidoAdapter_4_out (Failed)
```
       Start 1641: TOPP_FidoAdapter_1_out
1641: Test command: /builddir/build/BUILD/OpenMS-Release2.0.0/bin/FuzzyDiff "-ini" "/builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_1_output.tmp" "-in2" "/builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML" "-whitelist" "IdentificationRun date"
1641: Test timeout computed to be: 1500
test 1643
        Start 1643: TOPP_FidoAdapter_2_out
1643: Test command: /builddir/build/BUILD/OpenMS-Release2.0.0/bin/FuzzyDiff "-ini" "/builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_2_output.tmp" "-in2" "/builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML" "-whitelist" "IdentificationRun date"
1643: Test timeout computed to be: 1500
1643: Warning: Parameters file version (1.8.0) does not match the version of this tool (2.0.0).
1643: FAILED: 'ratio of numbers is too large'
1643: 
1643:   input:	in1	in2
1643:   line:	10	10
1643:   pos/col:	63/85	63/85
1643:  --------------------------------
1643:   is_number:	true	true
1643:   numbers:	0.80392	0.862051
1643:   is_space:	false	false
1643:   is_letter:	false	false
1643:   letters:	"0"	"0"
1643:   char_codes:	48	48
1643:  --------------------------------
1643:   relative_max:        1.07231
1643:   relative_acceptable: 1.01
1643:  --------------------------------
1643:   absolute_max:        0.0581308
1643:   absolute_acceptable: 0.01
1643: 
1643:   whitelist cases:
1643:     "IdentificationRun date"   1x
1643: 
1643: Offending lines:			(tab_width = 8, first_column = 1)
1643: 
1643: in1:  /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FidoAdapter_2_output.tmp   (line: 10, position/column: 63/85)
1643: 			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
1643: 			                                                            0.803920447826385" sequence="" >
1643: 
1643: in2:  /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML   (line: 10, position/column: 63/85)
1643: 			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
1643: 			                                                            0.862051248550415" sequence="" >
1643: 
1643: 
1643: Easy Access:
1643: /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FidoAdapter_2_output.tmp:10:85:
1643: /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML:10:85:
1643: 
1643: diff /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FidoAdapter_2_output.tmp /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML
1643: FuzzyDiff took 0.02 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).
1641: Warning: Parameters file version (1.8.0) does not match the version of this tool (2.0.0).
1641: FAILED: 'ratio of numbers is too large'
1641: 
1641:   input:	in1	in2
1641:   line:	8	8
1641:   pos/col:	63/85	63/85
1641:  --------------------------------
1641:   is_number:	true	true
1641:   numbers:	0.705907	0.91437
1641:   is_space:	false	false
1641:   is_letter:	false	false
1641:   letters:	"0"	"0"
1641:   char_codes:	48	48
1641:  --------------------------------
1641:   relative_max:        1.29531
1641:   relative_acceptable: 1.01
1641:  --------------------------------
1641:   absolute_max:        0.208463
1641:   absolute_acceptable: 0.01
1641: 
1641:   whitelist cases:
1641:     "IdentificationRun date"   1x
1641: 
1641: Offending lines:			(tab_width = 8, first_column = 1)
1641: 
1641: in1:  /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FidoAdapter_1_output.tmp   (line: 8, position/column: 63/85)
1641: 			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
1641: 			                                                            0.70590728521347" sequence="" >
1641: 
1641: in2:  /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML   (line: 8, position/column: 63/85)
1641: 			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
1641: 			                                                            0.914370179176331" sequence="" >
1641: 
1641: 
1641: Easy Access:
1641: /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FidoAdapter_1_output.tmp:8:85:
1641: /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML:8:85:
1641: 
1641: diff /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/FidoAdapter_1_output.tmp /builddir/build/BUILD/OpenMS-Release2.0.0/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML
1641: FuzzyDiff took 0.03 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).
946/951 Test #1643: TOPP_FidoAdapter_2_out .....................................***Failed    0.10 sec
947/951 Test #1641: TOPP_FidoAdapter_1_out .....................................***Failed    0.10 sec
```

Full log (at the bottom): https://copr-be.cloud.fedoraproject.org/results/sagitter/Fido-pi/fedora-22-x86_64/openms-2.0.0-13.fc21/build.log

**Comment by hendrikweisser** [comment] 2015-05-26 15:10
Can you try building Fido from here: https://github.com/hendrikweisser/Fido
That is the version that we used for the OpenMS tests.

**Comment by danielhyduke** [comment] 2015-05-26 20:46
I'm getting similar errors when I'm using Fido from hendrikweisser/Fido for TOPP_FidoAdapter_[1-4|6]_out.  I've built OpenMS from the git repository on CENTOS Linux 7 and I updated FuzzyDiff.ini with INIUpdater 

Also, TOPP_FidoAdapter_5 fails because it's looking for a file named FidoAdapter_5_input.idXML in  src/tests/topp/THIRDPARTY but the file's named Fido_Adapter_5_input.idXML (same for the *output.idXML file) in the repository.

1718/1785 Testing: TOPP_FidoAdapter_1
1718/1785 Test: TOPP_FidoAdapter_1
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FidoAdapter" "-test" "-in" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_input.idXML" "-out" "FidoAdapter_1_output.tmp" "-fidocp_executable" "/home/dhyduke/usr/local/bin/FidoChooseParameters"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_1" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
Reading input data...
Generating temporary files for Fido...
Warning: Scores of peptide hits seem to be posterior error probabilities. Converting to (positive) posterior probabilities.
Running Fido with parameter estimation...
Fido parameter search:
Using best gamma, alpha, beta = 0.1 0.01 0
Parsing Fido results and writing output...
Inferred 1516 proteins in 1376 groups (0 proteins with probability zero).
Removing temporary files...
FidoAdapter took 1.66 s (wall), 0.40 s (CPU), 0.00 s (system), 0.40 s (user).
<end of output>
Test time =   1.70 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_1" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_1" time elapsed: 00:00:01
----------------------------------------------------------

1719/1785 Testing: TOPP_FidoAdapter_1_out
1719/1785 Test: TOPP_FidoAdapter_1_out
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FuzzyDiff" "-ini" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_1_output.tmp" "-in2" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML" "-whitelist" "IdentificationRun date"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_1_out" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
FAILED: 'ratio of numbers is too large'

  input:	in1	in2
  line:	8	8
  pos/col:	63/85	63/85
 --------------------------------
  is_number:	true	true
  numbers:	0.116475	0.91437
  is_space:	false	false
  is_letter:	false	false
  letters:	"0"	"0"
  char_codes:	48	48
 --------------------------------
  relative_max:        7.85039
  relative_acceptable: 1.01
 --------------------------------
  absolute_max:        0.797896
  absolute_acceptable: 0.01

  whitelist cases:
    "IdentificationRun date"   1x

Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_1_output.tmp   (line: 8, position/column: 63/85)
			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
			                                                            0.116474539041519" sequence="" >

in2:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML   (line: 8, position/column: 63/85)
			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
			                                                            0.914370179176331" sequence="" >


Easy Access:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_1_output.tmp:8:85:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML:8:85:

diff /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_1_output.tmp /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML
FuzzyDiff took 0.00 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).
<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Failed.
"TOPP_FidoAdapter_1_out" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_1_out" time elapsed: 00:00:00
----------------------------------------------------------

1720/1785 Testing: TOPP_FidoAdapter_2
1720/1785 Test: TOPP_FidoAdapter_2
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FidoAdapter" "-test" "-in" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_input.idXML" "-out" "FidoAdapter_2_output.tmp" "-fidocp_executable" "/home/dhyduke/usr/local/bin/FidoChooseParameters" "-separate_runs"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_2" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
Reading input data...
Protein identification run 1:
Generating temporary files for Fido...
Warning: Scores of peptide hits seem to be posterior error probabilities. Converting to (positive) posterior probabilities.
Running Fido with parameter estimation...
Fido parameter search:
Using best gamma, alpha, beta = 0.7 0.09 0
Parsing Fido results and writing output...
Inferred 586 proteins in 561 groups (0 proteins with probability zero).
Protein identification run 2:
Generating temporary files for Fido...
Running Fido with parameter estimation...
Fido parameter search:
Using best gamma, alpha, beta = 0.7 0.09 0
Parsing Fido results and writing output...
Inferred 1113 proteins in 1006 groups (0 proteins with probability zero).
Protein identification run 3:
Generating temporary files for Fido...
Running Fido with parameter estimation...
Fido parameter search:
Using best gamma, alpha, beta = 0.3 0.01 0.025
Parsing Fido results and writing output...
Inferred 643 proteins in 617 groups (0 proteins with probability zero).
Removing temporary files...
FidoAdapter took 2.36 s (wall), 0.41 s (CPU), 0.00 s (system), 0.41 s (user).
<Warning: Scores of peptide hits seem to be posterior error probabilities. Converting to (positive) posterior probabilities.> occurred 3 times
<end of output>
Test time =   2.41 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_2" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_2" time elapsed: 00:00:02
----------------------------------------------------------

1721/1785 Testing: TOPP_FidoAdapter_2_out
1721/1785 Test: TOPP_FidoAdapter_2_out
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FuzzyDiff" "-ini" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_2_output.tmp" "-in2" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML" "-whitelist" "IdentificationRun date"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_2_out" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
FAILED: 'ratio of numbers is too large'

  input:	in1	in2
  line:	407	407
  pos/col:	65/87	65/87
 --------------------------------
  is_number:	true	true
  numbers:	1	0.754234
  is_space:	false	false
  is_letter:	false	false
  letters:	"1"	"0"
  char_codes:	49	48
 --------------------------------
  relative_max:        1.32585
  relative_acceptable: 1.01
 --------------------------------
  absolute_max:        0.245766
  absolute_acceptable: 0.01

  whitelist cases:
    "IdentificationRun date"   1x

Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_2_output.tmp   (line: 407, position/column: 65/87)
			<ProteinHit id="PH_102" accession="P01857|IGHG1_HUMAN" score="!
			                                                              1" sequence="" >

in2:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML   (line: 407, position/column: 65/87)
			<ProteinHit id="PH_102" accession="P01857|IGHG1_HUMAN" score="!
			                                                              0.754233658313751" sequence="" >


Easy Access:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_2_output.tmp:407:87:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML:407:87:

diff /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_2_output.tmp /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_2_output.idXML
FuzzyDiff took 0.01 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user).
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Failed.
"TOPP_FidoAdapter_2_out" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_2_out" time elapsed: 00:00:00
----------------------------------------------------------

1722/1785 Testing: TOPP_FidoAdapter_3
1722/1785 Test: TOPP_FidoAdapter_3
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FidoAdapter" "-test" "-in" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_input.idXML" "-out" "FidoAdapter_3_output.tmp" "-fidocp_executable" "/home/dhyduke/usr/local/bin/FidoChooseParameters" "-group_level" "-all_PSMs"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_3" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
Reading input data...
Generating temporary files for Fido...
Warning: Scores of peptide hits seem to be posterior error probabilities. Converting to (positive) posterior probabilities.
Running Fido with parameter estimation...
Fido parameter search:
Using best gamma, alpha, beta = 0.1 0.25 0.05
Parsing Fido results and writing output...
Inferred 1516 proteins in 1376 groups (0 proteins with probability zero).
Removing temporary files...
FidoAdapter took 1.58 s (wall), 0.37 s (CPU), 0.00 s (system), 0.37 s (user).
<end of output>
Test time =   1.63 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_3" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_3" time elapsed: 00:00:01
----------------------------------------------------------

1723/1785 Testing: TOPP_FidoAdapter_3_out
1723/1785 Test: TOPP_FidoAdapter_3_out
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FuzzyDiff" "-ini" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_3_output.tmp" "-in2" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_3_output.idXML" "-whitelist" "IdentificationRun date"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_3_out" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
FAILED: 'ratio of numbers is too large'

  input:	in1	in2
  line:	8	8
  pos/col:	63/85	63/85
 --------------------------------
  is_number:	true	true
  numbers:	0.267805	0.646024
  is_space:	false	false
  is_letter:	false	false
  letters:	"0"	"0"
  char_codes:	48	48
 --------------------------------
  relative_max:        2.41229
  relative_acceptable: 1.01
 --------------------------------
  absolute_max:        0.378219
  absolute_acceptable: 0.01

  whitelist cases:
    "IdentificationRun date"   1x

Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_3_output.tmp   (line: 8, position/column: 63/85)
			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
			                                                            0.267805308103561" sequence="" >

in2:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_3_output.idXML   (line: 8, position/column: 63/85)
			<ProteinHit id="PH_0" accession="A0FGR8|ESYT2_HUMAN" score="!
			                                                            0.646024286746979" sequence="" >


Easy Access:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_3_output.tmp:8:85:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_3_output.idXML:8:85:

diff /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_3_output.tmp /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_3_output.idXML
FuzzyDiff took 0.00 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).
<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Failed.
"TOPP_FidoAdapter_3_out" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_3_out" time elapsed: 00:00:00
----------------------------------------------------------

1724/1785 Testing: TOPP_FidoAdapter_4
1724/1785 Test: TOPP_FidoAdapter_4
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FidoAdapter" "-test" "-in" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_4_input.idXML" "-out" "FidoAdapter_4_output.tmp" "-fidocp_executable" "/home/dhyduke/usr/local/bin/FidoChooseParameters"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_4" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
Reading input data...
Protein identification run 1:
Generating temporary files for Fido...
Running Fido with parameter estimation...
Fido parameter search:
Warning: There are not enough false positives; needed 50 and was only given 33 (will proceed using largest available value)
Using best gamma, alpha, beta = 0.7 0.01 0
Parsing Fido results and writing output...
Inferred 146 proteins in 104 groups (0 proteins with probability zero).
Removing temporary files...
FidoAdapter took 0.41 s (wall), 0.28 s (CPU), 0.00 s (system), 0.28 s (user).
<end of output>
Test time =   0.46 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_4" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_4" time elapsed: 00:00:00
----------------------------------------------------------

1725/1785 Testing: TOPP_FidoAdapter_4_out
1725/1785 Test: TOPP_FidoAdapter_4_out
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FuzzyDiff" "-ini" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_4_output.tmp" "-in2" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML" "-whitelist" "IdentificationRun date"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_4_out" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
FAILED: 'ratio of numbers is too large'

  input:	in1	in2
  line:	13	13
  pos/col:	66/88	66/88
 --------------------------------
  is_number:	true	true
  numbers:	0.72378	0.763314
  is_space:	false	false
  is_letter:	false	false
  letters:	"0"	"0"
  char_codes:	48	48
 --------------------------------
  relative_max:        1.05462
  relative_acceptable: 1.01
 --------------------------------
  absolute_max:        0.0395343
  absolute_acceptable: 0.01

  whitelist cases:
    "IdentificationRun date"   1x

Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_4_output.tmp   (line: 13, position/column: 66/88)
			<ProteinHit id="PH_1" accession="sp|A6NJY1|SL9P1_HUMAN" score="!
			                                                               0.723779797554016" sequence="" >

in2:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML   (line: 13, position/column: 66/88)
			<ProteinHit id="PH_1" accession="sp|A6NJY1|SL9P1_HUMAN" score="!
			                                                               0.763314068317413" sequence="" >


Easy Access:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_4_output.tmp:13:88:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML:13:88:

diff /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_4_output.tmp /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_4_output.idXML
FuzzyDiff took 0.00 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user).
<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Failed.
"TOPP_FidoAdapter_4_out" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_4_out" time elapsed: 00:00:00
----------------------------------------------------------

1726/1785 Testing: TOPP_FidoAdapter_5
1726/1785 Test: TOPP_FidoAdapter_5
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FidoAdapter" "-test" "-greedy_group_resolution" "-in" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_5_input.idXML" "-out" "FidoAdapter_5_output.tmp" "-fidocp_executable" "/home/dhyduke/usr/local/bin/FidoChooseParameters"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_5" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
Reading input data...
Protein identification run 1:
Generating temporary files for Fido...
Running Fido with parameter estimation...
Fido parameter search:
Warning: There are not enough false positives; needed 50 and was only given 1 (will proceed using largest available value)
Using best gamma, alpha, beta = 0.9 0.36 0
Parsing Fido results and writing output...
Inferred 7 proteins in 5 groups (0 proteins with probability zero).
Resolving ambiguity groups greedily on Fido output...
Removing temporary files...
FidoAdapter took 0.01 s (wall), 0.00 s (CPU), 0.00 s (system), 0.00 s (user).
<end of output>
Test time =   0.05 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_5" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_5" time elapsed: 00:00:00
----------------------------------------------------------

1727/1785 Testing: TOPP_FidoAdapter_5_out
1727/1785 Test: TOPP_FidoAdapter_5_out
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FuzzyDiff" "-ini" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_5_output.tmp" "-in2" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_5_output.idXML" "-whitelist" "IdentificationRun date"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_5_out" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
FuzzyDiff took 0.00 s (wall), 0.01 s (CPU), 0.00 s (system), 0.01 s (user).
<end of output>
Test time =   0.04 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_5_out" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_5_out" time elapsed: 00:00:00
----------------------------------------------------------

1728/1785 Testing: TOPP_FidoAdapter_6
1728/1785 Test: TOPP_FidoAdapter_6
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FidoAdapter" "-test" "-in" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_input.idXML" "-out" "FidoAdapter_6_output.tmp" "-fido_executable" "/home/dhyduke/usr/local/bin/Fido" "-prob:protein" "0.9" "-prob:peptide" "0.01" "-prob:spurious" "0.0"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_6" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
Reading input data...
Generating temporary files for Fido...
Warning: Scores of peptide hits seem to be posterior error probabilities. Converting to (positive) posterior probabilities.
Running Fido with fixed parameters...
Parsing Fido results and writing output...
Inferred 1516 proteins in 1376 groups (0 proteins with probability zero).
Removing temporary files...
FidoAdapter took 0.82 s (wall), 0.38 s (CPU), 0.00 s (system), 0.38 s (user).
<end of output>
Test time =   0.85 sec
----------------------------------------------------------
Test Passed.
"TOPP_FidoAdapter_6" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_6" time elapsed: 00:00:00
----------------------------------------------------------

1729/1785 Testing: TOPP_FidoAdapter_6_out
1729/1785 Test: TOPP_FidoAdapter_6_out
Command: "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/bin/FuzzyDiff" "-ini" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/FuzzyDiff.ini" "-in1" "FidoAdapter_6_output.tmp" "-in2" "/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML" "-whitelist" "IdentificationRun date"
Directory: /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp
"TOPP_FidoAdapter_6_out" start time: May 26 13:42 PDT
Output:
----------------------------------------------------------
FAILED: 'ratio of numbers is too large'

  input:	in1	in2
  line:	980	980
  pos/col:	65/87	65/87
 --------------------------------
  is_number:	true	true
  numbers:	1	0.920273
  is_space:	false	false
  is_letter:	false	false
  letters:	"1"	"0"
  char_codes:	49	48
 --------------------------------
  relative_max:        1.08663
  relative_acceptable: 1.01
 --------------------------------
  absolute_max:        0.0797275
  absolute_acceptable: 0.01

  whitelist cases:
    "IdentificationRun date"   1x

Offending lines:			(tab_width = 8, first_column = 1)

in1:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_6_output.tmp   (line: 980, position/column: 65/87)
			<ProteinHit id="PH_243" accession="P01857|IGHG1_HUMAN" score="!
			                                                              1" sequence="" >

in2:  /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML   (line: 980, position/column: 65/87)
			<ProteinHit id="PH_243" accession="P01857|IGHG1_HUMAN" score="!
			                                                              0.920272529125214" sequence="" >


Easy Access:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_6_output.tmp:980:87:
/home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML:980:87:

diff /home/dhyduke/usr/local/src/proteomics/openms/OpenMS-build/src/tests/topp/FidoAdapter_6_output.tmp /home/dhyduke/usr/local/src/proteomics/openms/OpenMS/src/tests/topp/THIRDPARTY/FidoAdapter_1_output.idXML
FuzzyDiff took 0.03 s (wall), 0.03 s (CPU), 0.00 s (system), 0.03 s (user).
<end of output>
Test time =   0.06 sec
----------------------------------------------------------
Test Failed.
"TOPP_FidoAdapter_6_out" end time: May 26 13:42 PDT
"TOPP_FidoAdapter_6_out" time elapsed: 00:00:00
----------------------------------------------------------

**Comment by hendrikweisser** [comment] 2015-05-27 15:35
@danielhyduke:
Your problems are (at least partially) due to errors in a recent merge that apparently haven't been fixed yet: https://github.com/OpenMS/OpenMS/pull/1358#issuecomment-101726804

@jpfeuffer:
Could you check what happened there, please?

**Comment by sagitter** [comment] 2015-05-27 19:09
>Can you try building Fido from here: https://github.com/hendrikweisser/Fido
That is the version that we used for the OpenMS tests.

With your Fido version, tests works: https://copr-be.cloud.fedoraproject.org/results/sagitter/Fido-pi/fedora-rawhide-x86_64/openms-2.0.0-13.fc21/build.log.gz

**Comment by jpfeuffer** [comment] 2015-05-29 10:34
I linked a PR for a fix for the tests.
Now they certainly run through on my MacOS 10.10.2 (64bit) and a 64 bit Linux of our group.
No segfaults, no fails.

**Comment by hendrikweisser** [comment] 2015-05-29 10:41
Thank you, Julianus!
Just to clarify: The differences in the test results are caused by the switch to unmodified peptides?

**Comment by jpfeuffer** [comment] 2015-05-29 10:57
Yes. That means, that the "unmodifiying" procedures between Fido and OpenMS indeed differ and peptides are collapsed in one when they aren't in the other.
We could check the Fido procedure more deeply but I guess OpenMS should deal with the OpenMS format of modifications like it is now.

**Closed** 2015-05-29 11:20 UTC
