### ISSUE TITLE
protein groups in text exporter output

### ISSUE THREAD

**Issue by ursker** [OpenMS/OpenMS#1316] opened 2015-03-19 09:03 UTC
I would only use Open MS to analyze my data if the protein groups are not kicked out. Otherwise I fear to loose too many bilogically relevant information. Is it possible to include protein groups from Fido in the text exporter output?

**Comment by lars20070** [comment] 2015-04-08 11:26
Reading the Fido paper again [1], it seems that the Fido algorithm only scores and ranks proteins. It does not construct protein groups. Proteins in the same line of the output [2] have the same score, but do not necessarily form a "protein group".

If that's correct, what does the option -g "uses protein group level inference" exactly do?

[1] Serang et al. J Proteome Res, 2010 vol. 9 (10) p. 5346
[2] https://noble.gs.washington.edu/proj/fido/

**Comment by lars20070** [comment] 2015-04-08 11:29
Without protein groups, the Occam protein quantification #1210 will not be possible.

**Comment by jpfeuffer** [comment] 2015-04-08 12:37
@lars20070 
You are partly right. According to the paper, Fido only groups proteins that are indistinguishable with the observed data (PSMs).
At first, this is for saving computations. Second, it's just logical that those will get the same probability.
However, I can't answer the second question right now. From a toy example that I created it does not change or extend the grouping itself but only changes the scoring of the groups.

**Comment by jpfeuffer** [comment] 2015-04-08 12:40
You are also right, that without grouping, Occam quantification won't be possible.
However, an easy solution would be to use the ranking that Fido introduces to greedily resolve the groups e.g. take the best protein from a group with all its evidence, remove it and continue distributing the remaining PSMs. Thereby one could "force" a grouping that on the basis of the Fido probabilities might make more sense than the usual Occam approach (not perfectly sure about that right now).

**Comment by lars20070** [comment] 2015-04-08 13:18
@jpfeuffer I like the greedy approach. Hope I understand your suggested algorithm.

(1) Quantify protein with highest Fido score.
(2) Remove all peptide fold changes used in (1) and the protein.
(3) repeat (1)

In the end, all peptide quantifications are used but not all proteins quantified. A protein quantification between "unique only" and "all" but without the use of any groups.

**Comment by lars20070** [comment] 2015-04-14 10:59
@jpfeuffer We discussed that protein groups are not explicitly reported by Fido. But you mentioned that they are implicitly given. - Fido reports the peptide/protein mappings. Let's call two proteins connected if they share a mapping to the same peptide. All connected proteins then form a protein group, and these groups are disjunct. Is this your "implicit" definition?

I think we should report these groups and the sets of indistinguishable proteins.

**Comment by jpfeuffer** [comment] 2015-04-14 13:00
@lars20070 Exactly! That's what I meant. While I am greedily resolving the "groups aka connected components" I can try to store them in the other "group data structure" that we have (accessible via getProteinGroups, instead of getIndistinguishableProteinGroups).
Then both should be available for outputting.

**Comment by lars20070** [comment] 2015-04-14 21:10
Here an example. Guess that is what both of us had in mind. - Do we really want A and B in the same group? We know for sure that both are present due to the unique peptides 1 and 2.
![screen shot 2015-04-14 at 22 59 26](https://cloud.githubusercontent.com/assets/6149805/7147378/d7629918-e2fa-11e4-950c-24b27744ae7e.png)

**Comment by jpfeuffer** [comment] 2015-04-15 08:42
I see that it might not be favorable. The problem is: In which group would you put C in then? Group of A or group of B? Or both (which would make the groups non-disjunct)?

**Comment by lars20070** [comment] 2015-04-15 08:56
@jpfeuffer I think our definition of protein group is fine (for the start). Let's report report these groups. Then @ursker and our group will do some testing and come back to you if we want changes.

**Comment by lars20070** [comment] 2015-06-19 19:49
Resolved by #1358 and #1457.

**Closed by lars20070** 2015-06-19 19:49 UTC
