### ISSUE TITLE
TOPPAS ERROR: PeptideIndexer failed!

### ISSUE THREAD

**Issue by petercim** [OpenMS/OpenMS#2125] opened 2016-08-19 22:58 UTC
Hi,
As a new user of OpenMS/TOPP, I started with running the example pipelines. I encountered some problems with Ecoli_Identification.toppas workflow (see log below). Any ideas what's going wrong? One modification I made to the existing example toppas pipeline is to change OMSSAAdapter for XtandemAdapter.

Thanks!

============= log output ===================
While loading '/opt/OpenMS/2.0.1/share/OpenMS/examples/ID/Ecoli_MS2_small.mzML': Name of CV term not correct: 'MS:1000615 - ProteoWizard' should be 'ProteoWizard software'
While storing '/tmp/2016-08-19_225214_e29b608be951_205_1/_tandem_input_file.mzData': Cannot find value '19' needed to write CV term 'InletType' with accession '1000007'.
While storing '/tmp/2016-08-19_225214_e29b608be951_205_1/_tandem_input_file.mzData': Cannot find value '20' needed to write CV term 'IonizationType' with accession '1000008'.
While storing '/tmp/2016-08-19_225214_e29b608be951_205_1/_tandem_input_file.mzData': Cannot find value '13' needed to write CV term 'AnalyzerType' with accession '1000010'.
While storing '/tmp/2016-08-19_225214_e29b608be951_205_1/_tandem_input_file.mzData': Cannot find value '20' needed to write CV term 'DetectorType' with accession '1000026'.

X! TANDEM Vengeance (2015.12.15.2)

Loading spectra
Failed to open: ""
 (mzData). loaded.
Spectra matching criteria = 137
Starting threads . started.
Computing models:
    .........   sequences modelled = 8 ks
Model refinement:
Creating report:
    initial calculations  ..... done.
    sorting  ..... done.
    finding repeats ..... done.
    evaluating results ..... done.
    calculating expectations ..... done.
    writing results ..... done.

Valid models = 64

Set debug level to >=2 to keep the temporary files at '/tmp/2016-08-19_225214_e29b608be951_205_1/'
Statistics:
  identified MS2 spectra: 117 / 139 = 84% (with e-value < 0.1)
XTandemAdapter took 0.39 s (wall), 0.14 s (CPU), 0.00 s (system), 0.14 s (user).
# 

22:52:15 NOTICE: PeptideIndexer of node #4 started. Processing ...
Unknown (or deprecated) Parameter 'in' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'fasta' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'out' given in old parameter file! Ignoring ...
Overriding Default-Parameter 'decoy_string' with new value 'rev_'!
Overriding Default-Parameter 'prefix' with new value 'true'!
Overriding Default-Parameter 'log' with new value 'TOPP.log'!
Unknown (or deprecated) Parameter 'threads' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'no_progress' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'force' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'test' given in old parameter file! Ignoring ...
Unknown (or deprecated) Parameter 'ini' given in old parameter file! Ignoring ...
Mapping 117 peptides to 8272 proteins.
Aho-Corasick done. Found 122 hits in 115 of 117 peptides (time: 0.030208 s (wall), 0.03 s (CPU)).
Using suffix array to find ambiguous matches...
... for 2 unmatched peptide(s)...
... in all 8272 protein(s).
Peptide hits passing enzyme filter: 122
     ... rejected by enzyme filter: 4
Unmatched peptide: (Acetyl)AQINNIRPEFDR
Unmatched peptide: DDAMLWEGLQQAQKDD
Statistics of peptides (target/decoy):
  match to target DB only: 102
  match to decoy DB only : 13
  match to both          : 0
Statistics of peptides (mapping to proteins):
  no match (to 0 protein)         : 2
  unique match (to 1 protein)     : 108
  non-unique match (to >1 protein): 7
PeptideIndexer found unmatched peptides, which could not be associated to a protein.
Potential solutions:
- check your FASTA database for completeness
- set 'enzyme:specificity' to match the identification parameters of the search engine
- some engines (e.g. X! Tandem) employ loose cutting rules generating non-tryptic peptides;
   if you trust them, disable enzyme specificity
- increase 'aaa_max' to allow more ambiguous amino acids
- as a last resort: use the 'allow_unmatched' option to accept unmatched peptides
   (note that unmatched peptides cannot be used for FDR calculation or quantification)
  Result files were written, but PeptideIndexer will exit with an error code.
  Statistics of proteins:
  new proteins: 96
  orphaned proteins: 97 (all removed)
  PeptideIndexer took 0.18 s (wall), 0.18 s (CPU), 0.00 s (system), 0.18 s (user).
# 

22:52:15 ERROR: PeptideIndexer failed!

**Comment by cbielow** [comment] 2016-08-22 08:55
Hey Peter,

did the default pipeline run through?
The warnings from your modified pipeline seems to indicate some weird 
edge/node configuration. Could you please open a ticket
at
https://github.com/OpenMS/OpenMS/issues
and attach the modified pipeline, along with some information on your 
OpenMS version and operating system. Thanks.

cheers
Chris

Am 8/20/2016 um 12:58 AM schrieb petercim:

**Comment by petercim** [comment] 2016-08-22 18:19
Thanks, Chris! Will open a new issue.

**Comment by hendrikweisser** [comment] 2016-08-23 10:29
@petercim: You should also have a look whether the two missed peptides ("AQINNIRPEFDR" and "DDAMLWEGLQQAQKDD") occur in the FASTA database.

**Comment by cbielow** [comment] 2016-08-23 11:24
could you please attach your pipeline + input files (unless they are identical to the example pipeline)

**Comment by cbielow** [comment] 2016-08-23 11:25
my guess is that xtandem reports semi-tryptic peptides, so you need to loosen the peptideindexer settings accordingly. But the warnings about nodes/edges in the pipeline are still a bit confusing to me.

**Comment by cbielow** [comment] 2016-08-23 11:30
ok, so

```
>VIMSS14472 prpD 2-methylcitrate dehydratase (NCBI) [Escherichia coli K12]
MS*AQINNIRP*EFD
```
i.e. xtandem searches with n-terminal cleaved AA's
```
>rev_VIMSS16372 menF isochorismate hydroxymutase 2, menaquinone biosynthesis (VIMSS) [Escherichia coli K12]
NERQNK*DDAMLWEGLQQAQKDD*PN
```
this one is a bit more tricky -- i dont know why xtandem would find this one. its semi-trypic, but the c-terminal cleavage site looks weird.

**Comment by cbielow** [comment] 2017-01-23 08:43
closing this. Feel free to re-open if the problem is not solved.

**Closed by cbielow** 2017-01-23 08:43 UTC
