### ISSUE TITLE
ConsensusXML contains UNKNOWN Maps

### ISSUE THREAD

**Issue by Leon-Bichmann** [OpenMS/OpenMS#4146] opened 2019-06-10 10:46 UTC
Hi,
When using FeatureFinderIdentification and after that FeatureLinkerUnlabelledKD, the resulting ConsensusXML does not correctly annotate which original file corresponds to the individual maps:
```
#MAP	id	filename	label	size
MAP	0	UNKNOWN		4102
MAP	1	UNKNOWN		4714
MAP	2	UNKNOWN		4695
...
```

It would be important for users of my workflow to know which map corresponds to which original featureXML filename...

Any idea how to fix this?

**Comment by timosachsenberg** [comment] 2019-06-11 06:31
duplicate of https://github.com/OpenMS/OpenMS/issues/3683

**Closed by timosachsenberg** 2019-06-11 06:31 UTC
