### ISSUE TITLE
Constants.py missing in pyopenms pip installer

### ISSUE THREAD

**Issue by JeeH-K** [OpenMS/OpenMS#4293] opened 2019-10-10 15:40 UTC
pyopenms through pip installer didn't include Constants.py, so I had to copy the file from OpenMS/src/pyOpenMS/pyopenms. Maybe a bug?

**Comment by hroest** [comment] 2019-10-10 16:23
yes, this seems like a bug, sorry about that

**Comment by timosachsenberg** [comment] 2019-10-24 09:03
does this need to be fixed in our build scripts?

**Comment by jpfeuffer** [comment] 2019-10-24 10:19
Probably. Where does it have to go in the pip package?

**Comment by timosachsenberg** [comment] 2019-10-24 10:36
maybe the setup.py script? https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/setup.py

**Comment by jpfeuffer** [comment] 2019-10-24 12:31
yes probably but what needs to be the location in the end?

**Comment by poshul** [comment] 2019-11-18 11:28
@JeeH-K where is Constants.py supposed to be in the installed package?

**Comment by JeeH-K** [comment] 2019-11-18 11:58
Where the setup.py file is located is fine as the file, [https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pyopenms/Constants.py](https://github.com/OpenMS/OpenMS/blob/develop/src/pyOpenMS/pyopenms/Constants.py).

**Comment by hroest** [comment] 2019-11-19 01:42
yes, it should be in the main folder and should get imported here

https://github.com/OpenMS/OpenMS/blob/f531f2fda5833ce1be284c50e798a0b999c0528d/src/pyOpenMS/pyopenms/python_extras.py#L1

**Comment by poshul** [comment] 2019-11-19 15:01
I can confirm that the current pip egg doesn't have Constants.py, and that building the egg myself results in a product that does include Constants.py. Where does the pip version come from?

**Comment by timosachsenberg** [comment] 2019-11-19 15:21
Ok so this seems to be fixed? Or does something unexpected happen on the build machines for pip?

**Comment by timosachsenberg** [comment] 2019-11-25 09:04
@hroest I will close this as fixed. Feel free to reopen if you think this is still an issue.

**Closed by timosachsenberg** 2019-11-25 09:04 UTC
Labels: critical, pyOpenMS
