### ISSUE TITLE
instrument settings in MSGFplusAdapter

### ISSUE THREAD

**Issue by lars20070** [OpenMS/OpenMS#1409] opened 2015-05-08 11:49 UTC
Despite choosing the setting instrument = low_res the Q Exactive settings are used by MSGF+, see screenshot.

![msgfplusadapter](https://cloud.githubusercontent.com/assets/6149805/7535756/f9808596-f588-11e4-9d66-d5b1742fbb70.png)

**Comment by cbielow** [comment] 2015-05-08 14:21
adapter problem or MSGF problem?

**Comment by oliverschilling** [comment] 2015-05-08 21:13
when running msg from the command line, I don't ge this message...

**Comment by lars20070** [comment] 2015-05-15 08:36
In the temp folder one can only intercept msgfplus_mod.txt which in specifies the mods correctly. The remaining parameters are passed as options directly on the command line.

**Comment by lars20070** [comment] 2015-05-15 08:45
The MSGF+ output reports

Search Parameters: Instrument: LowRes

So I guess the adapter is passing on the setting correctly. But MSGF+ also reports

Loading build-in param file: HCD_QExactive_Tryp.param

Are LowRes or QExactive params used? @hendrikweisser do we need to worry about the QExactive message?

**Comment by lars20070** [comment] 2015-05-15 10:06
With 200 ppm precursor mass tolerance and instrument = LowRes, the MSGF+ search of 3899 MS2 spectra results in just three peptide identifications.

**Comment by hendrikweisser** [comment] 2015-05-15 11:09
I think the parameter should be passed on correctly by the adapter:
1. https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L115
2. https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L453
3. https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L478

I can't comment on what MS-GF+ does internally and whether it might have a bug there.

**Comment by lars20070** [comment] 2015-05-15 13:29
@hendrikweisser We did run MSGFplus a couple of times from the command line. The message

Loading build-in param file: HCD_QExactive_Tryp.param

never turns up. The message clearly comes from MSGFplus.

**Comment by hendrikweisser** [comment] 2015-05-15 14:31
Can you add a debug output for the parameters used for the MS-GF+ call in the adapter (variable "process_params", https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp#L501), and see how that differs from your manual call?

**Comment by lars20070** [comment] 2015-05-15 17:47
@hendrikweisser I did run the same toppas workflow on Linux (in order to check the proposed debug output). The MSGF+ message does not appear.

Loading build-in param file: HCD_QExactive_Tryp.param

Under Windows the above message appears always, QExactive or LowRes setting. In the case of LowRes data the settings from the adapter seem to be overridden and we get only a handful of hits.

**Comment by lars20070** [comment] 2015-05-19 11:51
@hendrikweisser I did run MSGF+ on the low-res Q Star data (-t 200ppm -inst 0) [1]. Looks fine, plenty of peptide hits. IDFileConverter produces idXML with 2,671 peptide hits. But it's not possible to open the idXML in TOPPView.

2445 peptide identification(s) without sequence and/or retention time information were removed.
0 peptide identification(s) remaining.

Guess this is a mzid to idXML file conversion bug. That might be the reason we see no peptide IDs from MSGFplusAdapter on Q Star data.

[1] https://www.dropbox.com/sh/p5iejarad5812ki/AABiT1CdfzeUjTSx8RIZc8wRa

**Comment by hendrikweisser** [comment] 2015-05-19 12:37
> I did run MSGF+ on the low-res Q Star data (-t 200ppm -inst 0) [1].

Did you run MS-GF+ by itself or via MSGFPlusAdapter?

> But it's not possible to open the idXML in TOPPView.

The reason is that the retention times are missing. In mzid, retention times are stored as "cvParam" elements in "SpectrumIdentificationResult":
`<cvParam accession="MS:1000894" cvRef="PSI-MS" name="retention time" value="5432.1"/>`

This information is missing in your file. I don't know why that's the case.

> Guess this is a mzid to idXML file conversion bug.

No, the information isn't there in the first place.

**Comment by lars20070** [comment] 2015-05-19 14:12
@hendrikweisser I did run MSGF+ by itself from the command line. Thanks for the info.
Guess either MSGF+ or msconvert is the problem. The Q Star machine is pretty old..

**Comment by Stortebecker** [comment] 2015-05-21 12:39
@hendrikweisser I have the same problem with Orbitrap XL data. Also here, the retention times are already missing in the mzid files. I ran MSGF+ from commandline.

**Comment by hendrikweisser** [comment] 2015-05-21 12:51
@lars20070, @Stortebecker: Did you use mzML as input for your MS-GF+ runs? Do the input files contain retention time information, e.g.:
```
<scan>
    <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="2655.095703125" unitAccession="UO:0000010" unitName="second" unitCvRef="UO" />
...
```

**Comment by lars20070** [comment] 2015-05-21 13:11
@hendrikweisser Yes. We used mzML input.

Could it be that the retention time is optional in the mzIdentML format, and MSGF+ simply never writes it?

**Comment by hendrikweisser** [comment] 2015-05-21 13:24
> Could it be that the retention time is optional in the mzIdentML format, and MSGF+ simply never writes it?

Oh, yes, you are right. I thought RT must be included since we get it from the adapter, but there we actually have to look it up in the mzML file (which I forgot about).

**Comment by lars20070** [comment] 2015-05-21 13:28
But mzid + mzML -> idXML in IDFileConverter is not supported yet. Right? We just tested it.

**Comment by hendrikweisser** [comment] 2015-05-21 13:36
> But mzid + mzML -> idXML in IDFileConverter is not supported yet.

Nope. It would be easy to add, because the code is already in MSGFPlusAdapter (should really be factored out into a library function somewhere, though).

**Comment by lars20070** [comment] 2015-05-21 14:49
Just as reference, the command line options used by the adapter during the Q Star search.

java -Xmx3500m -jar /home/lars/Desktop/MSGFplus_Lars/MSGFPlus.jar -s example.mzML -o /tmp/2015-05-21_164657_LinuxSchilling_20055_1/msgfplus_output.mzid -d uniprot-koli-k12-nov24-2011-plus-shuffled.fasta -t 200ppm -ti 0,1 -tda 0 -m 0 -inst 0 -e 5 -protocol 0 -ntt 1 -minLength 7 -maxLength 50 -minCharge 2 -maxCharge 4 -n 1 -addFeatures 0 -thread 1 -mod /tmp/2015-05-21_164657_LinuxSchilling_20055_1/msgfplus_mods.txt

**Comment by lars20070** [comment] 2015-05-21 15:17
@hendrikweisser Straight out of the search engine the number of PeptideIdentifications and PeptideHits should be identical. Right? For example, FileInfo delivers

spectra:                    2567
peptide hits:               2567

But the idXML straight out of the MSGFPlusAdapter has

spectra:                    3
peptide hits:               3512

How is this possible?

**Comment by lars20070** [comment] 2015-05-22 11:41
@hendrikweisser I opened the mzid from the command line in ProteoIDViewer. Together with the source mzML. 3512 peptide hits. Looks fine. The idXML from the MSGFPlusAdapter shows only 3 peptides when opened in TOPPView.

**Comment by lars20070** [comment] 2015-05-22 11:59
In fixed-mod MSGF+ searches of Q Exactive data, we see that PSMs overlap. One and the same spectrum gets a hit from the light, medium and heavy search. Without #1437 it is not possible to compare the search results from the adapter with the command-line results in TOPPView.
![overlaps](https://cloud.githubusercontent.com/assets/6149805/7770089/b0055d62-008a-11e5-9ac6-52ad47df76b2.png)

**Comment by hendrikweisser** [comment] 2015-05-22 12:06
> Without #1437 it is not possible to compare the search results from the adapter with the command-line results in TOPPView.

Why not just compare the output files (e.g. by opening them side by side)? You don't need TOPPView for that. You can also export them to CSV with TextExporter and run some statistics on them.

**Comment by lars20070** [comment] 2015-05-22 12:16
I did. 3 < 3512. The results are not the same.

**Comment by hendrikweisser** [comment] 2015-05-22 12:18
What happens when you compare the mzid from the adapter to the mzid from the command line?

**Comment by oliverschilling** [comment] 2015-05-22 12:43
Dear all, this topic seems to develop into a heated debate...msgf+ is a very powerful search engine. it would be shame if some glitches prevent its full usage within OpenMS. @hendrikweisser: if I understand correctly, you are the expert for the msgf+ adapter. Could you please take a look into the discrepancy between spectra and peptide hits? Thanks ! Oliver

**Comment by hendrikweisser** [comment] 2015-05-22 12:54
@oliverschilling:
> Could you please take a look into the discrepancy between spectra and peptide hits?

I don't want to say "no", but I'm currently busy with other things. If you don't want to wait until I have more time for this, then you/Lars will have to do some of the digging. As a first step, please compare the mzid files, to find whether the problem is with how MS-GF+ is run in the adapter or with the conversion of mzid to idXML.

**Comment by lars20070** [comment] 2015-05-22 13:17
The mzid are identical since both are generated by the same command line, see above. It seems the bug is in the conversion of the search result.

**Comment by hendrikweisser** [comment] 2015-05-22 15:12
> The mzid are identical since both are generated by the same command line, see above.

Okay. When you convert the mzid from MS-GF+ (command line) with IDFileConverter, do you get the "correct" idXML (just without RT information)?

**Comment by hendrikweisser** [comment] 2015-05-22 15:38
Lars, could you also run the MSGFPlusAdapter with "-debug 2"? We'd need to check the intermediate file "msgfplus_converted.tsv" that gets created in the temporary directory.

**Comment by lars20070** [comment] 2015-05-23 15:37
@hendrikweisser As suggested, I intercepted the java command line (looks good) from the adapter, executed MSGFPlus from the command line, followed by IDFileConverter and FileInfo.

-- General information --

File name: OS_CP10_P290115_260315_centroided_fromCommanLine.idXML
File type: idXML
Number of:
  runs:                       1
  protein hits:               2609
  non-redundant protein hits: 2609
  (only hits that differ in the accession)

  spectra:                    3300
  peptide hits:               3536
  modified top-hits:          3300/3300 (100%)
  non-redundant peptide hits: 3448
  (only hits that differ in sequence and/ or modifications)
  Modifications (top-hits only): Carbamidomethyl(628), Dimethyl(2919)

On the other hand, the MSGFPlusAdapter followed by FileInfo results in this.

-- General information --

File name: OS_CP10_P290115_260315_centroided_fromMSGFPlusAdapter.idXML
File type: idXML
Number of:
  runs:                       1
  protein hits:               2609
  non-redundant protein hits: 2609
  (only hits that differ in the accession)

  spectra:                    3
  peptide hits:               3500
  modified top-hits:          3/3 (100%)
  non-redundant peptide hits: 3448
  (only hits that differ in sequence and/ or modifications)
  Modifications (top-hits only): Dimethyl(1)

**Comment by lars20070** [comment] 2015-05-23 15:47
Protein hits and non-redundant peptide hits are correct.
Spectra (PeptideIdentifications) and peptide hits are not correct.

Checking the tsv and going through your 'create idXML output' code will be the next step.

**Comment by lars20070** [comment] 2015-05-23 16:03
MSGF+ returns mzid. It seems IDFileConverter and MSGFPlusAdapter are not using the same (refactored) code for the mzid -> idXML conversion. Why not?

**Comment by mwalzer** [comment] 2015-05-25 16:24
brief answers: 
mzid - rt attribute: optional -> use RTAnnotator (UTILS)
MSGFPlus adapter is actually (only a litle bit) older than that, I'd consider the tsv reading part of MSGFPlusAdapter deprecated.

**Comment by lars20070** [comment] 2015-05-25 16:37
Thanks @mwalzer! I did not know about the RTAnnotator util.

**Comment by hendrikweisser** [comment] 2015-05-26 08:47
> I did not know about the RTAnnotator util.

Me neither. I would like to have this functionality (also?) in IDFileConverter, since that's where it is for the other search engine formats. I'd be in favour of reopening #1437.

> remove MSGFPlusAdapter tsv part and leave the output with the natively written mzid.

I agree that the TSV part should be removed now that the mzid conversion is more mature. However, MSGFPlusAdapter should still produce an idXML (if required, and including RT information) to be in line with the other adapters.

**Comment by lars20070** [comment] 2015-05-26 08:55
Note that there are still some issues with the mzid -> idXML conversion https://github.com/OpenMS/OpenMS/issues/1446. Simply the rank does not appear to be correct.

**Comment by timosachsenberg** [comment] 2015-07-22 11:28
so what we need to do:
1. use IDFileConverter code in MSGFPlusAdapter to convert mzid to idXML
2. use RTAnnotator code to annotate RT
and check if this code can be factored out of the tools and reused

**Comment by timosachsenberg** [comment] 2015-07-22 11:30
what is not clear to me:
- why does this occur for QStar data?

**Comment by lars20070** [comment] 2015-07-22 12:31
@timosachsenberg Here two idXML from the same MS-GF+ search: once [1] MS-GF+ run from the command line then converted using IDFileConverter (i.e. mzid -> idXML). Then [2] from the MS-GF+ adapter (i.e. mzid -> tsv -> idXML).

[1] https://www.dropbox.com/s/uxv2dgl47gco0ja/OS_CP10_P290115_260315_centroided_fromCommanLine.idXML
[2] https://www.dropbox.com/s/lfpzxs3tna840fu/OS_CP10_P290115_260315_centroided_fromMSGFPlusAdapter.idXML

**Comment by timosachsenberg** [comment] 2015-07-22 12:33
drop box doesn't work for me anymore... could you please take one corresponding hit from both files and paste them here or put it in a gist.

**Comment by lars20070** [comment] 2015-07-22 12:37
Links updated. Sorry.

**Comment by lars20070** [comment] 2015-07-22 13:00
Here a peptide sequence from the `idXML` from MS-GF+ command line plus `IDFileConverter`.
```
		<PeptideIdentification score_type="MS-GF:EValue" higher_score_better="true" significance_threshold="0" MZ="414.754455566406" spectrum_reference="sample=1 period=1 cycle=2006 experiment=3" >
			<PeptideHit score="6.184501" sequence="(Dimethyl)VSAEK(Dimethyl)EK(Dimethyl)ALSLLAGR" charge="4" aa_before="E" aa_after="I" protein_refs="PH_530" >
				<UserParam type="string" name="MS:1002049" value="-14"/>
				<UserParam type="string" name="MS:1002050" value="40"/>
				<UserParam type="string" name="MS:1002052" value="2.3052996E-6"/>
				<UserParam type="string" name="MS:1002053" value="6.184501"/>
				<UserParam type="string" name="AssumedDissociationMethod" value="HCD"/>
				<UserParam type="string" name="IsotopeError" value="0"/>
				<UserParam type="float" name="calcMZ" value="414.756805419922"/>
				<UserParam type="int" name="start" value="52"/>
				<UserParam type="int" name="end" value="66"/>
				<UserParam type="string" name="target_decoy" value="target"/>
			</PeptideHit>
		</PeptideIdentification>
```

and here from the `MSGFPlusAdapter`. The `PeptideHits` are not wrapped in `PeptideIdentifications`.

```
			<PeptideHit score="2.3052996e-06" sequence="(Dimethyl)VSAEK(Dimethyl)EK(Dimethyl)ALSLLAGR" charge="4" aa_before="E" aa_after="I" protein_refs="PH_2078" >
```

**Comment by timosachsenberg** [comment] 2015-07-22 16:44
Ok there seem to be some differences:
e.g. 
```
search_engine="MSGFPlus" vs. "MSGF+"
search_engine_version="" vs. "Beta (v10089)"
missed_cleavages="0" precursor_peak_tolerance="0.133333333333333" peak_mass_tolerance="0" vs.  missed_cleavages="1000" precursor_peak_tolerance="200" peak_mass_tolerance="0"
```

**Comment by hendrikweisser** [comment] 2015-10-02 10:14
Have we actually found out what exactly causes the failure in MSGFPlusAdapter?

**Comment by ypriverol** [comment] 2016-01-21 15:41
I guess is the same issue that I have in my Mac. @hendrikweisser

**Comment by hendrikweisser** [comment] 2016-01-21 15:56
@ypriverol:
> I guess is the same issue that I have in my Mac.

This issue is about the adapter working incorrectly for some datasets, not about it *not* working at all (like #1764 and #1771). So I don't think this is the issue that you have (at least not as far as I know).

**Comment by hendrikweisser** [comment] 2016-07-27 14:35
Any updates on this issue? Has it been resolved in the meantime?

**Closed** 2019-07-03 09:31 UTC
Labels: defect, minor, wontfix
