### ISSUE TITLE
Error in IDMerger

### ISSUE THREAD

**Issue by infusini** [OpenMS/OpenMS#4740] opened 2020-05-22 12:51 UTC
Hi all,

I have been attempting to test Epifany and downloaded the example workflow for Knime.

I used the example mzMLs (iPRG2016 data B sample). After running the CometAdaptor successfully the IDMerger showed the error below:

```
ERROR IDMerger             0:6        Failing process stdout: [Warning: Parameters file version (2.4.0-HEAD-2019-01-29) does not match the version of this tool (2.5.0)., Your current parameters are still valid, but there might be new valid values or even new parameters. Upgrading the INI might be useful., Error: Unexpected internal error (the value 'Cannot convert string to peptide modification. No terminal modification matches to term specificity and origin.' was used but is not valid; .(Gln->pyro-Glu)ETMGPIPPVHPC(Carbamidomethyl)TIM(Oxidation)GIYK)]
ERROR IDMerger             0:6        Failing process stderr: []
ERROR IDMerger             0:6        Return code: 8
ERROR IDMerger             0:6        Execute failed: Failed to execute node IDMerger
```

The error comes because of the variable modification `Gln -> pyroGlu (Q)` that I added to the parameters, removing that specific modification solves the problem, but it would be good to have the ability to select it in the future. 

Thank you,

Giuseppe

**Comment by jpfeuffer** [comment] 2020-05-22 20:14
Closed as duplicate of #4741

**Closed by jpfeuffer** 2020-05-22 20:14 UTC
