### ISSUE TITLE
KNIME FidoAdapter not working with Mascot?

### ISSUE THREAD

**Issue by isaphan** [OpenMS/OpenMS#2533] opened 2017-04-20 02:49 UTC
Hello
I am unable to run the label free with protein quantification pipeline with the MascotAdapterOnline (OpenMS 2.1.0 on KNIME 3.3.2 OS X El Capitan).

Although I have IDPosteriorErrorProbability prob_correct set to true, the workflow crashes at the FidoAdapter node with the error

Failing process stderr: [Error: Unsuitable score type for peptide-spectrum matches detected (problem: lower scores are better)., Fido requires probabilities as scores, e.g. as produced by IDPosteriorErrorProbability with the 'prob_correct' option.]

**Comment by jpfeuffer** [comment] 2017-04-20 10:09
Hi,

interesting. Was IDPep the last step before FidoAdapter? Or did you perform e.g. FDR calculation afterwards. I am asking because that would change the main score of each PSM.

**Comment by isaphan** [comment] 2017-04-20 17:59
The pipeline has an FDR node after IDPep, followed by IDMerger before FIdoAdapter.

**Comment by jpfeuffer** [comment] 2017-04-20 18:02
Ok so then the score is overwritten by the FDR calculation. You can use the IDScoreSwitcher to make the PosteriorProbability the main score again.

**Comment by isaphan** [comment] 2017-04-20 18:13
OK. Can you confirm I got the parameters for IDScoreSwitcher  right (MS newbie here):
-new_score "Posterior Probability_score"
-new_score_orientation "'higher_better'"

**Comment by jpfeuffer** [comment] 2017-04-21 08:21
That seems about right. If it works it was probably correct :)

**Comment by isaphan** [comment] 2017-04-21 18:21
It never worked: it ran, but gave nonsensical results. The XML identification files that are saved after IDFilter somehow no longer include "Posterior Probability_score" in the UserParam list. They only contain target_decoy and description after IDFilter. Makes no sense to me.

**Comment by jpfeuffer** [comment] 2017-04-21 19:58
Hmm.. that would be bad and should not be the case.
Can you somehow upload the idXML before the IDFilter step and the configuration of your IDFilter, so I can reproduce the problem?

**Comment by isaphan** [comment] 2017-04-24 17:49
my bad, the Posterior Probability_score is there for non-decoy hits. My problem is that the strongest Mascot hit does not appear with a high score, let alone in the final protein quantification output. I am analyzing a TAP pulldown experiment and my bait should come up top in the experiment and not at all in the control. Well, it does not appear at all in the Protein Quantifier output.

**Comment by jpfeuffer** [comment] 2017-04-24 17:57
Okay. But even that should not be the case if IDPosteriorErrorProbability was performed on the whole set of PSMs.
Since this is getting more complex: Can you upload the workflow?

**Comment by isaphan** [comment] 2017-04-24 19:35
Workflow attached (hope this works, the form is not accepting this file format). Input Node 167 is the output from the Mascot online adapter.

**Comment by jpfeuffer** [comment] 2017-04-24 20:12
Unfortunately it does not seem to work via github. Can you upload it somewhere and just paste the link?

**Comment by isaphan** [comment] 2017-04-26 23:39
https://www.dropbox.com/s/rp9o7l6xtn5tcxy/lfq_and_peptide_identification_mascot_ampylation.knwf?dl=0

**Comment by jpfeuffer** [comment] 2017-04-27 09:13
Thanks.
- Can you set add_decoy_peptides to "true" in the FalseDiscoveryRate node? With the current settings Fido needs target/decoy information for calibration. (Recommended)
- You probably need to use different q-value cutoffs for Fido and quantification. Only mild filtering should applied before Fido (let's say all peptides with 10% posterior probability).
- This is not the labelfree_with_protein_quantification workflow that we propose on https://github.com/OpenMS/Tutorials/blob/master/Workflows/labelfree_with_protein_quantification.knwf . The aforementioned issues are addressed in this workflow.

**Comment by isaphan** [comment] 2017-04-27 19:10
> You probably need to use different q-value cutoffs for Fido and quantification. Only mild filtering should applied before Fido (let's say all peptides with 10% posterior probability).

As a naive user, this is where I wish there was a parameter called 'q-value cutoff'. However, reading between the lines of the OpenMS tutorial, I am guessing you mean I should set IDFilter.score.pep = 0.1 ?

> The aforementioned issues are addressed in this workflow.

I'm not sure I understand what you mean. In the labelfree_with_protein_quantification workflow, default values look exactly the same as in the lfq workflow: FalseDiscoveryRate.add_decoy_peptide = "false",  IDFilter.score.pep = 0.01, ie FDR = 1%.

**Comment by jpfeuffer** [comment] 2017-04-27 23:02
Regarding the first issue, I agree with you that it should be more straightforward to filter for FDR and we are thinking about adding this cutoff directly to the FDR tool. Would you as a user find this a reasonable way to do this? On the one hand it makes life easier for starting users but on the other it adds some kind of redundancy to the options of different tools. 
Concerning the second issue, as far as I remember the workflow (not in front of me right now) the IDs for protein inference follow a different path than the IDs that are mapped to the features for quantification on MS1 level. To infer the probability of presence of proteins and/or protein groups you can use the set of peptides found inside as well as outside of quantifiable features (2D areas in the MS1 map consisting of the isotopic envelope and elution profile of an entity). But for quantification you only want peptides that also have integratable MS1 intensities associated with them and are reliably identified (e.g. under a certain q-value). Therefore at the end of such a loop in the lfq protein workflow, you usually collect two types of identifications (represented by different outports) which may be (and in this case are) used in a different context afterwards. I admit that this is easily overlooked and hope I could clarify this a bit. I have to apologize for being so brief in the last comment.

**Comment by isaphan** [comment] 2017-04-28 01:38
I guess you could mention in the FDR tool help that to set the q-val cutoff one needs to set IDFilter.score.pep and a value of 0.01 for score.pep really means FDR = 1%? It's very convoluted.  I am merely trying to obtain similar results that I got from MaxQuant/Perseus and Distiller/Scaffold.  No luck so far.

Alas, after setting FalseDiscoveryRate.add_decoy_peptide=True and IDFilter.score.pep = 0.1,  my current lfq workflow is still not returning sensible results; the table I am getting out from ProteinQuantifier is odd: 

A) the bait  from the TAP experiment should be the most abundant species and it is completely missing. I suspect the rest of the output is wrong too, but I can't easily tell because..

B) there is no protein description! I had write_protein_description=true in PeptideIndexer, is there a way to get those merged into the ProteinQuantifier output?

I'm now running labelfree_with_protein_quantification workflow.

**Comment by isaphan** [comment] 2017-05-02 00:42
labelfree_with_protein_quantification is starting to produce sensible results... except  the bait in the control sample should not appear at all and it does. Neither MaxQuant nor Distiller detect the bait in the control.

**Closed** 2020-02-21 12:23 UTC
Labels: Documentation, Performance, TOPP, defaults, defect, wontfix
