### ISSUE TITLE
QWidget: Cannot create a QWidget when no GUI is being used

### ISSUE THREAD

**Issue by BioComSoftware** [OpenMS/OpenMS#2195] opened 2016-09-29 13:02 UTC
When attempting to run a pipeline (*.TOPPAS) file on Linux Ubuntu using the ExecutePipeline OpenMS executable - 'IF' the pipeline has an error, instead of an error being presented at the command line or log file, the error...

'QWidget: Cannot create a QWidget when no GUI is being used'

...appears. 

It seems that the ExecutePipeline command attempts to display the error using a QWidget window, which fails at the command line...ultimately masking the error. The only way to get the error is to run the *.TOPPAS pipeline from the GUI. 

OpenMS versions affected:
2.0.1
2.1.0

LINUX VERSION:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by hendrikweisser** [comment] 2016-09-29 13:12
Duplicate of #954. (Still, thanks for reporting it!)

**Closed by hendrikweisser** 2016-09-29 13:12 UTC
