### ISSUE TITLE
OpenSwathWorkflow crashes

### ISSUE THREAD

**Issue by sjr24** [OpenMS/OpenMS#5168] opened 2021-02-15 19:43 UTC
SwathWizard crashes following iRT and mz correction.  Log report is below.

Loading mzML file C:/Users/srice/Downloads/HeLa_Evosep_diaPASEF_RAW/60SPD_py8/20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450.mzML using readoptions normal

Progress of 'Loading metadata file C:/Users/srice/Downloads/HeLa_Evosep_diaPASEF_RAW/60SPD_py8/20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450.mzML':

Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
Determined there to be 24 SWATH windows and in total 1319 MS1 spectra
Determined there to be 24 SWATH windows and in total 1319 MS1 spectra

-- done [took 9.80 s (CPU), 9.79 s (Wall)] -- 
Progress of 'Loading data file C:/Users/srice/Downloads/HeLa_Evosep_diaPASEF_RAW/60SPD_py8/20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450.mzML':

-- done [took 03:38 m (CPU), 01:52 m (Wall)] -- 
Will load iRT transitions and try to find iRT peptides
Progress of 'Load PQP file':

-- done [took 0.00 s (CPU), 0.01 s (Wall)] -- 
Progress of 'Extract iRT chromatograms':

-- done [took 1.53 s (CPU), 0.76 s (Wall)] -- 
Progress of 'Retention time normalization':
Will analyse 11 peptides with a total of 47 transitions 

rsq: 0.99592 points: 11
# mz regression parameters: Y = -8.55219 + 0.0193346 X + -7.83063e-06 X^2
 sum residual sq ppm before 100.146 / after 66.2143

Process 'C:/Program Files/OpenMS-2.6.0/bin/OpenSwathWorkflow.exe' crashed hard (segfault-like). Please check the log.

**Comment by cbielow** [comment] 2021-02-16 07:30
Hi,

thanks for reporting the problem.
This is not actually an issue with the wizard, but the underlying OpenSwathWorkflow.
Could you point us to the input files you used, so we can recreate the problem.
Thanks!

**Comment by sjr24** [comment] 2021-02-16 13:57
Chris,

I am using a file from the data published by Meier et al. 2020.  diaPASEF: parallel accumulation-serial fragmentation combined with data-independent acquisition. Nature Meth.  Data is available at the PRIDE db accession number PXD017703.  The file I have tried are at HeLa_Evosep_diaPASEF_RAW\60SPD_py8\ 20200428_Evosep_60SPD_SG06-16_MLHeLa_200ng_py8_S3-A4_1_2450.d (I tried *_2450.d :*_2452.d).  The error occurred when the .d files were converted to mzML using either msconvert or  convertTDFtoMzML.py.  Let me know if you need any additional information.

Thanks,
Shawn

**Comment by cbielow** [comment] 2021-02-17 14:50
hi, I cannot reproduce the problem, but that might well be the iRT library, which differs.
Can you point me to the one you are using.
Thanks.

**Comment by cbielow** [comment] 2021-04-18 12:24
I re-ran OpenSWATHWorkflow with the files you specified and I cannot reproduce the problem*.
However, the data should be converted using MobiDIK (http://openswath.org/en/latest/docs/mobi-dik.html), as far as i can tell, and not via msconvert because the latter will result in huge files and a wrong data layout.
I also tested with the Mobi-DIK converted data, and it runs through fine*.

*Litte caveat: I'm using a current OpenMS development version, which might not behave identical to the 2.6 release.

My best guess to go forward is to try conversion using Mobi-DIK and see if that fixes the problem. If not, please feel free to report back and we will think of a better solution.

**Comment by cbielow** [comment] 2024-07-19 09:15
closing, even though we might want to inspect the data conversion in any mzML file that the OpenSwathWorkflow receives and at least print a warning or halt computation entirely if the wrong converter was used.
@jcharkow what's your take on that? Or does msconvert deliver good results in the meantime?

**Closed** 2024-07-19 09:15 UTC
