### ISSUE TITLE
IDPosteriorErrorProbability does not work for PercolatorAdapter

### ISSUE THREAD

**Issue by katrina-uw** [OpenMS/OpenMS#5778] opened 2022-02-02 02:10 UTC
I try to run the following workflow:
![image](https://user-images.githubusercontent.com/45520179/152082286-cd8ddca5-a892-43c8-adaa-8e87ec4d52fb.png)

However, it failed with the error msg:
No data collected. Check whether search engine is supported.

I understand it may not support percolator, however, I wonder what's the best way to extract the posterior probability from percolator if I want to apply fidoAdapter on top of it? The reason is that percolator only provides pep, where the posterior probability is equal to 1-pep (This is why I want to apply IDPosteriorErrorProbability to get 1-pep), and the input for FidoAdapter should be the posterior probability.

Thanks a lot!

**Comment by jpfeuffer** [comment] 2022-02-02 09:46
Hi!

Everything you are saying is correct. IDPEP should not be needed here.

As far as I remember, the Fido adapter does an automatic conversion if error probabilities are given.
Did you select "pep" as the main score in Percolator adapter?

**Comment by katrina-uw** [comment] 2022-02-02 18:36
Thank you for the reply!

Yes I have selected pep in the percolator, here is the output file from percolator adapter:
![image](https://user-images.githubusercontent.com/45520179/152215663-2054f784-6f66-4f3d-85d1-0f5b8cbfc8e6.png)

And here is the output after FidoAdapter:
![image](https://user-images.githubusercontent.com/45520179/152216373-54c926d4-6b50-414e-a18e-4f62612936ea.png)

Looks like the FidoAdapter outputs the posterior error probability instead of the posterior probability.  
Can I use 1-pep to get the posterior probability? Is there a way to let it output posterior probability directly? (Or through some converter?)

Thank you so much!

**Comment by jpfeuffer** [comment] 2022-02-02 21:31
Hi! 
Hmm but Fido adapter does not change peptide probabilities. It only assigns probabilities for proteins. So it is normal to see no change on the peptide level. You need to look for the proteins.

And yes you can just convert them by calculating 1-probability.

**Comment by katrina-uw** [comment] 2022-02-03 02:15
Oh I see, I guess you mean this table is not the results that FIDO computes right? 
https://user-images.githubusercontent.com/45520179/152216373-54c926d4-6b50-414e-a18e-4f62612936ea.png

I wonder what's the best way to see the protein probability generated from fidoAdapter? 
I try to use the TextExporter with the following setting (because the openMS tutorial said that IDtextReader can only read peptide information):
![image](https://user-images.githubusercontent.com/45520179/152269994-4dae9b05-df9c-4422-8120-e7bd3dfef1b1.png)
and the flow is:
![image](https://user-images.githubusercontent.com/45520179/152269952-1435428d-ccd2-4b25-b028-832d4d56c007.png)

But I'm not sure if there is any other way to read the protein probability from fido. Is my way correct?

Thank you so much!

**Comment by jpfeuffer** [comment] 2022-02-03 08:37
Can you try to use the MzTabExporter and MzTabReader instead. It should create multiple tables for different sections.

**Comment by katrina-uw** [comment] 2022-02-03 12:13
Thanks!!

However when I use MzTabExporter and MzTabReader it throws the following error:
Error: Unexpected internal error (Multiple files in a run, but no id_merge_index in PeptideIdentification found.)

Here is my workflow:
![image](https://user-images.githubusercontent.com/45520179/152340677-e7b72887-0db5-4e56-9672-462c8f644831.png)

hmm, is my connection wrong here?

**Comment by jpfeuffer** [comment] 2022-02-03 13:01
Hi! In your IDMerger, can you set merge_proteins_add_PSMs to true?
Otherwise it kind of just concatenates the single searchengine runs into one file  and many tools do not support this structure.

**Comment by katrina-uw** [comment] 2022-02-04 01:27
Yes actually I have set this one to be true. Here is my workflow:
![image](https://user-images.githubusercontent.com/45520179/152457064-775de7c3-4f27-42ab-b51a-8dc7ec7fb1c6.png)

The setting with IDMerger is:
![image](https://user-images.githubusercontent.com/45520179/152457101-15d79d98-33f2-4c26-a1e2-89e8e054858f.png)

I'm confused about the  "id_merge_index", shouldn't the peptide files be already merged before it is feeding to the percolator?

(By the way I try to add IDMerger with merge_proteins_add_PSMs to be true after percolator as well, it does not work either...)

**Comment by m-jahn** [comment] 2022-02-04 09:40
Hi, may I join the discussion fo this issue?
I wanted to open an issue myself but I noticed that I have very similar problems as @katrina-uw. I'm suspecting this is related to IDMerger too.

![image](https://user-images.githubusercontent.com/32667667/152505749-ec611e3d-0d0f-4f62-9b50-f86ec479beeb.png)

In short, I was running a KNIME pipeline based on the FeatureFinderIdentification workflow (Weisser et al., 2017) successfully in OpenMS 2.4. I recently tried to rerun it in KNIME 4.5.0 and OpenMS 2.7 but the pipeline failed with several errors. I replaced all nodes with recent versions and tried to work around the errors I got, but the problem always starts when I try to combine several IDXml files with IDMerger, and feed the combined IDs to FFI. The workflow usually runs fine until it gets to ProteinQuantifier, where I get two types of errors, depending on the settings in IDMerger  ragrding `merge_proteins_add_PSMs`:

Either this: 

`ERROR ProteinQuantifier    0:365      Failing process stdout: [No fractions annotated in consensusXML. Assuming unfractionated., Quantifying peptides..., <No fractions annotated in consensusXML. Assuming unfractionated.> occurred 2 times, Error: Unexpected internal error (Protein group quantified that is not present in inference data.)]`

Or the error reported in this issue: https://github.com/OpenMS/OpenMS/issues/4232
This issue was closed but the authors did not report their solution.

BTW I also tested a simple vanilla workflow with IDmerger from [nodepit](https://nodepit.com/workflow/com.knime.hub/Users/timosachsenberg/GCB%202021/basic_peptide_identification_with_inference), the one mentioned in [this issue](https://github.com/OpenMS/OpenMS/issues/5518). It did not work with two basic DDA LFQ files.

**Comment by m-jahn** [comment] 2022-02-04 11:25
I think I made some progress on this. The issue seems to be a bug in `IDMerger`.
I had a closer look at the merged idXML files it produces and there was only one field that indicates the origin of the original idXML files. If this field contains a list with more than one item/file names, both ProteinQuantifier and MzTabExporter fail. This is the one:

```
<UserParam type="stringList" name="spectra_data" value="[/tmp/knime_labelfree_MSGFp90792/fs-MapAl_0-322-90793/000/000/MapAlignerPoseClustering_0/HF_20220113_DDA_40min_2ul_TTP_1.mzML]"/>
```
If I remove the other file names from the merged idXML file and leave only one, all nodes finish and I get expected the output with this workflow. Here the merging is done separately, the idXML file saved to disk, manipulated, and re-imported for the FFI workflow (the top part).

![image](https://user-images.githubusercontent.com/32667667/152520463-a906e280-5a70-44c4-b019-945e2b231d76.png)


Maybe this is a bug. If so it could be relatively easy fixed by trimming the list in `spectra_data` to one item, either the first or last input file, or an arbitrary new ID such as "merged_IDs_from_n_files".

**Comment by jpfeuffer** [comment] 2022-02-04 13:46
Can you all try with annotate_file_origin=true? I am wondering why this is not the default. I think this should add the id_merge index. mztab and protein quantifier need to know from which file an ID comes from

**Comment by m-jahn** [comment] 2022-02-04 14:06
With the example above, simply using a couple of idXMLs and then Input Files --> IDMerger --> ProteinQuantifier, the latter fails with a similar error as the ones mentioned above:
```
ERROR ProteinQuantifier    0:393      Failing process stdout: [Experimental design (Identification derived):,   files: 8  fractions: 1  labels: 1  samples: 8, , Error: Unexpected internal error (More than one ms file annotated in protein identification.)]
ERROR ProteinQuantifier    0:393      Failing process stderr: []
ERROR ProteinQuantifier    0:393      Return code: 8
ERROR ProteinQuantifier    0:393      Execute failed: Failed to execute node ProteinQuantifier
```

ProteinQuantifier had default settings and IDMerger had:
![image](https://user-images.githubusercontent.com/32667667/152542244-c5e446f3-4a1e-4b4b-b59a-b354c13b7eee.png)

**Comment by katrina-uw** [comment] 2022-02-04 16:40
annotate_file_origin=true works, not sure what's the meaning of this field, but thank you!! :)

**Comment by katrina-uw** [comment] 2022-02-06 05:01
Sorry one last question, regarding the MzTabReader, is it possible to export the file from it? This is what I was trying to do:
![image](https://user-images.githubusercontent.com/45520179/152668336-2b75cc9e-87ab-42c1-9384-a98c52cad6aa.png)

However, I got this exception:
WARN  CSV Writer           4:36       Input table must only contain String, Int, or Doubles

I guess this is because there some fields in the reader that is of "list" format. However, if csv does not work, is there any way to export the data to text format?

Thank you!

**Comment by jpfeuffer** [comment] 2022-02-06 09:13
You can use the Output File node directly on the output of MzTabExporter

**Comment by m-jahn** [comment] 2022-02-07 15:05
Just an update with this issue:

- when I use `annotate_file_origin=true`, mzTabExporter does not fail any longer :+1: 
- ProteinQuantifier still fails with the error message mentioned above :-1: 
- Tested this with different idXML files from different experiments, same result
- used minimal pipeline with nodes: Input FIles --> IDMerger --> ProteinQuantifier

If somebody wants to reproduce this, the KNIME pipeline is here: https://github.com/m-jahn/openMS-workflows/tree/master/labelfree_MSGFplus_Percolator_FFI

**Comment by jpfeuffer** [comment] 2022-02-07 16:56
Yes so I thought about it and the problem is that you are trying to annotate every MS map with the merged IDs. While this is a valid strategy, it is hard to track the origin of the ID and the feature (for quantification) separately. That is why it was never tested yet. It worked before since we just recently introduced tracing of all information to enable complete PRIDE compatible mztabs.
It seems like only ProteinQuantifier chokes on it. So it might be fixable.

But seeing your workflow, it looks like you are trying to replicate one of our newest additions, the ProteomicLFQ node. It will hide the merging, aligning, linking and inference in one node and allows for matching across runs. You could give it a try. I recently uploaded a workflow to the KNIME hub and a blog post should be released this week.

**Comment by jpfeuffer** [comment] 2022-02-07 16:57
The workflow is here:
https://hub.knime.com/openms-team/spaces/Blog%20workflows/latest/Protein%20label-free%20quantification~Q8TgAl_OAuerfhES

**Comment by m-jahn** [comment] 2022-02-08 08:40
Thanks for your input, I give it a try and will compare the results of the ProteomicsLFQ pipeline to my current workflows. Will ProteinQuantifier be updated to deal with the output from IDMerger nevertheless? If not this issue can be closed IMO.

**Comment by jpfeuffer** [comment] 2022-02-08 10:13
Yes, we would like to fix it. But I think we will track it in the issue that you linked so I will close here.

**Closed by jpfeuffer** 2022-02-08 10:14 UTC
