### ISSUE TITLE
FileConverter RAW -> mzML does not produce OpenMS-usable mzML files on Windows

### ISSUE THREAD

**Issue by enetz** [OpenMS/OpenMS#4353] opened 2019-11-12 19:45 UTC
KNIME does not accept the ThermoRawFileParser.exe with the massage:
`Invalid MIMEtype at port number 2 : has extension: 'exe'; expected one of: []`

Maybe because no accepted file endings for the executable are defined in `FileConverter`.

Found on:
Windows 10
KNIME 4.0.2
OpenMS 2.4.0.201911011812 (a recent nightly build of the KNIME plugin)

**Comment by jpfeuffer** [comment] 2019-11-13 08:01
Yes, there are multiple options:
- Allow "exe" in the endings. 
- Remove the file port in KNIME (since we ship the exe at a fixed place).

**Comment by enetz** [comment] 2019-11-13 10:20
Additionally if I don't provide an executable it says `Process 'ThermoRawFileParser.exe' failed to start. Does it exist? Is it executable?`

@jpfeuffer So the `ThermoRawFileParser.exe` is shipped together with the KNIME plugin automatically, but FIleConverter does not know where? How about the NET executable?

And is there a way to remove the ports from the KNIME node without removing input file parameters for the FileConverter binary (if we need them at all)?

Allowing "exe" endings would be a quick fix to make it run now, but in the long term we can't expect users to find the executable in the KNIME plugin folders by themselves.

**Comment by jpfeuffer** [comment] 2019-11-13 12:07
I agree. I think also that at least the path to the file (in our THIRDPARTY) is missing in the binaries.ini (s).
Can you check if the exe exists in the depths of the de.openms KNIME plugin or if we need to update our packaging as well, please?

**Comment by enetz** [comment] 2019-11-13 13:04
I found it in
knime_4.0.2\plugins\de.openms.win32.x86_64_2.4.0.201911011812\payload\bin\ThermoRawFileParser\ThermoRawFileParser.exe
in the Windows 64 Bit zip archive version, the same place as all the other THIRDPARTY  binaries, so that is not an issue

**Comment by jpfeuffer** [comment] 2019-11-13 17:14
Great. I think I can easily fix it then. I'll add to timos current PR #4355

**Comment by hroest** [comment] 2020-01-18 22:46
@jpfeuffer is this fixed?

**Comment by jpfeuffer** [comment] 2020-01-19 19:27
Should be fixed. @enetz can you confirm?

**Comment by enetz** [comment] 2020-01-19 19:30
@jpfeuffer @hroest I will test this with the latest nightly KNIME build tomorrow

**Comment by enetz** [comment] 2020-01-20 12:49
It looks like the conversion runs and an mzML file is written out. The file also looks normal when I open it in a text editor. But reading it in OpenMS I get this error:

```
ERROR PeakPickerHiRes      0:64       Failing process stdout: [Progress of 'loading spectra list':, Error: Unable to read file (- due to that error of type ConversionError in: C:\jenkins\ws\openms_nightly_packaging\c2e226b2\source\src\openms\include\OpenMS/DATASTRUCTURES/StringUtils.h@812-double __cdecl OpenMS::StringUtils::toDouble(const class OpenMS::String &))]
ERROR PeakPickerHiRes      0:64       Failing process stderr: []
ERROR PeakPickerHiRes      0:64       Return code: 3
ERROR PeakPickerHiRes      0:64       Execute failed: Failed to execute node PeakPickerHiRes
```

I get the same error with multiple tools, tried with PeakPickerHiRes, OpenPepXLLF and PrecursorMassCorrector.
Files converted with MSConvert work fine.

**Comment by jpfeuffer** [comment] 2020-01-20 12:51
hmm.. does the same happen outside of KNIME? probably, right?

**Comment by enetz** [comment] 2020-01-20 13:38
Happens on Windows in and outside of KNIME. Latest KNIME nightly build (18.12.2019) and a binary build I compiled myself from around the same time.

**Comment by jpfeuffer** [comment] 2020-01-20 13:41
Would be interesting to check the lastest ThermoRawFileParser.exe from the developers there.
Otherwise we need to dig deeper in our code :(

**Comment by enetz** [comment] 2020-01-20 14:09
I tried the ThermoRawFileParser.exe from the latest 1.1.1 release. Same error.

**Comment by hroest** [comment] 2020-01-20 17:40
looks like we try to conver to double when there is something else there @enetz can you try and debug and/or provide a minimal example of such a file that produces the error ? We should fix the error and add the file to our regression tests

**Comment by enetz** [comment] 2020-01-22 15:26
@hroest @jpfeuffer  I think I found the cause of the error now. There is a line that the parser writes out for each MS2 spectrum I think, it looks like this when the mzML is written on windows:
`<userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" type="xsd:float" value="1112,523" />`
and this is the same from a file converted on Linux:
`<userParam name="[Thermo Trailer Extra]Monoisotopic M/Z:" type="xsd:double" value="1112.523014796985535"/>`

On windows a comma is used for the float number and we try to parse a double with a dot.
Since all the other numbers in mzML files use dots, this looks like an error of the ThermoRawFileParser.

Here are two example files with the same 3 spectra each. The second spectrum is the culprit. The  `...LinTest.mzML` file works while the `...WinTest.mzML` shows the error.
[ThermoRawFileParserTest_WinLin.zip](https://github.com/OpenMS/OpenMS/files/4098016/ThermoRawFileParserTest_WinLin.zip)

**Comment by hroest** [comment] 2020-01-30 14:59
@enetz is there a way to control this behaviour? It seems it has to do with your locale settings: https://stackoverflow.com/questions/9160059/set-up-dot-instead-of-comma-in-numeric-values

also we should probably discuss this with HUPO PSI to understand whether this should be valid for mzML and whether this should be fixed on the Thermo side. Honestly, I dont think we should allow this nonsense and allow writers to use different decimal separators in their XML. @enetz can you file a bug against the `ThermoRawFileParser`?

@jpfeuffer @timosachsenberg it seems our error message was not really helpful here

**Comment by enetz** [comment] 2020-01-30 15:21
@hroest I tried this on two separate Windows 10 installations, one of them with english and one with german as the default/main language. So if this is some obscure Windows setting, we can't expect users to change that themselves.
This has worked fine with MSConvert on Windows for years, so I don't think commas are allowed for floating point numbers in mzML files. It is also just this one type of value, a `userParam`, all other numbers have a dot.

I will file a bug report then.

**Comment by jpfeuffer** [comment] 2020-01-30 16:30
See also an old solved issue of ours:
https://github.com/compomics/ThermoRawFileParser/issues/45

**Comment by timosachsenberg** [comment] 2020-01-30 16:35
> I tried the ThermoRawFileParser.exe from the latest 1.1.1 release. Same error.

@enetz do you mean v1.1.11 ?

**Comment by enetz** [comment] 2020-01-31 12:00
> > I tried the ThermoRawFileParser.exe from the latest 1.1.1 release. Same error.
> 
> @enetz do you mean v1.1.11 ?

@timosachsenberg yes, v1.1.11 from September 25th

**Comment by timosachsenberg** [comment] 2020-02-18 12:26
ok should be fixed on current release2.5.0 HEAD

**Closed by timosachsenberg** 2020-02-18 12:26 UTC
Labels: defect
