### ISSUE TITLE
MaraClusterAdapter executable not found in KNIME

### ISSUE THREAD

**Issue by m-jahn** [OpenMS/OpenMS#3907] opened 2019-01-03 17:17 UTC
Hello,

first I want to say thanks to all the developers that constantly improve openMS.
I'm using it for 3 years now, mainly to analyze labelfree MS data. I wanted to test the new MaraCluster node in KNIME using MaraClusterAdapter but I get the following error message regardless of what files I use as input:
`Maracluster executable not found at location specified. Aborting!`

The error looks like it is a KNIME issue (I haven't tested the MaraCluster executable independently). However, the MaraCluster executable is present in the KNIME sub-folder _payload/bin/MaRaCluster_ and there's an entry in the _binaries.ini_ file that I suppose points towards those external executables.
Is there a way to specify an alternative path to the MaraCluster executable?

Thanks for help,
Michael

**Comment by jpfeuffer** [comment] 2019-01-07 14:38
Hi Michael,

happy new year and thanks for the kind words.

Unfortunately I can confirm your bug but I think I might have found the problem:
https://github.com/OpenMS/OpenMS/blob/ac4c8767657504e98572baf453c41dcf1d7fff15/src/topp/MaRaClusterAdapter.cpp#L291
@Leon-Bichmann (author) The above line is (I think) not able to find the executable when it's on a PATH environment (as it is the case with the KNIME nodes) but only when it is given directly. The only option here is usually to try to execute it (let it find by the system) and catch a potential failure there.

@m-jahn Since the executable parameter is not exposed in KNIME, I think you cannot workaround it right now. You have to start it from the command line or wait and update (at least the executable) once it is fixed.

**Comment by m-jahn** [comment] 2019-01-07 14:57
Okay thanks, then I know. Will run MaRaCluster externally for the time being.

**Comment by Leon-Bichmann** [comment] 2019-01-07 15:36
Alright, happy new years also from me!

Sorry for that inconvenience, we can try to fix it for one of the next nightly builds.

Will removing that if clause fix the issue?

**Comment by jpfeuffer** [comment] 2019-01-25 15:47
Fixed in #3911

**Closed by jpfeuffer** 2019-01-25 15:47 UTC
