### ISSUE TITLE
Calculation of protein ratios by ProteinQuantifier (labelled peptides)

### ISSUE THREAD

**Issue by Stortebecker** [OpenMS/OpenMS#3016] opened 2017-11-21 14:05 UTC
Hi.

@algom reported a weird calculation of protein ratios by ProteinQuantifier. ProteinQuantier seems to use *peptide abundances* for the calculation of protein ratios, independent of the method (`-average`). This means that the methods `sum` and `mean` are equal and `median` is based on a single peptide (or even the abundances of two different peptides), independent of the `-top ` specified. 

For me, this is unwanted behavior. One would need to change the calculation of `mean` and `median` to be based on *peptide ratios* instead.

Example: 
consider a protein with three peptides. 
the peptide abundances are 
for light: 1000, 200, 40 (sum=1240)
for heavy: 500, 75, 30 (sum=605)
peptide ratios would be: 0.5, 0.375, 0.75

At the moment, 
`median` is calculated as: log2(median(abundances heavy) / median(abundances light)) = log2(200/75)
`mean` is calculated as: log2(mean(abundances heavy) / mean(abundances light)) = log2((1240/3)/(605/3))

Instead,
`median` should be calculated as: log2(median(abundances heavy / abundances light)) = log2(median(ratios))
`mean` should be calculated as: log2(mean(abundances heavy / abundances light)) = log2(mean(ratios))

This probably applies in the same way to `weighted_mean`.

**Comment by Stortebecker** [comment] 2017-11-21 16:47
I think that the unexpected behavior of `mean` occurs specifically in labelled datasets. The difference to unlabelled datasets is that *peptide abundances* are **paired data** and the "n" is always the same in both conditions, therefore `sum` = `mean`. Still, the current method might be wanted for unlabelled data. Maybe it would make more sense not to replace the current implementation, but to provide an *additional* `-method`: `mean_ratio`. 

However, the `median` calculation would also be weird for unlabelled datasets. I think it is very susceptible for errors. If we take the above example, but assume that the third peptide had some contamination in the heavy peak, chaning the heavy abundance from 30 to 400. If we quantify with the current `median` implementation, we would get the ratio log2(400/200) for the protein, which is totally off. Calculating the median of ratios for each peptide would be much less susceptible.

Maybe you could also add a note to the [documentation](http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_ProteinQuantifier.html) about how the calculations work.

**Comment by cbielow** [comment] 2017-11-22 08:43
I can totally see the point (but have not looked at the code).
Maybe @hendrikweisser can help here?

**Comment by hendrikweisser** [comment] 2017-11-28 15:52
I developed ProteinQuantifier for label-free analysis; someone else later added the ratios calculations (@lars20070?). I'm fairly sure that the tool should behave as intended for label-free data, but I don't know about labeled.

> This means that the methods sum and mean are equal

For label-free, the main difference between "mean" and "sum" is how missing values are treated - they are ignored for "mean", but are implicitly zero for "sum". This is mentioned at the end of the documentation.

> However, the median calculation would also be weird for unlabelled datasets.

Not really. You can come up with examples that give weird results for each averaging method. Median is generally more robust against outliers than mean.

In the end, I fully agree that for labeled data, peptide ratios should be calculated first, then averaging should be applied. If that's not how it's done at the moment, it should be fixed - but to be honest I don't have enough time/motivation for it.

**Comment by lars20070** [comment] 2017-12-04 13:36
IMO, we should wait for @jjGG's conclusions. He is currently evaluating different [protein quantification](https://gitter.im/OpenMS/ProteinQuantification) approaches.

**Comment by lars20070** [comment] 2017-12-04 14:59
@Stortebecker `n` is the number of peptides per protein, not the number of conditions `n=2`.
IMO, there is no need to distinguish between *labelled* and *label free* experiments in the protein quantification step.

**Comment by Stortebecker** [comment] 2017-12-05 12:54
@lars20070 Exactly, that is what i was talking about. In a labelled experiment, you always have the same number of peptides per protein in each of the conditions.

**Comment by algom** [comment] 2017-12-05 18:15
@lars20070 On the contrary, it has to be different. The big advantage of the labelled approach is that it provides extra information, at the peptide level. As every comparison between the peptides, even at a different charge, makes the whole protein abundance determination more robust. That is why it is better to have peptide ratios and from here construct the protein abundance ratio. Unfortunately, MSqRob is mainly targeted towards label-free. One might adapt it by adding a term in the model fitting including the label, and this might work properly, although a degree of freedom will be lost.

**Comment by lars20070** [comment] 2017-12-06 09:48
@Stortebecker @algom [Back in 2014](https://github.com/OpenMS/OpenMS/pull/1074#discussion_r20402607), Hannes convinced me that a simple `sum = mean` outperforms `weighted mean`. Similarly, one could test that *averaging the ratios instead of abundances* leads to tighter protein fc distributions in fixed ratio experiments. [Here](https://www.dropbox.com/sh/bdykvgiyvs7qi2z/AACJVxjo6bb1tIGOWmU8rHCYa) the fixed ratio peptide abundances Jonas is working with.

**Comment by jpfeuffer** [comment] 2018-02-07 11:09
What's the status here? How is the evaluation of ProteinQuantification strategies going?
Have you tried diffacto?
https://www.ncbi.nlm.nih.gov/pubmed/28302922 https://github.com/statisticalbiotechnology/diffacto

And what about the MSStatsConverter?

**Closed** 2020-08-09 14:50 UTC
Labels: question, wontfix
