### ISSUE TITLE
TheoreticalSpectrumGenerator charge parameter is not handled by ParamHandler

### ISSUE THREAD

**Issue by mwalzer** [OpenMS/OpenMS#2613] opened 2017-05-18 15:56 UTC
`getSpectrum` parameters `min_charge` and `max_charge` are not handled by ParamHandler like all other parameters.

**Comment by enetz** [comment] 2017-05-18 16:14
You mean the charges should just be handled by the ParamHandler, like e.g. ion types?
max_charge was already there before and was never handled by the ParamHandler,
@timosachsenberg was there a reason for that?
I agree, I do not see any reason for special treatment of these parameters.

**Comment by timosachsenberg** [comment] 2017-05-18 16:22
hmm I guess the performance overhead via parameters is too high

**Comment by timosachsenberg** [comment] 2017-05-18 16:23
note that the other stuff is set only once but charges depend on actual precursor charge

**Comment by timosachsenberg** [comment] 2017-05-18 16:25
also note that this is hard to get these changes in parameter thread safe so I would be against using param

**Comment by timosachsenberg** [comment] 2017-05-18 16:29
So to answer your question: I think it is by design to allow using TSG in a multi-threaded context without locks. I would keep it as it is.

**Comment by timosachsenberg** [comment] 2017-05-18 20:46
close?

**Comment by mwalzer** [comment] 2017-05-19 10:27
Hadn't had any chance to respond yet

**Comment by mwalzer** [comment] 2017-05-19 10:36
So, while I agree that it's a hassle to get changes needed often in, I think setting the defaults like that would be good.

**Comment by mwalzer** [comment] 2017-05-19 10:36
Or have no defaults for min and max charge.

**Comment by timosachsenberg** [comment] 2017-05-19 10:42
I think it would then be better to have no defaults.

**Comment by timosachsenberg** [comment] 2017-05-22 10:33
fixed with https://github.com/OpenMS/OpenMS/pull/2622

**Closed** 2017-05-25 21:12 UTC
