### ISSUE TITLE
Error in TargetedFileConverter

### ISSUE THREAD

**Issue by Ankit-Balhara** [OpenMS/OpenMS#3954] opened 2019-02-04 18:12 UTC
I am trying to convert my SpectraST mrm file to openswath compatible TraML format by using the following command line but I geeting this error message:

c:\Program Files\OpenMS-2.4.0\bin>TargetedFileConverter -in c:\TPP\bin\SpecLib_pqp.mrm -out c:\TPP\bin\transitionlist.TraML
Warning: unknown modification '143' of residue 'C' - adding it to the database
Warning: unknown modification '111' of residue 'Q' - adding it to the database
Progress of 'conversion to internal data representation':
Error: Unexpected internal error (Error, could not parse modifications on C[143]C(Carbamidomethyl)TESLVNR. Please use unimod / freetext identifiers like PEPT(Phosphorylation)IDE(UniMod:27)A.)**

Please help me out to resolve this issue. As I am quite new to programming, please suggest elaborately. Thanks in advance.

**Comment by hroest** [comment] 2019-02-04 18:55
Could you share with us the input file that you used? It seems there is an issue with the modification that is being used, specifically on the peptide "C[143]C(Carbamidomethyl)TESLVNR". However, I dont find any issues with this when trying this in pyopenms


```
$ python
Python 3.7.1 (default, Oct 20 2018, 21:59:34) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopenms
>>> pyopenms.AASequence.fromString("AAC[143]C(Carbamidomethyl)TESLVNR")
Warning: unknown modification '143' of residue 'C' - adding it to the database
<pyopenms.pyopenms_5.AASequence object at 0x7fe10f12f7f0>
>>> pyopenms.AASequence.fromString("C[143]C(Carbamidomethyl)TESLVNR")
<pyopenms.pyopenms_5.AASequence object at 0x7fe10f12f7f0>
>>> pyopenms.AASequence.fromString("C[143]C(Carbamidomethyl)CTESLVNR").getResidue(0).getMonoWeight()
161.01056506380002
```
and it seems the weight is correct here as well ...

**Comment by Ankit-Balhara** [comment] 2019-02-05 05:00
Hi Hannes,

Thanks for your quick reply. Please find the attached file.
 SpecLib_pqp.mrm
<https://drive.google.com/file/d/1A2QmWHTWRcWPDFP7HJgiI6k7niwC73uj/view?usp=drive_web>
 SpecLib_pqp.pepidx
<https://drive.google.com/file/d/1yZuHHMnTAVm436pru1OyWdc5owawfEB1/view?usp=drive_web>
 SpecLib_pqp.spidx
<https://drive.google.com/file/d/1iFNQumz7Bjnn4ApnbVzX3bdbSE1HYvRO/view?usp=drive_web>
 SpecLib_pqp.splib
<https://drive.google.com/file/d/1alac9ZUWwC4cFOyFXEw7fk4aKT1w9x_V/view?usp=drive_web>
 SpecLib_pqp.sptxt
<https://drive.google.com/file/d/1-JdKUawEnB3eIIApsq-TEaVeIbD0UaZc/view?usp=drive_web>

Warm regards,

*Ankit Balhara*
Ph.D. Student,
Dr. Saranjit Singh's Lab
Center for Drug Metabolism and Disposition,
Department of Pharmaceutical Analysis,
NIPER, S.A.S. Nagar,
Punjab-160 062, India.
Institute website: www.niper.gov.in

**Comment by grosenberger** [comment] 2019-02-05 13:18
Unfortunately, TPP PTM annotation support is limited in OpenMS, especially for less popular types. Also, TPP/SpectraST has sometimes own conventions that can make it very hard to provide consistent support.

If you have only few PTMs that need to be converted, my suggestion would be to replace them directly with the corresponding UniMod terms, as this will make conversion much easier, especially if you also have C-/N-term PTMs, where the TPP nomenclature can be ambiguous sometimes.

**Comment by hroest** [comment] 2019-02-05 15:12
Yes, the problem is clearly the Q[111] and C[143] in your data. It looks like this is a bug / incompatibility with TPP in OpenMS with N-terminal modifications in as it does not properly place them they way they are written here. OpenMS interprets these modifcations as non N-terminal and these are not recognized by OpenMS and lead to issues, I think because it does not properly recognize these N-terminal modifications. There are multiple ways around that 

- remove those peptides from your files
- replace the mass designation with the correct unimod designation (e.g. replace `Q[111]GGG` with `(UniMod:28)QGGG` and  `C[143]GGG` with `(UniMod:26)CGGG`) by opening the file in a text editor and doing a search and replace
- change your  `unimod.xml` (in `./share/OpenMS/CHEMISTRY/unimod.xml`) file as follows


```
                record_id="26">
         <umod:specificity hidden="0" site="C" position="Any N-term" classification="Artefact"
```

becomes

```
                record_id="26">
         <umod:specificity hidden="0" site="C" position="Anywhere" classification="Artefact"
```


and 


```
                record_id="28">
         <umod:specificity hidden="0" site="Q" position="Any N-term" classification="Artefact"
```

becomes 

```
                record_id="28">
         <umod:specificity hidden="0" site="Q" position="Anywhere" classification="Artefact"
```


I think the second option is the easiest for you

**Comment by hroest** [comment] 2019-02-05 16:15
the issue should now be addressed in https://github.com/OpenMS/OpenMS/pull/3957 and should be fixed in the next release of OpenMS

**Comment by Ankit-Balhara** [comment] 2019-02-05 18:25
Hi Hannes,

Thank you so much for your help. Option 2 worked for me.

Ankit.

**Closed** 2019-02-05 21:11 UTC
