### ISSUE TITLE
FeatureFinderIdentification problem

### ISSUE THREAD

**Issue by wenbostar** [OpenMS/OpenMS#3287] opened 2018-03-07 21:08 UTC
Hi,

I wanted to use FeatureFinderIdentification for XIC extraction for targeted peptides. I did retention time prediction (match between run) using an in-house tool and generated two files (test.idXML and test_match_ext.idXML) for tool FeatureFinderIdentification. The command line is shown below:

```
FeatureFinderIdentification -in test.mzML -id test.idXML -id_ext test_match_ext.idXML -out test.featureXML -extract:n_isotopes 3 -detect:peak_width 40 -model:type symmetric -extract:mz_window 20 -extract:rt_window 120 -log 0
```

But I got the following error:

```
Loading input data...
Progress of 'loading spectra list':
-- done [took 2.42 s (CPU), 2.55 s (Wall)] --
Progress of 'loading chromatogram list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] --
Realigning internal and external IDs...Error: Unexpected internal error (No reference RT information left after filtering)

```
It seems that FeatureFinderIdentification requires some overlapped peptides between test.idXML and test_match_ext.idXML. But in my case, I have done match between run using an in-house tool and the retention time information in test_match_ext.idXML has been corrected. How can I make FeatureFinderIdentification work in this case?

Bo

**Comment by hendrikweisser** [comment] 2018-03-08 10:24
> It seems that FeatureFinderIdentification requires some overlapped peptides between test.idXML and test_match_ext.idXML.

That is true. The overlap is required to estimate the uncertainty in the RT positions of the "external" peptides. In DDA experiments you generally have overlapping peptides (identified in several samples) anyway. Are they removed by your in-house RT prediction tool? If so, could you just change this behaviour?

Alternatively, you can treat the "external" peptides as if there were no uncertainty in their RT positions. In that case, just merge your two idXML files and consider all peptides as "internal" (input parameter "id"). However, you risk making (more) false-positive assignments if the assumption of "no uncertainty" doesn't hold.

**Comment by wenbostar** [comment] 2018-03-08 15:47
Hi @hendrikweisser , thanks a lot. 

> Are they removed by your in-house RT prediction tool? 

Yes. The overlapped peptides are removed because I have done the RT prediction.

> If so, could you just change this behaviour?

In my pipeline, I aligned one sample to all other samples (more than 50 in my case) to get the external peptides. So only external peptides are included in this file: test_match_ext.idXML. It's not easy to include all the related peptides in this file.

Could you please add an option (a new command line parameter) to FeatureFinderIdentification so that estimating the uncertainty of RT can be optional? It would be very useful in the case like that I have.

**Comment by hendrikweisser** [comment] 2018-03-08 17:05
> It's not easy to include all the related peptides in this file.

Why is that? Does the file get too big?

> Could you please add an option (a new command line parameter) to FeatureFinderIdentification so that estimating the uncertainty of RT can be optional? It would be very useful in the case like that I have.

The only reason for distinguishing between "internal" and "external" peptide identifications is that you can be certain about the "internal" RTs, but there's uncertainty associated with the "external" ones. If you want to ignore that uncertainty, just do what I suggested above and merge them with the "internal" ones. In that sense, estimating the uncertainty is already optional. It wouldn't make sense to add a parameter for it.

**Comment by timosachsenberg** [comment] 2018-03-08 18:25
Hendrik would -force flag to continue be an option?

**Comment by timosachsenberg** [comment] 2018-03-08 18:25
Every tool has it

**Comment by wenbostar** [comment] 2018-03-08 19:22
Hi @hendrikweisser , thanks again.

> Why is that? Does the file get too big?

There are two reasons. The first one is that I will have to do RT prediction for the overlapped peptides  and put these information into the external idXML file. This step will take a lot of running time since I have a lot of samples and fractions. It seems it's kind of redundant processing after I do the RT prediction outside of OpenMS (it might not be true). The second one is that the file get too big since there are more than 50 samples (for each sample, there are 15 fractions) in my case. Hope it makes sense to you.

Merging both "internal" and "external" files into one "internal" file might not be a good option in my case. If I do that then I cannot use the SVM evaluation model implemented in FeatureFinderIdentification to control the FDR.

**Comment by wenbostar** [comment] 2018-03-08 19:24
@timosachsenberg , thanks. I tried to add -force flag. But I got the same error.

**Comment by timosachsenberg** [comment] 2018-03-09 06:52
@hendrikweisser sorry my comment was a bit short (from mobile).
If we want to run FFid automatically I think it would be beneficial to e.g. fall back to the internal Ids only approach if no alignment can be found. As I understood it the tools just errors out.
If you think this is a bad default behavior the -force flag would be an option to overwrite the strict error-out behavior to continue processing.

**Comment by hendrikweisser** [comment] 2018-03-09 15:00
I've thought about this some more. In the case that "internal" (parameter "id") and "external" (parameter "id_ext") IDs are given, but there is no overlap, there would be these options:
1. Abort with an error (current behaviour).
2. Run only with the "internal" IDs, ignoring the "external" ones (conservative, but would avoid the error).
3. Merge "internal" and "external" IDs, treat them all as "internal" (again no error, but anti-conservative).
4. Change the algorithm to not use RT information from "external" IDs, except to define the chromatogram extraction window (what @wenbostar requested; would allow FDR estimation).

@timosachsenberg: I'm not sure if you were suggesting alternative 2 or 3. I would be okay with 2 (especially with "-force"), but not with 3. The reason is that option 3 would do something that the user probably didn't intend and that could lead to overly optimistic results.

The algorithm could probably be changed to work without "external" RTs after the chromatogram extraction (option 4). What you would lose is a) estimation of the RT extraction window (parameter "extract:rt_window"), and b) use of the RT feature in the SVM. The problem with b) is that the RT feature can be very informative. If your chromatography is stable (or your RT correction/prediction is good), you would probably get worse results by using the SVM without RT than by merging "internal"/"external" IDs (and incurring some false-positives). That's what happened on my example data when I developed the algorithm and was the reason for introducing the RT feature in the first place!

So option 4 could be implemented and I'm not against that, but I doubt that it would help in many cases. And I don't have the time for it.

@wenbostar: Having some overlap between "internal" and "external" IDs allows FFId to estimate how well your RT correction/prediction worked, which is very useful information. So I would suggest (again) to do the RT prediction at least for some of the "internal" peptides - you can take a random sample - and include them in the output.

**Comment by wenbostar** [comment] 2018-03-13 15:10
@hendrikweisser , thank you very much for your suggestions. I will go with this suggestion: Having some overlap between "internal" and "external" IDs. It makes sense.

**Comment by timosachsenberg** [comment] 2018-03-15 10:56
I think option 2 would be a good.
I personally would prefer to just output a warning that the external ids can't be used.
But I would leave this to you whether you think the force flag is necessary.

**Comment by hendrikweisser** [comment] 2018-03-15 13:45
I just looked at the FFId code again. Actually, most of the handling for option 4 is already in there! It gets triggered if there is overlap between "internal" and "external" IDs, but the RT alignment of the two fails (for whatever reason). See the error message here: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L237
In this case (internal + external IDs, but no alignment), this branch is not entered: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L854. This means the "rt_delta" meta value is not written to feature candidates, and thus the RT feature is not used in the SVM classification (https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L1121).

So in order to make option 4 work, the `try` entry point [here](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L230) would only have to be moved up to include the `aligner.align` call ([here](https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L224)).

The remaining problem in that case is that `rt_uncertainty` is not estimated properly, which is later used to calculate the RT extraction window: https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/TRANSFORMATIONS/FEATUREFINDER/FeatureFinderIdentificationAlgorithm.cpp#L246  
This is only relevant if `rt_window_` wasn't set directly by the user (via parameter `extract:rt_window`). The code should still work anyway, but perhaps we could come up with a better initialization for `rt_uncertainty` for that case.

@timosachsenberg: I think making this change to enable option 4 would be better than having option 2, since you get additional results for the "external" peptides.

@wenbostar: Even if we make this change, having some overlap between internal and external IDs would be the better solution, because it will give you better results.

**Comment by timosachsenberg** [comment] 2018-03-15 14:02
I thought you had some "doubt that it would help in many cases." ;) Totally fine with me then....

**Comment by hendrikweisser** [comment] 2018-03-15 15:04
> I thought you had some "doubt that it would help in many cases." ;)

That was before I saw that the code is basically already there. ;-)

In all seriousness, based on the validation I did for the FFId paper, the order of results - from best to worst - is as follows:
1. With "internal" and "external" IDs combined using machine learning (incl. RT feature)
2. With "internal" and "external" IDs merged (treating "external" as "internal")
3. With "internal" and "external" IDs combined using machine learning (without RT feature)
4. With "internal" IDs only

So as I said, if you have reproducible RTs you're better off just merging IDs from different runs. However, if you're going for the machine learning approach, then doing that without the RT feature is a better fall-back option than using only "internal" IDs.

**Closed** 2020-04-30 09:53 UTC
Labels: TOPP, question, wontfix
