### ISSUE TITLE
windows build instruction rendering issue 

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#6533] opened 2022-12-06 11:08 UTC
![image](https://user-images.githubusercontent.com/5803621/205895714-39b6d503-2860-41b8-883e-0f376bc03a91.png)

**Comment by timosachsenberg** [comment] 2022-12-06 11:09
https://abibuilder.cs.uni-tuebingen.de/archive/openms/Documentation/nightly/html/install_win.html

**Comment by cbielow** [comment] 2022-12-06 12:33
I cannot reproduce this on Windows :/
using 
 **doxygen 1.8.16**
on my machine

**Comment by timosachsenberg** [comment] 2022-12-06 12:54
thanks for checking... let's wait for next nightlies

**Comment by jpfeuffer** [comment] 2022-12-06 12:55
nightlies are not working due to packaging

**Comment by cbielow** [comment] 2022-12-07 21:43
I can reproduce this with the latest doxygen (1.9.5). Fixed in #6540 (do not use pipes :) )

**Closed** 2022-12-08 08:18 UTC
Labels: blocker
