### ISSUE TITLE
TOPPView is not opening on macOS 12.6 (M1 Pro cpu)

### ISSUE THREAD

**Issue by lfnothias** [OpenMS/OpenMS#6433] opened 2022-11-02 16:02 UTC
I have tried with OpenMS-3.0.0-pre-nightly-2022-04-01 and OpenMS-3.0.0-pre-nightly-2022-10-31
but the opening of TOPPView is pending. When opening it via the terminal I am seeing: 
```
% /Applications/OpenMS-3.0.0-pre-nightly-2022-10-31/TOPPView.app/Contents/MacOS/TOPPView ; exit;
An OpenGL surfcace format was requested that is either not version 3.2 or higher or a not Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.
```
Note that TOPPAS and INIFileEditors are opening correctly.

Any suggestions ?

**Comment by tjeerdijk** [comment] 2022-11-02 17:02
You can try to remove Apple’s quarantine as follows
cd  /Applications/OpenMS-<version>
sudo xattr -r -d com.apple.quarantine *

And then run TOPPView. Works on my M1 Pro MacBook with OpenMS-3.0.0-pre-nightly-2022-10-31 under MacOS 12.6

Take care from Tjeerd

On 2. Nov 2022, at 17:02, lfnothias ***@***.******@***.***>> wrote:

I have tried with OpenMS-3.0.0-pre-nightly-2022-04-01 and OpenMS-3.0.0-pre-nightly-2022-10-31
but the opening of TOPPView is pending. When opening it via the terminal I am seeing:

% /Applications/OpenMS-3.0.0-pre-nightly-2022-10-31/TOPPView.app/Contents/MacOS/TOPPView ; exit;
An OpenGL surfcace format was requested that is either not version 3.2 or higher or a not Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.


Note that TOPPAS and INIFileEditors are opening correctly.

Any suggestions ?

**Comment by lfnothias** [comment] 2022-11-02 17:50
Thanks @tjeerdijk !
I tried but it didn't work.

**Comment by tjeerdijk** [comment] 2022-11-02 18:21
Strange. Can you double check that you removed the com.apple.quarantine extended attribute? You need to go to the macOS binary in the app bundle "cd /Applications/OpenMS-3.0.0-pre-nightly-2022-10-31/TOPPView.app/Contents/MacOS" and then run "xattr -l TOPPView"

**Comment by jpfeuffer** [comment] 2022-11-02 18:55
I suspect an error with the new tool scan mechanism. @timosachsenberg Do you have an idea how to check this, i.e. how to disable tool scanning?

**Comment by lfnothias** [comment] 2022-11-02 19:34
I am getting this with `% xattr -l TOPPView`
```
com.apple.lastuseddate#PS: ?bc
```

**Comment by tjeerdijk** [comment] 2022-11-02 19:47
That is the same output as I get. So you successfully removed the quarantine extended attribute.

Can you try the “usual" tech help, a reinstall of OpenMS. (Sorry not very specific but I cannot reproduce your error on my M1 Pro MacBook).

Can you (still) open the other applications, like TOPPAS and INIFileEditor?

On 2. Nov 2022, at 20:34, lfnothias ***@***.******@***.***>> wrote:



I am getting this with % xattr -l TOPPView

com.apple.lastuseddate#PS: ?bc

**Comment by lfnothias** [comment] 2022-11-04 15:50
I tried reinstall and reboot. Then removed the Apple's quarantine again, but same issue.
@tjeerdijk Are you also running macOS 12.6 ?

**Comment by jpfeuffer** [comment] 2022-11-04 18:20
Hi,
can you try running it with "--skip_tool_check" with the nightlies tomorrow?
Still waiting for @timosachsenberg s input on this, though. Could be a potential blocker for the release.

**Comment by lfnothias** [comment] 2022-11-06 16:24
Thanks @jpfeuffer. I have just tested opening TOPPView from the prenightly-2022-11-05 after removing quarantine (`sudo xattr -r -d com.apple.quarantine *`) doing the following:
`./TOPPView --skip_tool_check` and that gave me 
`Unknown option(s) '[--skip_tool_check]' given. Aborting!`
Maybe I am not using this parameter correctly ?

**Comment by jpfeuffer** [comment] 2022-11-06 16:32
Ah Sorry. It is --skip_tool_scan

**Comment by lfnothias** [comment] 2022-11-06 16:50
Thanks. It is now loading but still staying stuck like before.

**Comment by tjeerdijk** [comment] 2022-11-14 21:22
I have checked with another person who also has an M1 Pro MacBook under MacOS 12.6. She has to run TOPPView by opening the TOPPView.app package (right click and the "open package contents") and go to the MacOS folder (surf down a bit) and the run TOPPView from there. Maybe that helps?

**Comment by alhigaylan** [comment] 2022-11-16 20:52
Hello! I want to affirm that @tjeerdijk suggestion worked like a charm for me! I also have M1 chip MacBook (MacOS v 12.3.1) and TOPPView version 2.7.0. I had a problem with TOPPView taking a very long time to launch (it takes ~ 10 min) to open the app itself. 

 Tried the suggestion above. Right click on TOPPView --> Show package content --> Content --> MacOS --> double click on TOPPView executable 

 It will launch a terminal window with the command 
 `/Applications/OpenMS-2.7.0/TOPPView.app/Contents/MacOS/TOPPView ; exit;`

 TOPPView launched in a second.

**Comment by jpfeuffer** [comment] 2022-11-16 21:21
Can you guys try moving the apps out of the OpenMS-3.0.0 folder and back again?
It might be one of macs dozen security measures: path randomization.

But I really thought that with removing the quarantine attributes, this should also go away.

**Comment by lfnothias** [comment] 2022-11-18 09:44
Still no improvement on my side. Weird, it must something specific with my computer environment. Thanks a lot for all the help. I am closing the issue.

**Comment by lfnothias** [comment] 2022-12-08 13:11
Just a followup, after leaving the software pending for several days, the TOPPView windows finally showed up !

**Comment by timosachsenberg** [comment] 2022-12-08 13:13
awesome the new self-healing feature

**Comment by Ayesha-Feroz** [comment] 2023-03-10 15:00
> Just a follow-up, after leaving the software pending for several days, the TOPPView windows finally showed up !

This actually happens in my Apple M1 Pro TOPPView was working fine a month ago but now it's not opening and even though I tried opening it with TOPPView.app/Contents/MacOS/TOPPView; I get a message like this.                                             
 'An OpenGL surface format was requested that is either not version 3.2 or higher or a not Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.

**Comment by jpfeuffer** [comment] 2023-03-31 08:49
So, we just received an M2 macMini with Ventura. I cannot reproduce any of this. Neither with a downloaded nightly DMG and applying `xattr -r -d ...`, nor with a self-built TOPPView.

**Comment by timosachsenberg** [comment] 2023-06-14 10:27
can you build it in debug mode and see if there is additional output on the command prompt?

**Comment by KyowonJeong** [comment] 2023-06-14 10:29
It will take some time but now building...

**Comment by timosachsenberg** [comment] 2023-06-26 13:52
@poshul you were able to build it and run the tests on M1 right?

**Comment by KyowonJeong** [comment] 2023-06-26 19:54
In the debugger, I see some strange value in XMLHandler.h line 252 (the spot where toppview freezes. Sorry I don't know how to make a direct link to this line). 
There in str a, very looong string is stored when opening Toppview:

u"Peptide Identification with MSFragger.#br#Important note:#br#The Regents of the University of Michigan (Ã\U00000083Â\U00000083Ã\U00000082Â\U00000083Ã\U00000083Â\U00000082Ã\U00000082Â\U00000083Ã\U00000083Â\U00000083Ã\U00000082Â\U00000082Ã\U00000083Â\U00000082Ã\U00000082Â\U00000083Ã\U00000083Â\U00000083Ã\U00000082Â\U00000083Ã\U00000083Â\U00000082Ã........... 

Check: https://capture.dropbox.com/EEuwPKmufUOlfEuG

I think the last part string is just garbage. Maybe this is the reason why Toppview freezes?

**Comment by timosachsenberg** [comment] 2023-06-26 21:09
hmm interesting: https://github.com/OpenMS/OpenMS/pull/6917
can you check out this quick fix?

**Comment by KyowonJeong** [comment] 2023-06-27 06:23
> hmm interesting: #6917 can you check out this quick fix?

It works! But you need to make sure to delete "~/.TOPPView.ini" to make this change effective!!

Thanks @timosachsenberg !!!

**Comment by KyowonJeong** [comment] 2023-06-27 06:27
One remaining issue is whenever I close Toppview, it crashes. But still it opens and runs well.

**Comment by timosachsenberg** [comment] 2023-06-27 06:50
I think TOPPView.ini is also written when TOPPView is closed. Can you debug into this and see if it crashes during writing?

**Comment by KyowonJeong** [comment] 2023-06-27 07:20
I could not see in debug mode yet, but one thing I see is that TOPPView.ini is not written when TOPView is closed. I will look into that why this is happening.

**Comment by KyowonJeong** [comment] 2023-06-27 07:25
OK, I rebuilt them all and this bug is gone. I cannot reproduce it. And TOPPview.ini is again well written when closing. I think this has been resolved.

**Closed** 2023-06-27 07:31 UTC
Labels: major
