### ISSUE TITLE
How to treat parameters with defaults in share on a linux command line

### ISSUE THREAD

**Issue by bernt-matthias** [OpenMS/OpenMS#4361] opened 2019-11-15 14:48 UTC
Still working of

Take for instance AccurateMassSearch and its ctd file:

```
      <ITEM name="positive_adducts" value="CHEMISTRY/PositiveAdducts.tsv" type="input-file" description="This file contains the list of potential positive adducts that will be looked for in the database. Edit the list if you wish to exclude/include adducts. By default CHEMISTRY/PositiveAdducts.tsv in OpenMS/share is used! If empty, the default will be used." required="true" advanced="false" supported_formats="*.tsv" />
```

The corresponding command line would be `-mapping CHEMISTRY/PositiveAdducts.tsv` which does not work since the path is not found in the working dir. 

Question is how to treat such defaults.

**Comment by cbielow** [comment] 2019-11-17 12:07
why `-mapping`?
It should be `-positive_adducts ...`, which does work on the command line as expected.

The TOPP tool uses the path to ./OpenMS/share internally to complete this filename, if it cannot be found using the filepath which is provided (i.e. you could also provide an absolute or relative path yourself).
then again, the path to ./OpenMS/share is baked into library, but can be overrriden by setting OPENMS_DATA_PATH in your environment (which can be the case when installing packages, e.g. on Windows).

**Comment by cbielow** [comment] 2019-11-17 12:10
Thus, a commandline like
`AccurateMassSearch.exe -in c:\temp\featureXML\QC_20140323_1_0.featureXML -out c:\temp\bla.mzTab -positive_adducts CHEMISTRY/PositiveAdducts.tsv` works just fine.

You can call OpenMSInfo to find out where the SHARE is expected, given the current system settings:
```
$ ..\openms_test_build\bin\Release\OpenMSInfo.exe
OpenMS Version:
==================
Version      : 2.4.0-disabled-20191028
Build time   : Oct 28 2019, 22:06:18
Git sha1     : disabled
Git branch   : disabled

Installation information:
==================
Data path    : c:/dev/openms_test/share/OpenMS
Temp path    : C:/Users/bielow/AppData/Local/Temp
Userdata path: C:/Users/bielow/

Build information:
==================
Source path  : C:/dev/openms_test/src/openms
Binary path  : C:/dev/openms_test_build/src/openms
Binary arch  : 64 bit

OS Information:
==================
Name: Windows
Version: 6.2
Architecture: 64 bit
```

**Comment by cbielow** [comment] 2019-11-17 12:11
closing for now. Please reopen if questions remain unanswered.

**Closed by cbielow** 2019-11-17 12:11 UTC

**Comment by bernt-matthias** [comment] 2019-11-17 13:24
Sorry for the confusion caused by my typo. 

I guess the main confusion is due to `required="true"` which suggests that its required to set the parameter on the command line. But actually the tool chooses `CHEMISTRY/PositiveAdducts.tsv` automatically if the parameter is not given.

This configuration (ie required="true" plus a non empty value) is only found for a few of the ctd files generated by the OpenMS tools (e.g. parameters specifying external tools). 

For the generation of the command line required="false" and value="" could be more useful (but I don not know how the OpenMS tools treat this when the ctd file is used as input). \

For the CTDConverter I will treat these inputs as if  required="false" and value="" would be set.

**Comment by cbielow** [comment] 2019-11-17 18:58
Not sure what happens during this conversion, but the following does not work
`AccurateMassSearch.exe ... -positive_adducts ""`
since it results in
`Error: The required parameter 'positive_adducts' [valid: tsv] was not given or is empty!`
(the documentation of the param says also empty values will use the default, but this is simply not true (by design of how TOPP tools enforce parameter validity.

Thus, if you to not mention the parameter, everything will be fine. But do not use an empty value if you need to specify it.
