### ISSUE TITLE
Getting rid of mzML parsing warnings by "fixing" the file

### ISSUE THREAD

**Issue by PaulPyl** [OpenMS/OpenMS#2569] opened 2017-04-28 09:11 UTC
Hi there,

I have some mzML files that generate a lot of warnings of the following types when processed with the command line tools, I observed this in e.g. the OpenSWATHWorkflow tool, the XTandemAdapter as well as in the FileConverter.

> <While loading 'xxx.mzML.gz': Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'> occurred 97296 times
> <While loading '/tmp/openswath_tmpfile_29.mzML': Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'> occurred 1520 times

I was wondering if there is a way of fixing this by applying the suggested changes and I tried to use the FileConverter with -in xxx.mzML.gz and -out yyy.mzML.gz but the "converted" file still has the same warnings about the CV term. Before the conversion there were also warnings about en encoding being unspecified and how 64bit was going to be used by default, they looked like this:

> <While loading 'xxx.mzML.gz': Invalid mzML format: Numpress-compressed binary data array 'intensity array' has no child term of MS:1000518 (binary data type) set. Assuming 64 bit float data type.> occurred 96 times

Those have been fixed by the conversion however. So essentially I am wondering why one type of warning is removed by converting but the other is not and if it is possible to make that happen?

If this is already possible I would be thankful if someone could give me an example command to achieve this?

Best,
Paul

**Comment by hroest** [comment] 2017-04-28 17:41
Hi Paul

the first issue is an error in OpenMS (more like an omission) and is addressed by #2570 but dont worry, its not in any way changing how the software works

The second issue is likely a problem of the software used to convert which does not adhere to the PSI standard. You should probably write to them but maybe you can copy-paste a single spectrum first to investigate where the problem really lies

**Closed** 2017-04-30 07:16 UTC
Labels: defect, minor

**Comment by hroest** [comment] 2017-05-02 17:14
Hi Paul

can you please send all input files including the iRT and library used? I have used a few other files from here http://www.peptideatlas.org/PASS/PASS00779 and I get the following

```
./release_2.1/bin/OpenSwathWorkflow -in /media/data/tmp/openms_issues/foo.mzML -tr /media/data/tmp/schubert_chapter/Mtb_TubercuList-R27_iRT_UPS_newDecoy.csv  -out_tsv /tmp/foo.tsv -out_chrom /tmp/foo.chrom.mzML -readOptions cache -tempDirectory /tmp/  -rt_extraction_window -1 -force
Since neither rt_norm nor tr_irt is set, OpenSWATH will not use RT-transformation (rather a null transformation will be applied)
Loading mzML file /media/data/tmp/openms_issues/foo.mzML using readoptions cache
Progress of 'Loading metadata file /media/data/tmp/openms_issues/foo.mzML':
While loading '/media/data/tmp/openms_issues/foo.mzML': Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'
Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
Determined there to be 3 SWATH windows and in total 0 MS1 spectra
Determined there to be 3 SWATH windows and in total 0 MS1 spectra
-- done [took 0.07 s (CPU), 0.07 s (Wall)] -- 
Progress of 'Loading data file /media/data/tmp/openms_issues/foo.mzML':
Read chromatogram while reading SWATH files, did not expect that!
[...]
-- done [took 0.73 s (CPU), 0.73 s (Wall)] -- 
<While loading '/tmp/openswath_tmpfile_1.mzML': Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'> occurred 2 times
Extraction will have a gap between 950.5 and 1049.5
Extraction will have a gap between 1075.5 and 1099.5
Progress of 'Load TraML file':
-- done [took 4.16 s (CPU), 4.32 s (Wall)] -- 
Will analyze 477335 transitions in total.
Progress of 'Extracting and scoring transitions':
Thread 0 will analyze 1749 compounds and 8745 transitions from SWATH 0 in batches of 1749
Thread 0 will analyze 922 compounds and 4610 transitions from SWATH 1 in batches of 922
Thread 0 will analyze 708 compounds and 3540 transitions from SWATH 2 in batches of 708
-- done [took 7.80 s (CPU), 7.83 s (Wall)] -- 
OpenSwathWorkflow took 13.19 s (wall), 13.00 s (CPU), 0.00 s (system), 13.00 s (user).
```

so it looks like thing are going well and I dont see any crashes. So at least it looks like your mzML file is working, maybe the issue with your iRT or library file?

**Comment by hroest** [comment] 2017-05-02 17:19
also note that the OpenSwathChromatogramExtractor is the wrong tool for the kind of file you provided, the tool basically assumes that you only have data from a specific swath window in your input foo.mzML but in your case you have multiple windows mixed in there. For the OpenSwathChromatogramExtractor you need to split your swath files first, so for this kind of input file the OpenSwathWorkflow would be be the right tool to use.

hmm unfortunately the error message is not very informative, if you look at line 85:

 85         throw Exception::IllegalArgument(__FILE__, __LINE__, OPENMS_PRETTY_FUNCTION, "Scan " + String(index) + " has a different precursor isolation window than the firs    t scan.");

which would tell you what is going on but in this case its not very informative at all. I need to investigate that

**Comment by PaulPyl** [comment] 2017-05-02 17:43
Hi Hannes,

I see, the info on Line 85 is indeed more helpful than the message printed in the command output, although in this case I am not sure how to interpret it.

I attach [here](https://github.com/OpenMS/OpenMS/files/971370/RT-peptides.and.spectral-library.zip) the two other input files for the OpenSwathWorkflow run:

- RT-peptides in traml format 
- the spectral library I generated from the DDA runs corresponding to the samples in my study (the sample from which the foo.mzML file was generated is one of 64 that went into generating the spectral library)

The spectral library was generated using the steps outlined in the OpenSwath tutorial. I stopped before the ConvertTSVToTraml step because of the following error (I think this issue might relate to issue #2505 and I haven't attempted it with a nightly build yet so it is possible that this was fixed in #2428):

```
paul@Cthulhu:/deadpool/projects/paul/M3/Interact/Standard$ ConvertTSVToTraML -in outputlibrary.csv -out test.traml
Reading outputlibrary.csv
Progress of 'converting to TraML format':
Error: Unexpected internal error (The value 'UniMod:27' was used but is not valid! Retrieving the modification failed. It is not available for the residue 'E' and term specificity 0.)
```
Since the OpenSwathWorkflow doesn't require the library to be traml I tried with the file anyway but I guess it is possible that something is wrong with the library still.

I had gotten the OpenSwathCromatogramExtractor step from the example OpenSwath workflow bash file but I guess I didn't read it carefully enough :(

Thanks,
Paul

**Comment by hroest** [comment] 2017-05-02 17:56
obviously with your sample input, the iRT re-calibration will not work:

```
$ ./release_2.1/bin/OpenSwathWorkflow -in /media/data/tmp/openms_issues/foo.mzML -tr /media/data/tmp/openms_issues/outputlibrary.tsv  -out_tsv /tmp/foo.tsv -out_chrom /tmp/foo.chrom.mzML -readOptions cache -tempDirectory /tmp/  -rt_extraction_window -1  -tr_irt /media/data/tmp/openms_issues/iRT-peptides-escher.traml -force
Will load iRT transitions and try to find iRT peptides
Progress of 'Retention time normalization':
Error: Unexpected internal error (unknown error)
```

but I also saw some problems with UniMod 27 and 28 which I think are unfortunately on our side, so if you remove these then I got it to work like this:
```
$ grep -v ':28'  /media/data/tmp/openms_issues/outputlibrary.csv | grep -v ':27' > /media/data/tmp/openms_issues/outputlibrary_new.tsv 
$ ./release_2.1/bin/OpenSwathWorkflow -in /media/data/tmp/openms_issues/foo.mzML -tr /media/data/tmp/openms_issues/outputlibrary_new.tsv  -out_tsv /tmp/foo.tsv -out_chrom /tmp/foo.chrom.mzML -readOptions cache -tempDirectory /tmp/  -rt_extraction_window -1   -force
[...]
Will analyze 4679 transitions in total.
Progress of 'Extracting and scoring transitions':
Thread 0 will analyze 18 compounds and 108 transitions from SWATH 0 in batches of 18
Thread 0 will analyze 10 compounds and 60 transitions from SWATH 1 in batches of 10
Thread 0 will analyze 7 compounds and 42 transitions from SWATH 2 in batches of 7
-- done [took 0.11 s (CPU), 0.10 s (Wall)] -- 
OpenSwathWorkflow took 1.11 s (wall), 1.10 s (CPU), 0.00 s (system), 1.10 s (user).
```

**Comment by PaulPyl** [comment] 2017-05-02 19:56
Hi Hannes,

thanks for the quick reply, so I can try with removing those modifications as a quick fix? I am new to the field but I assume I would like to keep them in the spectral library if possible?

Is there an issue with the way I have generated the library that would cause this or is it something that happens in OpenMS itself? I used a much older release on another server (version 1.11 I believe) and there the UniMod errors had not occurred.

When I remove them from the spectral library and also not provide the retention time peptides the OpenSwathWorkflow runs on my full-sized input file. When I provide the retention time peptides I get another unknown error (output shortened again):

```
Loading mzML file JM-M3-10.mzML.gz using readoptions cache
Progress of 'Loading metadata file JM-M3-10.mzML.gz':
While loading 'JM-M3-10.mzML.gz': Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'
Will analyze the metadata first to determine the number of SWATH windows and the window sizes.
Determined there to be 32 SWATH windows and in total 1521 MS1 spectra
Determined there to be 32 SWATH windows and in total 1521 MS1 spectra
-- done [took 23.95 s (CPU), 25.60 s (Wall)] -- 
Progress of 'Loading data file JM-M3-10.mzML.gz':
Read chromatogram while reading SWATH files, did not expect that!
While loading 'tmp/openswath_tmpfile_0.mzML': Name of CV term not correct: 'MS:1000422 - high-energy collision-induced dissociation' should be 'beam-type collision-induced dissociation'
[...]
Extraction will overlap between 1175.5 and 1174.5
This will lead to multiple extraction of the transitions in the overlapping regionwhich will lead to duplicated output. It is very unlikely that you want this.
Please fix this by providing an appropriate extraction file with -swath_windows_file
Will load iRT transitions and try to find iRT peptides

---------------------------------------------------
FATAL: uncaught exception!
---------------------------------------------------
last entry in the exception handler: 
exception of type Exception occured in line 145, function const T& OpenMS::Map<Key, T>::operator[](const Key&) const [with Key = OpenMS::String; T = std::vector<OpenMS::CVTerm>] of /deadpool/software/sources/OpenMS-2.1.0/src/openms/include/OpenMS/DATASTRUCTURES/Map.h
error message: unknown error
---------------------------------------------------
```
Best,
Paul

**Comment by PaulPyl** [comment] 2017-05-02 19:58
Seems the error is because a key is looked up in a Map that is not in it (or so I gather from a quick look at line 145 in that file), but I can't tell which Map / what type of key that would be.

**Comment by hroest** [comment] 2017-05-02 20:11
Hi Paul

yes, you can try without these and remove them like this:

```
$ grep -v ':28'  /media/data/tmp/openms_issues/outputlibrary.csv | grep -v ':27' > /media/data/tmp/openms_issues/outputlibrary_new.tsv 
```

I cant really help you with the Map problem as the issue is quite unspecific. If you do not provide the iRT peptide library you should see a warning like 
```
Since neither rt_norm nor tr_irt is set, OpenSWATH will not use RT-transformation (rather a null transformation will be applied)
```

do you see that?

**Comment by hroest** [comment] 2017-05-02 20:18
also, another fix you could use is the replace 
```
Q(UniMod:28)VSGIGEKTLEK
```

with 
```
.(UniMod:28)QVSGIGEKTLEK.
```

note the two dots which indicate N/C termini and now OpenMS will actually properly parse it (only works in newer OpenMS versions). Do the same for UniMod:27 -- or just remove those peptides from the library as shown above

**Comment by PaulPyl** [comment] 2017-05-02 21:08
Indeed I see the message about the null-transformation being applied when I do not supply the RT peptides.

I will try out the reformatting of the peptide modifications. This might be a simple question but I was looking at the traml format specification document and was wondering if there is a similar document specifying the way the spectral library should be formatted in the TSV file?

I have now narrowed it down to the iRT Traml file being the source of the remaining issue:

```
paul@Cthulhu:/deadpool/projects/paul/M3/OpenSWATH$ ConvertTraMLToTSV -in /mnt/common/RTpeptides/iRT-peptides-escher.traml -out iRT-peptides-escher.csv -debug 10
Debug level: 10
 >> ConvertTraMLToTSV -in /mnt/common/RTpeptides/iRT-peptides-escher.traml -out iRT-peptides-escher.csv -debug 10
Value of string option 'test': 0
Log file: 
Writing to ''
Debug level (after ini file): 10
Value of string option 'no_progress': 0
Value of string option 'in': /mnt/common/RTpeptides/iRT-peptides-escher.traml
Checking input file '/mnt/common/RTpeptides/iRT-peptides-escher.traml'
Value of string option 'out': iRT-peptides-escher.csv
<Checking input file '/mnt/common/RTpeptides/iRT-peptides-escher.traml'> occurred 2 times
Checking output file 'iRT-peptides-escher.csv'
Reading /mnt/common/RTpeptides/iRT-peptides-escher.traml
While loading '/mnt/common/RTpeptides/iRT-peptides-escher.traml': Name of CV term not correct: 'MS:1001141 - precursor ion intensity' should be 'intensity of precursor ion'
Progress of 'converting to OpenSWATH transition TSV format':
Error: Unexpected internal error (unknown error)
<Checking output file 'iRT-peptides-escher.csv'> occurred 2 times
Error occurred in line 145 of file /deadpool/software/sources/OpenMS-2.1.0/src/openms/include/OpenMS/DATASTRUCTURES/Map.h (in function: const T& OpenMS::Map<Key, T>::operator[](const Key&) const [with Key = OpenMS::String; T = std::vector<OpenMS::CVTerm>]) !
```

I think this file has been around in the lab for many years so I assume that it is possible that it might have been created before the latests traml specification was released.
Indeed when I try the above command with OpenMS version 1.11.1 it converts it to csv (or rather tsv that is called .csv without error/warning).
When I convert to .csv with OpenMS 1.11.1 and then back to traml with OpenMS 2.1.0 the resulting traml file does not create the error in the OpenSwathRTNormalizer and instead the program fails because it can't use any of the RT transitions, the errors are like this:

```
[...]
Error: Transition YILAGVENSK_2_y4 from group YILAGVENSK_2 does not have a corresponding chromatogram
Error: Transition YILAGVENSK_2_b2 from group YILAGVENSK_2 does not have a corresponding chromatogram
Error: Transition YILAGVENSK_2_y5 from group YILAGVENSK_2 does not have a corresponding chromatogram
Will analyse 0 peptides with a total of 54 transitions 
Error: Unexpected internal error (Need at least 2 points for the regression.)
```

I will look into creating a new iRT.traml file but I still want to ask if this error message means that the issue is with the iRT.traml file it means that the RT peptides found in my input data .mzML.gz file have an issue?

**Comment by hroest** [comment] 2017-05-03 00:13
the tsv format is not really standardized so its OpenMS internal only. There is some documentation here http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/UTILS_TargetedFileConverter.html

sems like the error is now at least better specified ... but to me it is not clear why you are not getting any chromatograms extracted , this seems to be the main problem here.
