### ISSUE TITLE
How to get type hints with pyopenms

### ISSUE THREAD

**Issue by PierreSnell** [OpenMS/OpenMS#6559] opened 2022-12-15 22:31 UTC
First, thanks a lot for this wonderful toolbox! 

I started to use PyOpenMs but vscode (and pylance, the python extension) keeps complaining about unknown types. 

However, I saw that some pyi (type hints) were generated : https://github.com/OpenMS/autowrap/pull/119.
But I can't find them in the develop branch.  

Is it possible to have them somewhere in the release/dist so I can point the type checker (or it can find it automatically) to them and have a wonderful developer experience? (or a git repo to clone) 

Thanks in advance for any help or update,
Have a great day.

**Comment by PierreSnell** [comment] 2022-12-15 23:20
EDIT : I installed the nightly build and the `.pyi` are here and typing are present ! :D

However, in the typings, `unicode` and `String` are not defined.

**Comment by jpfeuffer** [comment] 2022-12-16 00:16
Cool! Glad that it worked. Typehints are indeed rather recent. There is definitely room for improvement.

There is an issue for the unicode type and other small ones. https://github.com/OpenMS/autowrap/issues/164
Unicode probably should just be removed since we do not support python2 anymore.

**Comment by jpfeuffer** [comment] 2022-12-16 12:42
Will close as duplicate of the autowrap issue but regarding type hints, keep the issue reports coming, it is hard to test that automatically.

**Closed by jpfeuffer** 2022-12-16 12:42 UTC
