### ISSUE TITLE
mzML files generated by ProteoWizard are not parsed correctly

### ISSUE THREAD

**Issue by alexeigurevich** [OpenMS/OpenMS#4294] opened 2019-10-11 10:31 UTC
It seems that `sourceFileList` attribute of an mzML file is skipped if the file was produced by [ProteoWizard](http://proteowizard.sourceforge.net/tools/msconvert.html) `msconvert` utility. This is crucial for e.g. `SiriusAdapter` tool since it calls `SiriusMSFile::store` from `SiriusMSConverter.cpp` which has the following line
```
ainfo.sf_path = spectra.getSourceFiles()[0].getPathToFile();
```
that will cause _undefined behavior_ since spectra.getSourceFiles() returns an empty vector in this case. In most cases it would lead to Segmentation Fault.

A minimal example reproducing the problem:
```
> SiriusAdapter -in sample.mzML
Progress of 'loading spectra list':
-- done [took 0.00 s (CPU), 0.00 s (Wall)] -- 
Number of MS2 spectra to be processed: 1
Segmentation fault: 11
```
(SiriusAdapter Version: 2.4.0-develop-2019-09-23 Sep 23 2019, 11:48:11, Revision: b1bde16)

This spectrum file was retrieved from a simple MGF file using the following command:
```
msconvert sample.mgf
```
(ProteoWizard release: 3.0.7692 (2015-6-23))

Attached is [sample.zip](https://github.com/OpenMS/OpenMS/files/3717035/sample.zip) including both `sample.mgf` and `sample.mzML`.

Current workaround: 
```
>FileConverter -in sample.mzML -out sample.fixed.mzML
>SiriusAdapter -in sample.fixed.mzML
```

**Comment by oliveralka** [comment] 2019-10-12 05:38
I am trying to debug, but did not reach a conclusion yet.
For everyone who is interested. The issue may be related to the MzMLHandler. It seems that the file is read correctly in the beginning.
```
        line 913
        source_files_[current_id_].setNameOfFile(name_of_file);
        source_files_[current_id_].setPathToFile(path_to_file);
```
While debugging the filename and path is parsed correctly, but in the loaded MsExperiment, the sourceFiles vector is empty. It has to be lost/overwritten in between.

**Comment by hroest** [comment] 2019-10-13 01:48
note that in the mzML the `run` should reference a specific source file: http://www.peptideatlas.org/tmp/mzML1.1.0.html#run however the mzML in the sample does not reference any source file and thus the parsed source files are not stored:

https://github.com/OpenMS/OpenMS/blob/51851d4e6eeca92ae2942ddcb63e95aefe0ceff8/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L1033-L1038

In other words, the problem is that source file `sourceFile id="scan_1438.mgf" ` is in the mzML file but is never referenced in the mzML file itself

**Comment by hroest** [comment] 2019-10-13 01:52
PS: we should look into all these cases of using the source file vector:

```
$ grep -R getSourceFiles src/openms | grep '\[0'
src/openms/source/FORMAT/MascotGenericFile.cpp:      native_id_type_accession = experiment.getExperimentalSettings().getSourceFiles()[0].getNativeIDTypeAccession();
src/openms/source/FORMAT/HANDLERS/MzDataHandler.cpp:           << "\t\t\t\t<nameOfFile>" << cexp_->getSourceFiles()[0].getNameOfFile() << "</nameOfFile>\n"
src/openms/source/FORMAT/HANDLERS/MzDataHandler.cpp:           << "\t\t\t\t<pathToFile>" << cexp_->getSourceFiles()[0].getPathToFile() << "</pathToFile>\n";
src/openms/source/FORMAT/HANDLERS/MzDataHandler.cpp:        if (cexp_->getSourceFiles()[0].getFileType() != "")
src/openms/source/FORMAT/HANDLERS/MzDataHandler.cpp:          os << "\t\t\t\t<fileType>" << cexp_->getSourceFiles()[0].getFileType() << "</fileType>\n";
src/openms/source/ANALYSIS/ID/SiriusMSConverter.cpp:    ainfo.sf_path = spectra.getSourceFiles()[0].getPathToFile();
src/openms/source/ANALYSIS/ID/SiriusMSConverter.cpp:    ainfo.sf_type = spectra.getSourceFiles()[0].getFileType();
src/openms/source/ANALYSIS/ID/SiriusMSConverter.cpp:    ainfo.native_id_accession = spectra.getSourceFiles()[0].getNativeIDTypeAccession();
src/openms/source/ANALYSIS/ID/SiriusMSConverter.cpp:    ainfo.native_id_type = spectra.getSourceFiles()[0].getNativeIDType();
```

**Comment by timosachsenberg** [comment] 2019-10-14 14:42
correct:
```
          <precursorList count="1">
            <precursor spectrumRef="scan=1">
              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="391.283569335938" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </selectedIon>
              </selectedIonList>
              <activation>
                <cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="26.1322861" unitCvRef="UO" unitAccession="UO:0000266" unitName="electronvolt"/>
                <cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" value=""/>
              </activation>
            </precursor>
          </precursorList>
```
wrong:
```
				<precursorList count="1">
					<precursor spectrumRef="scan=1">
						<activation>
							<cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" />
							<cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="26.132286100000002" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO"/>
						</activation>
					</precursor>
				</precursorList>
```

**Comment by oliveralka** [comment] 2019-10-14 15:01
The first issue is as @hroest pointed out the missing `sampleRef="sa_0" defaultSourceFileRef="sf_ru_0"` in the run tag. 

We tried to "fix" this by converting the msconvert.mzML again using the OpenMS FileConverter to mzML (mzML-mzML_fileconv-mzML). This lead to a loss of precursor Mz annotation at the ms2 level. Please see the post of @timosachsenberg above.

When the original.mzXML is converted using the OpenMS FileConverter everything is converted correctly. 

msconvert:
![msconvert](https://user-images.githubusercontent.com/15729190/66761032-85009a80-eea3-11e9-842f-048ecd7f45eb.png)
mzML to mzML:
![mzML-mzML](https://user-images.githubusercontent.com/15729190/66761041-89c54e80-eea3-11e9-9c93-327f7080844d.png)
mzXML to mzML:
![mzXML-mzML](https://user-images.githubusercontent.com/15729190/66761052-8cc03f00-eea3-11e9-836f-e663c49ffe24.png)


@jpfeuffer @hendrikweisser 
Do you have by chance have an idea, what the issue could be?

**Comment by jpfeuffer** [comment] 2020-03-10 21:30
@oliveralka what is the status here?

**Comment by oliveralka** [comment] 2020-08-04 08:12
For the second issue - the loss of selected ion m/z  / precursor mz (as shown by Timo above).

```
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="391.283569335938" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </selectedIon>
```

It seems that this can be resolved by setting the  `-force_TPP_compatibility` in the FileConverter.

@cbielow I am not sure what kind of conventions there are in regard to mzML conversion. Would it be better to resolve a zero precursor mz by setting the selected ion m/z in any case - not only by forcing TPP compatibility? Since the selected ion m/z is the only value in regard to the precursor reported in the msconvert mzML. Or is this maybe a different edge case due to the different conversions, since the mzXML to mzML conversion of the FileConverter works without any issues. 

Have a look here for the example data:
https://drive.google.com/drive/folders/1UkKLY_LzMqr4y5jViOaI7wsxRHkyrhIL?usp=sharing

**Comment by jpfeuffer** [comment] 2020-08-04 09:27
Can you give a summary of what the issues are now, on our side and on the msconvert side?

**Comment by oliveralka** [comment] 2020-08-04 10:02
There are two issues here:

1) SourceFile issue - if the SourceFile is not reported correctly, then SiriusAdapter segfaults since it depends on the information. I still have to see how to fix that issue. 

2) Precursor information gets lost when converting a msconvert.mzML via the FileConverter to a fileconverter.mzML without the `-force_TPP_compatibility` flag. 

mzXML:
`<precursorMz precursorIntensity="0" activationMethod="HCD">391.283569335938</precursorMz>`
msconvert:
```
          <precursorList count="1">
            <precursor spectrumRef="scan=1">
              <selectedIonList count="1">
                <selectedIon>
                  <cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="391.283569335938" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/>
                </selectedIon>
              </selectedIonList>
              <activation>
                <cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="26.1322861" unitCvRef="UO" unitAccession="UO:0000266" unitName="electronvolt"/>
                <cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" value=""/>
              </activation>
            </precursor>
          </precursorList>
```

mzXML - mzML (FileConverter):
```
				<precursorList count="1">
					<precursor>
						<isolationWindow>
							<cvParam cvRef="MS" accession="MS:1000827" name="isolation window target m/z" value="391.283569335938" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
						</isolationWindow>
						<activation>
							<cvParam cvRef="MS" accession="MS:1000044" name="dissociation method" />
						</activation>
					</precursor>
				</precursorList>
```

mzML (msconvert) - mzML (Fileconverter)  - information is lost:

```
				<precursorList count="1">
					<precursor spectrumRef="scan=2241">
						<activation>
							<cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" />
							<cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="21.2211094" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO"/>
						</activation>
					</precursor>
				</precursorList>
```

mzML (msconvert) - mzML (Fileconverter - tpp compatible):
```
				<precursorList count="1">
					<precursor spectrumRef="scan=1">
						<selectedIonList count="1">
							<selectedIon>
								<cvParam cvRef="MS" accession="MS:1000744" name="selected ion m/z" value="391.283569335938" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />
								<cvParam cvRef="MS" accession="MS:1000041" name="charge state" value="0" />
							</selectedIon>
						</selectedIonList>
						<activation>
							<cvParam cvRef="MS" accession="MS:1000422" name="beam-type collision-induced dissociation" />
							<cvParam cvRef="MS" accession="MS:1000045" name="collision energy" value="26.132286100000002" unitAccession="UO:0000266" unitName="electronvolt" unitCvRef="UO"/>
						</activation>
					</precursor>
				</precursorList>
```
`MS:1000744` is read in here: 
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L1690

but it is only written out as optional:
https://github.com/OpenMS/OpenMS/blob/develop/src/openms/source/FORMAT/HANDLERS/MzMLHandler.cpp#L3801
```
      if (options_.getForceTPPCompatability() ||
          precursor.getCharge() != 0 ||
          precursor.getIntensity() > 0.0 ||
          precursor.getDriftTime() >= 0.0 ||
          precursor.getPossibleChargeStates().size() > 0)
```

As for the direct conversion via the FileConverter (mzXML to mzML) the mass is directly used as `MS:1000827` 
(`isolation window target m/z `) instead of the `MS:1000744` (`selected ion m/z`) as shown in msconvert. This means I am currently not sure what the correct way is and if filling the MS:1000744 should be forced if the precursor mz is not set otherwise.

**Comment by jpfeuffer** [comment] 2020-08-04 18:12
So, I guess for 1)
- File issue at msconvert
- Meanwhile, if there is another place where the input is stored, you could optionally parse it from there

2)
- add if(... || precursor.mz > 0.0). As soon as there is valuable information, it should be fine to store it.

**Closed** 2020-08-12 12:17 UTC
Labels: defect
