### ISSUE TITLE
Failed to merge featureXMLs by FileMerger

### ISSUE THREAD

**Issue by wtbxsjy** [OpenMS/OpenMS#1615] opened 2015-09-25 02:54 UTC
I am trying to use FileMerger to merge several featureXML files(after IDMapper step) generated from fractionated data. But an error occur as below:

> FeatureXMLFile::store():  found 1 invalid unique ids

The version infomation was shown below:

> FileMerger -- Merges several MS files into one file.
> Version: 2.0.0 Sep 24 2015, 08:40:47, Revision: 6679891

**Comment by hendrikweisser** [comment] 2015-10-02 10:10
Does the FileMerger actually fail if you get this error? If not then you can probably just ignore the error message. (We should still fix it, though.)

**Comment by hroest** [comment] 2015-10-03 07:05
I have seen this warning/error before and usually it still produces a result. However it indicates that there is a bug in FileMerger that we should fix

**Comment by wtbxsjy** [comment] 2015-10-03 11:01
Thanks for your kindly reply. Although the error occur, a result file still produced. I am just wondering whether the file could be used for further analysis or not. If the error will not affect the result file, I can continue my analysis.

**Comment by hroest** [comment] 2015-10-05 17:51
the result file is still produced and will work. so you can continue with your analysis using this file

**Comment by timosachsenberg** [comment] 2015-11-03 08:38
by the way, I think this error message is caused by a unique_id field set to zero in featureXML (the element is not present anymore):
```
    // TODO The next line should be removed in OpenMS 1.7 or so!
    static const XMLCh* s_unique_id = xercesc::XMLString::transcode("unique_id");
```
and
```
      //handle unique id
      String unique_id;
      if (optionalAttributeAsString_(unique_id, attributes, s_id))
      {
        map_->setUniqueId(unique_id);
      }
      // TODO The next four lines should be removed in OpenMS 1.7 or so!
      if (optionalAttributeAsString_(unique_id, attributes, s_unique_id))
      {
        map_->setUniqueId(unique_id);
      }
```

What we probably need to do is to assign a generated unique id if the unique id is INVALID (==0)

**Comment by hendrikweisser** [comment] 2019-04-18 15:40
The primary issue has been resolved and there hasn't been an update in a long time, so I'm closing this ticket.

**Closed by hendrikweisser** 2019-04-18 15:40 UTC
Labels: defect, minor, task
