### ISSUE TITLE
Consensus maps: show sub-maps in different colors [275]

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/OpenMS#275] opened 2014-01-09 10:53 UTC
Submitted by hendrikweisser on 2011-02-25 21:44:33

When sub-features are displayed in consensus maps, they are currently colored according to intensity.

It would be nice if they could alternatively be colored according to the sub-map they come from (e.g. red for features from map 0, blue for features from map 1, etc.).

**Comment by hendrikweisser** [comment] 2019-04-23 09:45
#1621 is a duplicate of this, but has more useful comments, so I'm going to close this ticket.

**Closed by hendrikweisser** 2019-04-23 09:45 UTC
Labels: TOPPView, enhancement, minor
